### ISSUE TITLE
BUG - Air Start A-4 explodes or clips carrier on trap

### ISSUE THREAD

**Issue by DISCOVMA131** [heclak/community-a4e-c#109]
On multiplayer server, air-start A-4E-C will clip severely nose down (e.g., 50-80 degrees nose down) through carrier deck and occasionally explode on trap when landing on carrier.

Does not appear to be dependent on weight, speed or which wire on touchdown.

**Comment by mwlue** [comment]
I'm having this issue in offline mode as well.

**Comment by heclak** [comment]
This seems to be part of the SFM exploding bug we had before. 
I've posted about it here. https://forums.eagle.ru/showpost.php?p=3841356&postcount=22

Please help to test and verify the conditions.

**Comment by Crielaard** [comment]
Same issue.
Both Local hosted MP game, by clients and the host and SP game.

Stennis heading 320
14knots
10kts wind from 320

A-4
90% fuel
on AoA
Vertical speed about 500ft/min on touchdown

Happened with all 4 wires.

Aditionally, the A4 seems to be standing still while the ship moves under it. This stops when using the wheelbrakes.

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
