### ISSUE TITLE
Texture tweaks needed on throttle panels

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#113]
## JATO Panel
Missing line for JATO section. Spoiler label covered by screw. Moving Spoiler label to above the switch might be better.

![image](https://user-images.githubusercontent.com/46121009/54442924-85ed1480-477a-11e9-894a-c6008d5c478f.png)
![image](https://user-images.githubusercontent.com/46121009/54443408-84701c00-477b-11e9-8f45-bfe9935e3ef6.png)
![image](https://user-images.githubusercontent.com/46121009/54443079-e4b28e00-477a-11e9-9a6b-a7a22301bbf0.png)

## Fuel Cutoff
I think there is a label missing above the Fuel Emer Off for the up position ('Norm'?) but it looks like the 3d model is making it a little crammed. The labelling is a little confusing between the switch above it and the fuel emer cutoff lever.

![image](https://user-images.githubusercontent.com/46121009/54443022-c0ef4800-477a-11e9-8c4d-260690c126ca.png)
![image](https://user-images.githubusercontent.com/46121009/54443186-16c3f000-477b-11e9-9fd5-eb929edfe10a.png)

**Comment by callmepartario** [comment]
all set - textures are on google drive and ready for testing.

**Comment by heclak** [comment]
Will merge just before a patch release.
