### ISSUE TITLE
Flaps blowback valve not working

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#122]
A relief valve in the wing flap system allows the flaps to blow back to prevent structural damage when air-loads cause the hydraulic pressure within the actuating cylinder to exceed the pressure at which the relief valve opens (3650 psi). This automatic retraction will begin at approximately 230 KIAS.

NOTE
The flaps will not return automatically to the extended position if the flap handle is in the STOP position; therefore, it will be necessary to reposition the flaps after reducing airspeed below the blowback limit.

**Comment by heclak** [comment]
just checked and the blowback valve is working but blowback occurs at a much higher speed. Will need to check the math behind it.

**Comment by callmepartario** [comment]
flaps blowblack valve is now handled in the EFM.

**Comment by 08jne01** [comment]
This is not true, I fixed something in the lua, not sure if it's as fixed as it should be. I was leaving this open in case it was still not behaving correctly. We can leave this closed though and just make sure it's correct when we write the hydraulics simulation.
