### ISSUE TITLE
Incorrect Engine Control Panel

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#128]
There seems to be some issues with the design of the engine control panel. I can't figure out which panel are we modelling and it makes it inconsistent to add features. Primary feature that I'm adding is fuel dump and possibly some engine features. Would like to confirm the design before looking into the feature set.

![image](https://user-images.githubusercontent.com/46121009/54880076-d3086f00-4e7b-11e9-8564-d3fec1efb9e3.png)

A-4E
![image](https://user-images.githubusercontent.com/46121009/54880083-e61b3f00-4e7b-11e9-85ff-aafad9ea1310.png)

A-4E/F
![image](https://user-images.githubusercontent.com/46121009/54880174-0697c900-4e7d-11e9-9937-96f047309dd8.png)

A-4F
![image](https://user-images.githubusercontent.com/46121009/54880183-1b745c80-4e7d-11e9-9f92-42304a871a2d.png)

**Comment by callmepartario** [comment]
remodeled and textures are ready!
