### ISSUE TITLE
Oxygen switch

### ISSUE THREAD

**Issue by norbot-1** [heclak/community-a4e-c#130]
We have an oxygen indicator on the front panel but no functioning oxygen switch on the left panel. Could the switch be made functional?
![oxygen_1](https://user-images.githubusercontent.com/49375700/55738904-5606f900-5a28-11e9-83b0-3c06cf419804.JPG)
![oxygen_2](https://user-images.githubusercontent.com/49375700/55738912-5901e980-5a28-11e9-9d53-c024efb24f76.JPG)

**Comment by heclak** [comment]
The switch will be made functional. But from my research, that switch just toggles the flow of oxygen to the mask. It isn't a master switch for the oxygen system.

**Comment by heclak** [comment]
Made clickable for next patch.
