### ISSUE TITLE
Gun Sight brightness knob might need updating

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#133]
The gun sight brightness knob might need to be updated to the single knob design instead of the current dual concentric design. Dual design is for the cmptr light.

![image](https://user-images.githubusercontent.com/46121009/57180014-c33a6c80-6eb6-11e9-97de-8bea20b040d5.png)

![image](https://user-images.githubusercontent.com/46121009/57180465-642b2680-6ebb-11e9-85ca-1860118ddb39.png)

**Comment by callmepartario** [comment]
resolved!
