### ISSUE TITLE
missing texture

### ISSUE THREAD

**Issue by WarLord211** [heclak/community-a4e-c#134]
i loaded the A-4E-C.edm in the model viewer. 
extractet all textures and put the in an folder called: textures.
everything is loaded but the model viewer says that an texture is missing:
uvmapshuffer_spec

**Comment by heclak** [comment]
Thanks for the report. I think this is a leftover texture from the spec maps. All the textures have been migrated to PBR and spec maps aren't used anymore. I'll try to remove this from the 3d files.
