### ISSUE TITLE
inaccurate rocket payloads?

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#135]
It has been brought up there might be some inaccuracies in the implementation of rocket pods for the A-4E.

https://www.reddit.com/r/hoggit/comments/bq4g4m/a_few_inaccuracies_with_american_rocket_pods/

Here are some questions that need research/answering:

1. What is the correct type of Zuni rockets that the A-4E should be carrying?
2. Is it incorrect to have the M257 parachute illumination heads for the A-4E? Is it suppose to be carrying another type of illumination flares.
3. Does the A-4E carry LAU-68 pods? We need a detailed list of rocket pods for the A-4E and their differences. Eg. single-fire modes, single/ripple selector, intervalometer, rate of fire, etc.

We can break this topic into multiple bug reports once we can confirm the research behind each point.

**Software Information (please complete the following information):**
 - DCS Version: non-version specific
 - A-4E Version: version 1.3

**Comment by BogdanTudosie** [comment]
I can try to inspect the A-4E Tactical Guide for this if it has not been fixed yet!

**Comment by heclak** [comment]
> I can try to inspect the A-4E Tactical Guide for this if it has not been fixed yet!

Any additional research would be useful here. I haven't had the time to do any research yet.

**Comment by BogdanTudosie** [comment]
Alright, I'll check the Tactical manual and get back to you.

**Comment by BogdanTudosie** [comment]
These are the Zuni rocket models available with engine types.

![53CD74F6-F797-419C-9F82-1D42428EB9B2](https://user-images.githubusercontent.com/4290948/72817730-f2765100-3c72-11ea-85ab-e5d81f17a49b.png)

**Comment by heclak** [comment]
@BogdanTudosie thanks for the research but I think it's best not to post directly from the tactical manual just in case for security reasons. I've removed your image as a precaution.

It would be helpful if you could help look through the current payload in the module to see if anything should be removed/added. That would help ease the workload.

**Comment by BogdanTudosie** [comment]
I asked some people that worked with the Skyhawk on the Ordnance issue to clarify. Manual specifies Zuni in LAU-10s (we got those right) and 2.75 FFARs also, however, I haven't found the specification on the Launcher type. May or may not be LAU-3/A. 

http://skyhawk.org/article/skyhawk-ordnance - Specifies both 2.75 and 5.0 FFARs being used, but still looking to find out which model was used exactly.
