### ISSUE TITLE
other mods override sound definitions

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#138]
**Describe the bug**
When other mods are installed and they overwrite the default sound defs, these sound defs are loaded over the A-4E-C's default sounds as well. Some examples include the engine sounds, gear, and canopy. 

**To Reproduce**
Some known mods that are overwriting the A-4E-C sounds include the MB-339, and SU-57. If these are co-installed in the Saved Games folder then the sounds of the A-4E-C will be changed. 

**Expected behavior**
Sound defs need to be defined in the A-4E-C mod to enforce the choice of sound defs that are used. A list of basic sounds should be generated to create custom sound defs to enforce the choice of sounds.

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.32299
 - A-4E Version: v1.3.1-beta

**Comment by Luciano-LCO489** [comment]
Using DCS Version: 2.5.5.32299 and A-4E Version: v1.3.1-beta as the only module installed i got no landing gear or canopy sounds.

**Comment by heclak** [comment]
So the root cause of this is due to the incorrect folder structure of the Sounds folder in other mods. I'll be restructuring the Sounds folder for the A-4E and working with other modders to make the relevant adjustments to their mods. 

The current list of known mods that are affecting the A-4E-C are:
- MB-339PAN
- SU-57

**Comment by heclak** [comment]
MB-339 has communicated that they will update their files for the next release to the new folder structure.

**Comment by callmepartario** [comment]
closing this issue for now as it's tied into toher external sound issues we'll be tracking through #335
