### ISSUE TITLE
catapult attachment area creeps forward after return to carrier to re launch

### ISSUE THREAD

**Issue by baldawg** [heclak/community-a4e-c#140]
**Describe the bug**
After launching from the carrier and flying pattern back to boat the area for re attachment moves forward.

**To Reproduce**
catapult to attach fly the pattern and trap, attempt to re attach to catapult'

**Expected behavior**
the proximity checks will give you a distance but your aircraft will need to continue forward
to attach.  

**Screenshots**
![image](https://user-images.githubusercontent.com/52021449/59815835-79c7a480-92df-11e9-9405-993dcebe2590.png)

![image](https://user-images.githubusercontent.com/52021449/59815869-91069200-92df-11e9-9960-958ca42953c1.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Release]
 - A-4E Version [e.g. v1.3.1]

**Additional context**
![Screen_190619_214354](https://user-images.githubusercontent.com/52021449/59815934-c612e480-92df-11e9-9ea3-b21da9b47e54.png)
![Screen_190619_214340](https://user-images.githubusercontent.com/52021449/59815944-ce6b1f80-92df-11e9-87b6-16b9182f5035.png)

[baldawgcatapultmiztrk.zip](https://github.com/heclak/community-a4e-c/files/3308618/baldawgcatapultmiztrk.zip)

**Comment by heclak** [comment]
info: this mission requires the following mods:
- 476 vFG Range Targets
- Navy Equipment

**Comment by heclak** [comment]
I've checked the mission file and confirmed that the speed and single waypoint criteria of the carrier are met. There might be a different issue. Will need some people to playtest it over a period of 20 - 40 minutes to confirm the location drift. Is the drift is confirmed then it might be a math accuracy issue in the code. We will need to confirm the behaviour in both SP and MP.

**Comment by heclak** [comment]
Next patch will include an option to bypass the catapult location checks. This should solve the issue with the carrier location going out of sync. Unfortunately, I can't think of a way to better track the carrier location as the unit speed isn't as accurate as we thought. 

![image](https://user-images.githubusercontent.com/46121009/71055500-d45b9380-2190-11ea-8520-4a4073c872bd.png)
