### ISSUE TITLE
EXTERNAL - Cold and Dark Sound Bug

### ISSUE THREAD

**Issue by stebucur** [heclak/community-a4e-c#141]
**Describe the bug**
When the aircraft is spawned cold and dark, it produces a sound similar to the engine starter. This issue persists in a multiplayer environment with 2 player A4s spawned next to each other which also causes sound clipping.

**To Reproduce**
1. Begin the "Cold and Dark" Caucasus Instant Action Mission
2. Spawn In
3. F2 and Observe

**Expected behavior**
The aircraft makes no sound during cold and dark status as nothing is powered or running.

**Screenshots**
N/A

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.32299 Open Beta
 - A-4E Version: 1.3.1 (Development Branch)

**Additional context**

**Comment by Kenokis** [comment]
Same issue experienced

**Comment by heclak** [comment]
Does this happen in both SP and MP?

**Comment by stebucur** [comment]
Yes both Single and Multiplayer.

**Comment by Luciano-LCO489** [comment]
Got that issue either in SP.

**Comment by heclak** [comment]
Found the problematic sound. It's CanopyCommon. Not sure why the sim is asking it to play automatically, didn't notice it previously. I can disable it but I'll find a proper way of solving that problem. I have some code to implement the canopy closing/opening sounds. Will probably fix this issue together with that.
