### ISSUE TITLE
INTERNAL - Mirror Bezel Reflection

### ISSUE THREAD

**Issue by stebucur** [heclak/community-a4e-c#143]
**Describe the bug**
Mirror bezel also acts as a mirror.

**To Reproduce**
1. Turn on Mirrors
2. Observe

**Expected behavior**
The mirror bezel is not reflective and therefore should not reflect.

**Screenshots**
![image](https://user-images.githubusercontent.com/49611412/60062244-c6760a00-973b-11e9-9a32-93c39b371da6.png)

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.32533 Open Beta
 - A-4E Version: 1.3.1 Development Branch (commit: 53aa62b)

**Comment by Kenokis** [comment]
I reproduced this bug too.

**Comment by heclak** [comment]
Probably just a mistake in the material assignment. Should be able to fix this in the next build. Thanks for the report

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by callmepartario** [comment]
all fixed, thanks, heclak!
