### ISSUE TITLE
Missaligned Fuel Panel Switches

### ISSUE THREAD

**Issue by nick10180** [heclak/community-a4e-c#144]
Misaligned switches for Wing fuel pump, drop tanks, fuel cont 

![Screen_190625_135741](https://user-images.githubusercontent.com/52215397/60121529-478bcc00-9751-11e9-8424-4ae8940f8fa8.png)

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.32 Open Beta
 - A-4E Version: 53aa62b

**Comment by heclak** [comment]
The 3D panel has been remodelled to better resemble the real life counterpart but the textures have not been upgraded yet.

**Comment by callmepartario** [comment]
panel has been remodeled and these issues will no longer be present pending the next github binary push.
