### ISSUE TITLE
Incorrect Altimeter Readout

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#146]
**Describe the bug**
The altimeter is not accurately displaying the barometric altitude of the aircraft. This is due to an incorrect function of the getBarometricAltitude() which is provided by the sim to obtain the aircraft's barometric altitude. This cannot be fixed by us as it is a fault of the Lua function provided by the simulator. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an aircraft on any map with the QNH set at 2992
2. Check the correct altitude with the status bar (Ctrl + Y)
3. Altimeter and status bar does not match.

**Expected behaviour**
Barometric altitude output should match the value in the status bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/46121009/60500373-ce5e1d00-9cec-11e9-9bcd-26efe3f0ccdf.png)
This screenshot shows the raw output of the getBarometricAltitude() function with the value converted to feet. The discrepancy can be observed between the status bar and barometric altitude value.

**Software Information (please complete the following information):**
 - DCS Version:  DCS 2.5.5.32533 Open Beta
 - A-4E Version: v1.3.1

**Comment by heclak** [comment]
The issue has been reported on the ED bug forum. https://forums.eagle.ru/showthread.php?p=3967618#post3967618

**Comment by callmepartario** [comment]
altimeter now handled by the EFM
