### ISSUE TITLE
Nevada quickstart missions?

### ISSUE THREAD

**Issue by arrowcircle** [heclak/community-a4e-c#147]
Hi! I found that there are no quickstart missions for nevada map for A-4E Module.
How hard is to make this missions? Is there any docs for it?
If it's easy for newbie to make, I will make pull request.

**Comment by heclak** [comment]
I think the quickstart missions are a work-in-progress on the discord channel. But I can't test/check them since I do not own Nevada. It wasn't included because the testing of those missions didn't make it before the release of v1.3.1. It's planned for the next release.

**Comment by arrowcircle** [comment]
I can help with testing. You mentioned discord?

**Comment by heclak** [comment]
@arrowcircle sorry for the late reply. Yea. We're generally communicating on this discord server but using this issue tracker when it comes to confirmed bugs/development. https://discord.gg/tQZbkTQ

**Comment by callmepartario** [comment]
hey, nice one - i have some in-progress nevada quick-start missions i am tweaking as we test various aspects of the module. hop on discord and @ me (plusnine) and i will be happy to provide!

**Comment by callmepartario** [comment]
added a set of quick-starts for nevada!
