### ISSUE TITLE
3 amber push-button lights will require an alpha-enabled "on" state

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#151]
let's get together to discuss 3-d assignment construction here - should function similarly to the radar altimeter light, but i think there are improvements to be made there, as well.

![image](https://user-images.githubusercontent.com/17432407/60683239-c0cba300-9e64-11e9-820f-f6eee85080d2.png)

**Comment by heclak** [comment]
Yea. I haven't gotten around to animating them yet and I'm not sure what color lights all three of them should be. The engine one looks amber but the others might be red. I know the memory light is suppose to be slightly different with a push to test text on the edge but I don't think it would really be readable anyway so sharing the model should be fine.

Maybe the model should default to an off-state and I'll model the on-state lens cap later. And we could have amber and red on/off states.

**Comment by heclak** [comment]
![image](https://user-images.githubusercontent.com/46121009/60709745-be8c4600-9f43-11e9-8d31-38b0cfe29a95.png)

 Here's how the model is constructed. There is a dome behind the clear cap. So we can assign the lens cap to be transparent_self_illuminated then if you like, something to fill the inside of the indicator. Maybe something that would cause a parallex effect? Or we could just do an opaque texture on the lens cap.

**Comment by heclak** [comment]
I tweak the uv for the indicator as I decided to smooth out the model a bit more. Looked chunky. And I resized it to take up slightly less space on the UV. The new UV is in the drive, here one to figure out which is the on state.
![Inkeduv_engine indicator_NEW_switches_and_knobs_LI](https://user-images.githubusercontent.com/46121009/60715408-8559d300-9f4f-11e9-960d-acd81b8583cc.jpg)

**Comment by heclak** [comment]
I just realised there's a lights texture and inst details that has some indicators on them too. Maybe it's better to consolidate them? I could put the body of the indicator on the switches map but place the on/off lens on the lights or inst_details texture. That way we save on creating a new shader.

**Comment by callmepartario** [comment]
closed, see issue #155
