### ISSUE TITLE
compass panel recession border is unmapped or lacks light reflectivity properties?

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#152]
![image](https://user-images.githubusercontent.com/17432407/60683424-a1814580-9e65-11e9-89a9-1cba889dc819.png)

**Comment by heclak** [comment]
Fixed. It was a problem with the mapping. I've created a separate location for the white background of the sync indicator as I think there will be a problem lining up the background. Check the drive for the UV template.
