### ISSUE TITLE
Incorrect Roughmet file for Boards

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#153]
**Describe the bug**
Incorrect roughmet file including in the latest texture files. The roughmet file for the boards are the same as the one for cockpit switches

![image](https://user-images.githubusercontent.com/46121009/60700008-cab6da00-9f28-11e9-83c3-7a13e27f50f0.png)

![image](https://user-images.githubusercontent.com/46121009/60700073-0ea9df00-9f29-11e9-9c2a-bd4ecdfba0fe.png)

**Comment by callmepartario** [comment]
fixed!
