### ISSUE TITLE
Exhaust Smoke and Differential Braking?

### ISSUE THREAD

**Issue by RevMagnum** [heclak/community-a4e-c#154]
Wouldn't it be nice to have some good old exhaust (engine) smoke just like on the real one? I don't have all the models but SU25T and some other models seem to reproduce it quiet successfully as the smoke builds up depending on the thrust. I'd like to know if there's a way to manually add it. 

Also differential braking doesn't work for me as it doesn't have a binding option. As far as I know the A4 has differential braking and earlier models didn't have power steering and used it to steer the castoring nose wheel.

**Comment by heclak** [comment]
I'll have to look into the engine exhaust smoke again, it's possible and I thought I had left it in the last time. 

As for differential braking, it's not possible in the mod as it is using ED's standard flight model which doesn't feature differential braking. Maybe if we move to an EFM one day but it's not a feature that is possible right now.

**Comment by RevMagnum** [comment]
Just as I thought since I saw a very realistic smoke on Community A4E videos on youtube, I have the 1.3.1 maybe only that one is missing it...Not many might care but I like watching my landing replays :) 
I see about the differential braking, SU25T doesn't have one but TF51D has but that is like PFM I suppose. I hope project would thrive further.

Thanks for the reply.

**Comment by callmepartario** [comment]
IIRC we used to have a slightly thicker exhaust trail and that has somehow gone the way of the dodo, so i feel like it's possible somewhere within even the SFM framework... maybe i'll open the LUA and take a look.

**Comment by heclak** [comment]
Yea. Exhaust smoke broke in v1.3 and I thought I fixed it. I had figured out the issue a while back and thought I had committed the code. I'll commit the code again.

![image](https://user-images.githubusercontent.com/46121009/60957917-0fcb7980-a338-11e9-83da-dca85094af2d.png)

**Comment by heclak** [comment]
Exhaust smoke is fixed in develop branch

**Comment by RevMagnum** [comment]
So is there a quick fix that I can do within the files to get the smoke back or do we wait for a file?

**Comment by heclak** [comment]
@RevMagnum This is the file that you'll need. https://github.com/heclak/community-a4e-c/blob/develop/A-4E-C/A-4E-C.lua

It has not been tested if it causes other problems. If you are willing to be on the bleeding edge, I recommend joining the testing group. That way you can help identify problems before it is even released. It's a great way to help out in the development as well.

**Comment by RevMagnum** [comment]
Thanks a lot for the file but it loads the plane as A-10C...Sure I would like to join and help.

**Comment by Luciano-LCO489** [comment]
Tried installing just the file and got the same problem. You'll need the whole branch files.

**Comment by RevMagnum** [comment]
Are those also different than 1.3.1 because I have 1.3.1 intact.
