### ISSUE TITLE
Marking on AFCS Test Indicators should be white

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#157]
**Describe the bug**
AFCS Test marking should be white with backlighting. Comparing to the reference photo, the marking might need to be wider.

**Screenshots**
![image](https://user-images.githubusercontent.com/46121009/60755983-42206280-a02a-11e9-8a5d-ca2fdac5e0c5.png)

![image](https://user-images.githubusercontent.com/46121009/60755994-63814e80-a02a-11e9-8aa2-ee5a7e1b5046.png)

**Comment by callmepartario** [comment]
my bad, mapping was messed up here. will thiccen for this time around!
