### ISSUE TITLE
"Lift" Text on Emer Fuel Cutoff font and color

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#158]
**Describe the bug**
It's hard to confirm the font on the "lift" but maybe it might be better to use the same font like the ones on the panel labels? I think there's a mil-spec that limits the fonts that can be used for readability. And from references, the metal looks like it should be a darker anodized look. Then a white font color would be able to be used as well. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46121009/60756017-b824c980-a02a-11e9-9c0b-5f4bade04788.png)

![image](https://user-images.githubusercontent.com/46121009/60756028-e73b3b00-a02a-11e9-95b3-8aa677113296.png)

**Comment by callmepartario** [comment]
fixed!

**Comment by callmepartario** [comment]
no problem, will do.
