### ISSUE TITLE
AI A-4 showing afterburner

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#161]
AI A-4 is showing afterburner when launching from carrier.
![image](https://user-images.githubusercontent.com/51857690/61501771-311b0e00-a9a7-11e9-9b3e-9879308b972f.png)

**Comment by heclak** [comment]
yea. this is an issue due to the way we had to implement the catapult. I've reverted the code back to fix this issue for the AI. Unfortunately, that means we won't be able to have exhaust smoke for the A-4. It is an either-or situation. Unless we find a better catapult solution in the future.
