### ISSUE TITLE
Animate stick buttons

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#163]
Please consider animating the stick buttons or at least trim Knob.

**Comment by heclak** [comment]
The trim knob is definitely animated. I'll need to check on the rest as I can't seem to find the functions now.

**Comment by twanmal** [comment]
Hello, i'd love to help but there are at this time no NWS  function for the A4E for example...

**Comment by callmepartario** [comment]
trim knob is definitely animated and working.
