### ISSUE TITLE
Make tail hook lever clickable

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#164]
Tail hook is only usable via key bind but it already got an animated lever. Please consider making it clickable.

**Comment by heclak** [comment]
I've investigated the possibility of this but clickable method for the hook would break the hook in replays/track files. This is an issue with the DCS SFM system which is out of my control. Maybe a solution could be explored again in the future.

**Comment by callmepartario** [comment]
this would be a nice thing to start looking at fixing in the EFM. do we need to do any 3D work to add a connector / click spot?

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
