### ISSUE TITLE
Different radio names on files.

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#165]
Despite not having a working radio, the mod got the AN/ARC-51 radio modeled. When using SRS it show a different radio name (AN/ARC-24). This wrong name is registered in the A-4E-C.lua file and is from there SRS was getting it. Even with that change on the A-4E-C.lua file, SRS will still showing since its distributed with a file registering the wrong radio name (DCS-SimpleRadioStandalone.lua), requiring further contact with SRS devs to apply a correction.

**Comment by andyn** [comment]
Will be fixed as soon as https://github.com/ciribob/DCS-SimpleRadioStandalone/pull/397 gets merged.

**Comment by andyn** [comment]
You may close this bug, as it's been fixed in SRS for a while now.
