### ISSUE TITLE
RWR sound and IR seeker audible outside the plane

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#166]
When using RWR and/or IR seeker active for AIM missiles you can still hear its tones when you switch view from cockpit to any of the external.

Using Develop branch of the mod and DCS 2.5.5.33184.

**Comment by heclak** [comment]
This behaviour is correct if "External View Cockpit Sounds and Radio Messages" is turned on in the Audio Options. The RWR and IR seeker sounds are mapped to the "headphones" output.

![image](https://user-images.githubusercontent.com/46121009/70972419-517a0080-20de-11ea-9d31-5ddb87788a4d.png)
