### ISSUE TITLE
A-4E radar does not go through warmup phase.

### ISSUE THREAD

**Issue by Sirius8952** [heclak/community-a4e-c#167]
**Describe the bug**
When warming up the radar in the A-4E-C current release build, it does not go through the warmup phase.

**To Reproduce**
1. Turn on the radar to STBY.
2. Move to SRCH.
3. See error observed on the radar screen.

**Expected behavior**
The radar will show hopping movement instead of a noise filter applied.

**Screenshots**
N/A

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**
N/A

**Comment by callmepartario** [comment]
cannot reproduce. submitter should ensure they match the server's expected version of v1.3.1.

**Comment by heclak** [comment]
I just checked it in the dev branch which should be the same code. The warmup happens correctly. The hopping/noisy/non-stable radar image is the warmup phase. It takes some time before it stabilizes and shows a proper radar image.

![image](https://user-images.githubusercontent.com/46121009/81030841-d9f61380-8ebc-11ea-81ff-4a65b353e9a3.png)
