### ISSUE TITLE
A-4E engine does not require throttle movement

### ISSUE THREAD

**Issue by Sirius8952** [heclak/community-a4e-c#168]
**Describe the bug**
When starting up the A-4E-C engine, there is no throttle detent movement needed.

**To Reproduce**
1. Apply ground power
2. Click the engine start button
3. De-click the engine start button.
4. Observe RPM.

**Expected behavior**
The engine will naturally startup, even with the start engine button not applied.

**Screenshots**
N/A

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**
N/A

**Comment by callmepartario** [comment]
cannot reproduce. submitter should ensure they match the server's expected version of v1.3.1.

**Comment by DragonRoco** [comment]
I can reproduce sometimes by quickly double clicking on the starter. It starts normally, but the throttle still needs to be clicked to be moveable.

**Comment by callmepartario** [comment]
okay, yes, can confirm this is possible by double clicking the starter real quick.
