### ISSUE TITLE
Outside view stuttering when maneuvering

### ISSUE THREAD

**Issue by joeyjojojunior** [heclak/community-a4e-c#169]
**Describe the bug**
First time trying out the module, I noticed that whenever pitching or rolling, the outside view will oscillate back and forth. This happens both on my monitor and in VR. I am sure it is not a framerate issue. I do not see this behavior in other modules. 

**To Reproduce**
1. Enter free flight
2. Roll the plane 

**Expected behavior**
Outside view should not stutter.

**Screenshots**
Video of behavior (note framerate is >100):
https://youtu.be/hFmmxHCy6zk

Track file:
http://s000.tinyupload.com/?file_id=00493973174590153405

Graphics Settings:
![](https://i.imgur.com/fuA4Dh4.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.5.34108 Open Beta]
 - A-4E Version [e.g. v1.3.1]

**Additional context**
My system:
Gigabyte z-170x ud-3 mobo
i7 6700k @ 4.6 
32GB DDR4 2666
zotac gtx 1070

Please let me know if you need any other info for troubleshooting.

**Comment by LevelPulse** [comment]
That's the SFM flight model.

**Comment by OpTony1982** [comment]
Can it be fixed

**Comment by callmepartario** [comment]
EFM has fixed this issue.

**Comment by OpTony1982** [comment]
Hi, so if I download the latest version will be good
