### ISSUE TITLE
TrackIR

### ISSUE THREAD

**Issue by anyusernameavailable** [heclak/community-a4e-c#171]
I'm really enjoying this mod, but I have TrackIR problems. I have version 1.3.1 .Sorry if this is an issue already reported, I read that that TrackIr issues were resolved, but I still have problems. I'm not sure exactly how this happens (maybe by going to external views & then back to cockpit), but after working fine for awhile, my TrackIr forward view in cockpit becomes completely black. I can look backward & downward in cockpit OK, but not forward.

**Comment by callmepartario** [comment]
after many hours with my TrackIR i have yet to experience this issue. given how long its' been since we've heard, i'm inclined to close this.
