### ISSUE TITLE
"Flaps Down/Up else stop (Hotas)" commands are mixed up.

### ISSUE THREAD

**Issue by bogeyatyour6** [heclak/community-a4e-c#172]
I haven't yet tested if it's just the animation wrong or if it also affects the plane aerodynamics, but then using the keybind described above, the effect is contrary to the function described in the control settings.

This does not occur with the normal commands (not HOTAS). [Flaps Up/Down]

If you need any more information or for me to test another controller, just hit me up.

(I'm easier to reach on the A-4E Community Discord under the same pseudonym) [bogeyatyour6].

Best Regards and thanks for your hard work!

E.K.

**Comment by heclak** [comment]
This was fixed in the develop branch awhile back. It will be included in the next release.
