### ISSUE TITLE
[Engine Control Panel] Wing Fuel switch should be labelled "Dump" instead of "Pump"

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#173]
**Describe the bug**
Incorrect label. Top position should be labelled as "dump" instead of "pump". 

Wing Fuel is the name of the switch. The three modes/positions are labelled DUMP/OFF/EMER TRANS.

**Screenshots**
![image](https://user-images.githubusercontent.com/46121009/71142976-e94d2b00-2253-11ea-932b-95068350f8c4.png)

**Software Information (please complete the following information):**
 - DCS Version: N/A
 - A-4E Version: develop branch

**Comment by callmepartario** [comment]
nice one, this will be fixed in the next set of binaries!
