### ISSUE TITLE
Anti-Collision Light Speed-up Behavior

### ISSUE THREAD

**Issue by Cubeboyy** [heclak/community-a4e-c#175]
**Anti-Collision Light Speed-up Behavior:**
The anti-collision like seems to be rotating excesively fast, giving it an unnatural behavior.

**To Reproduce**

1. Go to cockpit
2. Connect ground power (also happens with engine on)
2. Click on master external lightning switch
3. Click on Anti-collision light switch
4. Go to external view

**Expected behavior**
The speed in which the light rotates should be way slower.

**Software Information:**
 - DCS Version: DCS 2.5.5.39384 
 - A-4E Version v1.4

**Comment by callmepartario** [comment]
thanks for confirming this is not just me. =)

**Comment by heclak** [comment]
So it turns out that the new setup for the AI light is trying to take control of the lights even when it is a player model. I'll need to try and figure out how to work with this controller, or else I might need to abandon the AI model improvements or figure out an alternative animation.
