### ISSUE TITLE
CONTROL HYD ladder is set up differently than the rest

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#176]
The CONTROL HYD light's setting differ from the other ladder lights, producing distracting results in some lighting conditions:

![image](https://user-images.githubusercontent.com/17432407/71366948-743e6600-2571-11ea-8e19-58524f16b3f1.png)

**Comment by callmepartario** [comment]
upon further examination, this appears to be an animation issue!

**Comment by heclak** [comment]
Fixed.
