### ISSUE TITLE
Console Flood Light Lighting 

### ISSUE THREAD

**Issue by Cubeboyy** [heclak/community-a4e-c#177]
**Console Flood Light Brightness Spike**
When turning the nob to turn on the lights there is a spike in brightness, it seems to be close to what the BRIGHT setting has in terms of brightness; even if the Console Light Intensity Switch is set to DIM or MEDIUM, then the brightness falls to the indicated brigtness.

**To Reproduce**

1. Go to cockpit
2. Set the Console Flood Light Intensity switch to DIM or MEDIUM
2. Turn the Console Flood Light nob just a bit.
3. Observe behavior.

**Expected behavior**
The brightness would follow the option set on the Intensity Switch, as expected.

**Software Information:**

-DCS Version: DCS 2.5.5.41371
-A-4E Version: v1.4

**Comment by callmepartario** [comment]
IIRC, this is intentional behavior. heclak can confirm, but i believe this is expected behavior to flipping that switch.

**Comment by heclak** [comment]
I've fixed this behaviour for when the knob is turned but I didn't correct the behaviour for when the flood brightness toggle switch is changed as the effect looks quite interesting.
