### ISSUE TITLE
AFCS does not work with MS FFB2 joysticks

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#179]
The AFCS does not work when an MS FFB2 joystick is used due to a failure in the iCommandPlaneTrimRollAbs function not working correctly. Since the AFCS roll stabilisation is dependent on this function, a rewrite is required to use the iCommandPlaneTrimRoll function which is a relative trim function which is functioning correctly.

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-2
