### ISSUE TITLE
Hook and Wire don't meet when you land on carrier

### ISSUE THREAD

**Issue by mustang60348** [heclak/community-a4e-c#182]
Would it be possible to have the Hook and the wire 'touch' when you catch the wire, right now they are very far apart?

**Comment by heclak** [comment]
This is probably due to use of SFM, if so only ED can fix this. ED doesn't seem to be invested in patch SFM issues anymore so I don't think this will ever be fixed by them.

**Comment by heclak** [comment]
Tweaked in the latest beta but there is still some desync. Closing as it seems to be the best that SFM can offer.
