### ISSUE TITLE
radio and air refueling

### ISSUE THREAD

**Issue by MavPL** [heclak/community-a4e-c#183]
Will the radio work to contact aircraft carriers, ATC, AVACS and others? Will it be possible to repair the navigation lights and landing lights? Can you fix the mistake that the plane does not stick to the deck of the aircraft carrier, just leaves the deck and you need to keep it on the brake, or put on chocks. One more thing. In the model, you missed the engine exhaust gas animation, can you add it? By the way. Your A-4E model is great except for the things that are missing

**Comment by callmepartario** [comment]
all these items are addressed in other recorded or resolved issues.
