### ISSUE TITLE
Catapult thrust boost still present on land runways

### ISSUE THREAD

**Issue by FlyingPetRock** [heclak/community-a4e-c#184]
Catapult thrust boost still present on land runways after spawning on carrier, then landing on runway.

Tried hitting alt 1 to "reset" status to land runway and it was still present.

Tried hitting alt 1 and alt 2 to "reset" status and still present.

Will test with chocks on next session to see if that will reset aircraft status.

Dev branch, version 1.4 on GaCW MP, Steam Open Beta.

**Comment by callmepartario** [comment]
is this still the case? i suppose certain runways that are at carrier deck elevation could cause this. with the EFM around the corner, it may not matter.

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
