### ISSUE TITLE
improve axis / input overlay

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#185]
To make the module consistent with the DCS ecosystem, it would be nice to add a controls indicator. Unfortunately, there is no generic script for it and all modules have their own code solution to it. It is not ethical to just rip off the entire code from another module so it would be needed to code this from scratch. This could be useful to other modules as a template code.

![image](https://user-images.githubusercontent.com/46121009/73610336-00cc5180-4611-11ea-882b-5bef84602053.png)

**Comment by AustinLeath** [comment]
I agree with this, I might be able to mock something up if you guys would be interested with some help with that.

**Comment by heclak** [comment]
@AustinLeath There's a standard controls indicator with all aircraft, unfortunately it isn't a standard piece of code in the main install that I can just link to. Weirdly, all the various module implement it in a different way (code-wise). Since we don't want to copy/paste someone else's code out of respect, we'll need to code it ourselves manually. If you want to take a go at it, please go ahead. Just leave a message here so we know not to duplicate our resources to the same issue.

**Comment by AustinLeath** [comment]
> @AustinLeath There's a standard controls indicator with all aircraft, unfortunately it isn't a standard piece of code in the main install that I can just link to. Weirdly, all the various module implement it in a different way (code-wise). Since we don't want to copy/paste someone else's code out of respect, we'll need to code it ourselves manually. If you want to take a go at it, please go ahead. Just leave a message here so we know not to duplicate our resources to the same issue.

Okay, I tried hard over these past two weeks to get it working to no avail. I will be working on my other projects instead. Go ahead and have another member of the team take over this issue.

**Comment by callmepartario** [comment]
note to self, start looking into this.
