### ISSUE TITLE
ASN-41 D2 Longitude knob not working

### ISSUE THREAD

**Issue by Luciano-LCO489** [heclak/community-a4e-c#187]
On devs branch:

ASN-41: In D1 both knobs lat and long work by just scroll. But in D2 Lat just work with click and scroll and long wont work.
Also wind speed and direction are just adjustable when on STBY.

**Comment by heclak** [comment]
Thanks. I've fixed the bug with the D2 Long knob in D2 mode.

What is the issue with the wind speed and wind direction knobs? You are supposed to be able to set the wind speed and direction on the nav panel in STBY mode. This is written on page 1-62 of the NATOPS.

**Comment by heclak** [comment]
I've pushed the bugfix to a separate branch. I'll merge it in after clarifying the issue about the wind speed and direction knobs. I'll continue fixes on that branch if additional fixes are required.

**Comment by heclak** [comment]
Closing this as it is fixed on the develop branch
