### ISSUE TITLE
seat height adjustment

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#188]
it might be nice if we could add a feature to adjust the default viewspace up or down - this would be especially for users without a headtracking solution who want to edge out a bit more skybox. bonus if we could animate the seat itself up or down a tad... will re-check the manual to see if/how this was done by the pilot, these things were so small.

**Comment by heclak** [comment]
I know this can be done if an EFM is used. Not sure about SFM/Lua. Lots of functions were only implemented in C++ as ED abandoned Lua development.

There's a seat adjustment switch somewhere in some models.

**Comment by callmepartario** [comment]
right on, just was logging a request someone made, deffo not something we need to worry about for 1.4 =)
