### ISSUE TITLE
ground start - hydaulics / wheel release?

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#189]
**having weird on-ground behavior while cold starting**
during a cold ground start, after the engine has spooled, but before throttling up or moving the aircraft's wheels, some hydraulic systems are non-responsive. notably, the flaps and spoiler arm switch are not functional until the aircraft has rolled (the airbrake appears unaffected).

**To Reproduce**
1. Ask for ground power and start the engine normally.
2. Before rolling the aircraft forward, test the flaps up and down for responsiveness. Arm the spoiler switch and note its movement (or lack thereof)
4. Press the wheel brake button or roll the aircraft forward by throttling up, and then test hydraulic responsiveness.

**Expected behavior**
Once the engine has become stable at 50%, the hydraulics used to be active at that time (correct me if I'm wrong).

**Software Information (please complete the following information):**
 - DCS Version: [Open Beta]
 - A-4E Version [v1.4 dev]

**Additional context**

**Comment by heclak** [comment]
So the hydraulics system is hardcoded for an RPM for 55% for the hydraulic pressure to kick in. The idle rpm has also been set to 55%. Looking at the engine performance checks for idle rpm, it should be higher than that. I'm not sure how DCS is simulating external temp vs engine rpm. If someone can do some tests to map the relationship better engine idle rpm and external temp then that would be helpful. Acceptable idle rpm range for 55.7 - 58.3% at 80°F (26.67°C).

That way we'll know if the engine idle rpm needs to be tuned higher or the hydraulic system needs to be tuned lower.

**Comment by callmepartario** [comment]
awesome, i saw the lights kick in so this clarification makes a lot of sense and i see the value in the change. thanks for clarification!
