### ISSUE TITLE
I'm not allowed to commit war crimes...

### ISSUE THREAD

**Issue by AeroShrek** [heclak/community-a4e-c#193]
Releasing Mark-77's causes the game to instantaneously crash.

To Reproduce:
I set up a bombing run in the Caucasus over a forest.  On pylon 3 I had 2x Mk 77 Mod 1's and on pylons 2 and 4 I had 1x Mk 77 mod 1's.  My reticle, altitude, and speed were the same as if I was dropping Mk 82's.  However, when I pressed the weapon release button, I was booted out of the game.  It is important to note that I was using the the latest OpenBeta build of DCS (2.5.6).

I expected the bombs to simply release and burn the ground below, but instead, DCS World crashed.

**Software Information (please complete the following information):**
 - DCS Version: DCS OpenBeta 2.5.6
 - A-4E Version: The latest, I think it is 1.3.1

**Comment by AustinLeath** [comment]
I too just experienced this with the same software information

**Comment by heclak** [comment]
I just tried this and I couldn't recreate it with the dev branch so I assume that it either only happens with the old version or it is a bug in the 2.5.6 version of DCS. Please let me know if you are still able to recreate this with the latest version of DCS.

**Comment by heclak** [comment]
closing this until someone can recreate it. I think it was just an issue in the base sim.

**Comment by AeroShrek** [comment]
Sorry, I haven't had time to try it again.  I will try to remember tomorrow
and update you.  I'm guessing it isn't a problem anymore, due to the
updates that your A-4 and DCS have gone through.

**Comment by AeroShrek** [comment]
I just recreated the situation, and luckily, I didn't experience any crashes.
