### ISSUE TITLE
Issue at lift off and touch down.

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#195]
**Describe the bug**
When take off and landing, at the lift off/touch down, I feel a sharp and small change in attitude(pitch and heading), no matter if I correct the wind, if I set zero wind, always I realize this sharp movement like if the ACFT was matching the heading with the trajectory.

**Expected behavior**
No SHARP change in Heading/Pitch during this events. If little heading discrepancy during touch down, the aircraft is expected to skid.

**Software Information (please complete the following information):**
 - DCS Version: Open Beta 2.5.5
 - A-4E development version

**Additional context**

**Comment by heclak** [comment]
This is an issue with the DCS FM, not the A-4E. Can't be fixed by us.
