### ISSUE TITLE
White flood light dimmer control

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#196]
After using the WHITE LIGHT DIMMER, if I don't click in any other switch before rotate other rotary like SHRIKE, RED FLOOD LIGHTS or PANEL BACKLIGHT, it seems to be still attached to the WHITE DIMMER.

**To Reproduce**
1. Rotate white light dimmer;
2. Try to rotate another dimmer or volume selector;
3. You still control the white dimmer;

**Expected behavior**
Once stop adjusting a dimmer, the rotation should be de attached.

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version:  OPEN BETA 2.5.5
 - A-4E Version development version

**Comment by heclak** [comment]
bug cannot be reproduced. closing.
