### ISSUE TITLE
AI ACFT crashes if spawned ParkingHot or Ramp on Carrier

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#198]
**Describe the bug**
If set an AI squadron to spawn on Carrier ParkingHot or Ramp, it fails to launch and get stucked in the ship's border.

**To Reproduce**
1. Go to MISSION EDITOR AND SET AN A-4 SQUADRON TO NOT START AT RUNWAY;
2. Proceed to start mission;
3. Wait until it tries to take off.

**Expected behavior**
Take off as expected.

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.5 Release
 - A-4E Version v1.4 Alpha

**Additional context**

**Comment by callmepartario** [comment]
closing this issue in favor of a newer issue set for the EFM.
