### ISSUE TITLE
Upper red beacon issue

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#199]
**Describe the bug**
If set the MASTER LIGHTS to OFF on HOTAS while  Red Beacon switch is ON, the light still illuminates the fuselage.

**To Reproduce**
1. Set master lights ON;
2. Set Anti Colision Lights ON;
3. Set master lights OFF or Cut off Engines or Remove External power;
4. Check the illumination on upper fuselagem;
5. Whichever of the options above cause the same effect.

**Expected behavior**
Stop illuminating.

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: Release 2.5.5
 - A-4E Version 1.4 Alpha

**Additional context**

**Comment by heclak** [comment]
Fixed. Thanks for reporting.
