### ISSUE TITLE
external textures not selectable by livery

### ISSUE THREAD

**Issue by alevs** [heclak/community-a4e-c#201]
Edited pilot skin not working, the lua's commands to call the new texture not respondig.

**Comment by BlueMarvel1914** [comment]
{"Pilot", 0, "a4e_pilot", false}; should work.

**Comment by callmepartario** [comment]
tailhook, rear gear also fall into this boat - other parts of the cockpit may fall into the same boat. this is low priority, but would be nice since memory is being used for the tailhook and gear textures (they share the plane's bottom sheet).

**Comment by callmepartario** [comment]
updated description luas in the next patch will address these issues.
