### ISSUE TITLE
Non-polished exhaust and tailhook.

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#202]
**Is your feature request related to a problem? Please describe.**
The exhaust pipe and engine turbine outlet are too shiny/clean.  The bare metal external exhaust 'shield' (the bit visible on the outside of the aurcraft) would have discoloration from being tempered by the exhaust heat.

The Tailhook appears to be shiny metalic on all the models as well.  Is there somewhere to paint this to the underside colour (or with the hazard lines around it as some do).

**Describe the solution you'd like**
Dirty/Carbon the exhaust up please, and have the template include it, and advise where to paint the tailhook (or include it in the template too) and advise how to reference them in the description.lua file.

**Describe alternatives you've considered**
Describe where the texture is and how to specify it in the description.lua file (and any other paramaters that share that texture) so I can change it myself?

**Additional context**
![Screen_200426_171504](https://user-images.githubusercontent.com/64348065/80300684-2c12a700-87e2-11ea-9805-80141d5a5194.jpg)

**Comment by heclak** [comment]
The textures for this were already updated in the dev branch. I'll leave @callmepartario to advise about the paintkit.

![image](https://user-images.githubusercontent.com/46121009/80935253-5d9cfb00-8dfe-11ea-8c23-df7075d6dda1.png)
