### ISSUE TITLE
add BORT placements for Royal Australian Navy

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#203]
**Is your feature request related to a problem? Please describe.**
Can the Bort template and system be added for the font and character sizing of the Royal Australian Navy Side Numbers be added.  The US navy and US style ones are not the right aspect ratio, font, position or size.  Normally the characters are modelled with the RCN_80_ATH font, which is taller and narrower than the US fonts.

**Describe the solution you'd like**
Add textures and model components/references in the .lua file for the RAN side numbers.
The RAN only uses the numbers on the forward fuselage, not he wings, rudder, tail, or other locations.  The location is such that the numbers don't run excessively over the curve to the top of the fuselage in front of the cockpit (distorting them), and start just above the refuelling boom.

**Describe alternatives you've considered**
Making individual skins for each aircraft without using the BORT system.

**Additional context**
![Screen_200426_180622](https://user-images.githubusercontent.com/64348065/80301757-574cc480-87e9-11ea-87c5-2f56f7a13ea0.png)
![Screen_200426_180501](https://user-images.githubusercontent.com/64348065/80301760-5b78e200-87e9-11ea-9177-f52bf8051739.png)

RCN_80_ATH font file
[rcn8b.zip](https://github.com/heclak/community-a4e-c/files/4534897/rcn8b.zip)

**Comment by heclak** [comment]
Is this screenshot one of the corrected ones or an incorrect one? I need a little help in identifying what exactly needs to be done as liveries aren't my speciality. If you could annotate on the images and add a before/after/reference image then I can try and see if it's within my means.

**Comment by Bungo71** [comment]
The screenshot is of the correct ones in the correct locations, and the font attached is the font.  They are universally black in all real world scenarios.

Thanks

Braedon

**Comment by Bungo71** [comment]
![A4E-C-Correct-Font](https://user-images.githubusercontent.com/64348065/81947998-8b771080-9644-11ea-82ed-4b0d1d2e315e.jpg)
![A4E-C-Incorrect-Font](https://user-images.githubusercontent.com/64348065/81948009-8dd96a80-9644-11ea-80d5-5b9d4578beec.jpg)

**Comment by callmepartario** [comment]
this is a nice thought, but ultimately out of scope to attend to each and every possible modex placement.
