### ISSUE TITLE
With CANOPY in OPEN position, if an ejection occurs, the canopy remains on the plane.

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#205]
When on ground, canopy open, if an ejection occurs, the canopy does not detach from the ACFT.

**To Reproduce**
1. On ground;
2. Open Canopy;
3. Command an ejection;
4. Observe the canopy in the position.

**Expected behavior**
Canopy also being ejected.

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.4192 OB
 - A-4E Version v1.4 BETA

**Comment by heclak** [comment]
This is a bug in DCS. You can report it to ED. I tried this with the A-10C and get the same result.

**Comment by 08jne01** [comment]
Heclak says it's a bug with DCS not the A-4.
