### ISSUE TITLE
Odd reflective patch underwing from the gear door along the spar

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#206]
**Describe the bug**
There is a reflective section of all skins along the spar of the starboard wing from the gear door corner where it meets the front wing spar, following the wing spar outboard under the first stores station.  Not apparent on the port wing.

**To Reproduce**
1. Any skin, including skins bundled in the 1.3.1 download
2. View from under the wing and manouver so that the lighting changes in that area to see the reflectivity better.  As per the attached images
3 The more reflective the roughmet the more pronounced is the effect.

**Expected behavior**
It shouild represent the roughmet patterns (see images attached) but these don't show any indication that this area should be different to the rest of the airframe.

**Screenshots**
A custom skin with increased reflectivity.
![More-Reflective-bug](https://user-images.githubusercontent.com/64348065/81944449-202b3f80-9640-11ea-89aa-ba602f78321b.jpg)

The included, unmodified, Australian Navy Livery
![Reflective-bug](https://user-images.githubusercontent.com/64348065/81944498-30431f00-9640-11ea-9525-0cf21a8a221d.jpg)

The area on the default roughmet texture.
![A4G-724-RAN-Lower_RoughMet](https://user-images.githubusercontent.com/64348065/81944520-376a2d00-9640-11ea-8e00-6048272ed653.jpg)

**Software Information (please complete the following information):**
 - DCS Version: 2.5.5.41371 stable
 - A-4E Version 1.3.1

**Additional context**

**Comment by Bungo71** [comment]
Just tried 1.4 beta 4 on DCS OpenBeta and this effect seems to be absent, so it may have been resolved already.

cheers

Braedon

**Comment by heclak** [comment]
Yea. We had fixed this a while back on the 1.4 branch.
