### ISSUE TITLE
Compatibility with the new Supercarrier Module?

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#207]
**Is your feature request related to a problem? Please describe.**
No, other than currently it is only compatible with the Stennis, and only under certain circumstances. (according to the guide, anyway, if this is not the case, the guide may need to be updated).

**Describe the solution you'd like**
Can the Skyhawk be made compatible with the new Supercarrier module?

**Describe alternatives you've considered**
Nil

**Additional context**
Currently have issues gettig the plane to sit still on a moving carrier (or should I say, moving with the carrier instead of moving backwards under the carrier, regardless of the orientation on the carrier), and the inability for the system to recognise that the aircraft is able to hook into the catapult despite being in the correct location and direction (unless a runway start is specified).

**Comment by heclak** [comment]
version 1.4 will bring new compatibility options, we've already tested it to be working with the Sao Paulo A12 carrier and the Charles de Gaulle carrier. Catapult positioning issues will be resolved with version 1.4 for both single-player and multiplayer modes.

Unfortunately, I don't have the Supercarrier module so I can't work on figuring out what needs to be done. But I believe it definitely requires radios which would mean that we are out of luck.

**Comment by 08jne01** [comment]
Implemented in v2.0.0-beta-1
