### ISSUE TITLE
Ability to talk to ground crew with canopy closed.  Rearm-refuel with the engine operating.

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#208]
**Is your feature request related to a problem? Please describe.**
Unable to talk to ground crew with the canopy closed, despite the ground crew clearly communicating via radio/intercom so the canopy position seems to be irrelevant (??).  It is able to be done in other aircraft (along with the re-arm/refuelling with the engine on).

**Describe the solution you'd like**
Be able to talk to ground crew or re-arm/refuel regardless of canopy position.
Ideally given the carrier limitations, be able to re-arm refuel with the engine on and the canopy closed so you don't have to shutdown and open the canopy while attached to the cat and start back up again.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by heclak** [comment]
The last I checked, ED placed the intercom functionality with the radio SDK which is unavailable to us. I've tried to try and achieve it without the SDK files a couple of times without success. So at the moment, it's not possible without several header files from ED.

In the near future, this isn't possible unless we get some changes from how ED decides to implement the intercom and radios systems.

**Comment by Bungo71** [comment]
That's OK.  Thanks
