### ISSUE TITLE
Excessively reflective windshield frame.  Blindingly reflects sun.

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#209]
**Describe the bug**
The cockpit windshield frame catches the sun as a reflective surface (more than the mirrors do).

**To Reproduce**
1. In cockpit, manouver the aircraft so that the sun reflects off the cockpit windscreen frame

**Expected behavior**
Should be non-reflective like the rest of the cockpit frame.  Colours of the frame suggest that the frame should not be reflective.

**Screenshots**

This can happen in several locations on this frame (left & right)

![Screen_200514_213908](https://user-images.githubusercontent.com/64348065/82052613-4b289880-96ff-11ea-9c4c-a894a07377fb.jpg)

**Software Information (please complete the following information):**
  - DCS Version: 2.5.5.41371 stable
  - A-4E Version 1.3.1

**Additional context**

**Comment by callmepartario** [comment]
these surfaces have been painted and will no longer reflect the sun in the 2.0 release.
