### ISSUE TITLE
"Rudder" in Axis Commands is not bindable via controller axis, keyboard, or controller button

### ISSUE THREAD

**Issue by asherao** [heclak/community-a4e-c#210]
**Describe the bug**
The "Rudder" entry on the A-4E-C Axis Commands section of Control Options is grayed out and not selectable for an xbox one controller or g27 Logitech racing wheel.

**To Reproduce**
1. Launch DCS
2. Click Options
3. Click Controls
4. Click Axis Assign
5. Scroll down to Rudder (not "Rudder Axis")
6. Attempt to assign an xbox one or g27 controller to the axis

**Expected behavior**
To be able to assign a xbox one or g27 controller axis to "Rudder".

**Screenshots**
![2020-05-15 23_03_16-Digital Combat Simulator](https://user-images.githubusercontent.com/15984377/82059210-ac9d3700-9700-11ea-8033-4f87a1e5b8f5.jpg)

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.47404 Open Beta
 - A-4E Version v1.3.1

**Additional context**
The entry for "Rudder Axis" works as expected. Suggest either removing one or combining them. "Rudder" only works for my Thrustmaster Warthog axis controls.

**Comment by heclak** [comment]
The "Rudder" binding was a leftover from your older version. I've cleaned up the bindings and it should be fine now.
