### ISSUE TITLE
keybind requests

### ISSUE THREAD

**Issue by asherao** [heclak/community-a4e-c#211]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
-Remove duplicated multiplayer chat binds
-Default Show/hide Stick to "Backspace"
-Button categories as according to what panel they are on. eg "AFCS Panel" or "AFCS".
-Discrete Radar Tilt keybinds. Example: 0, 5 Up, 10 Down
-Fuel Dump Switch - DUMP
-Fuel Dump Switch - OFF
-Fuel Dump Switch - EMER TRANS
-Fuel Control Switch - MANUAL 
-Fuel Control Switch - PRIMARY
-JATO Switch - ARM
-JATO Switch - STBY
-JATO Jettison Switch - JETTISON
-JATO Jettison Siwtch - SAFE
-Gunpod Switch - CHARGE
-Gunpod Switch - OFF
-Gunpod Switch - CLEAR
-Gunpod Station LH Switch - READY
-Gunpod Station LH Switch - OFF
-Gunpod Station CTR Switch - READY
-Gunpod Station CTR Switch - OFF
-Gunpod Station RH Switch - READY
-Gunpod Station RH Switch - OFF
-APR-25 Power Switch - ON
-APR-25 Power Switch - OFF
-APR-27 Power Switch - ON
-APR-27 Power Switch - OFF
-APR-25 Missile Volume - CCW
-APR-25 Missile Volume - CW
-APR-25 PRF Volume - CCW
-APR-25 PRF Volume - CW
-APR-25 Missile Volume Axis
-APR-25 PRF Volume (Axis)
-ECM Selector Knob - OFF
-ECM Selector Knob - STBY
-ECM Selector Knob - REC
-ECM Selector Knob - RPT OFF
-ECM Selector Knob - CCW
-ECM Selector Knob - CW
-Gun Sight Knob - BRT
-Gun Sight Knob - OFF
-Gun Sight Knob - CCW
-Gun Sight Knob - CW
-Gun Sight Day/Night Switch - DAY
-Gun Sight Day/Night Switch - NIGHT
-Gun Sight Elevation Control - Increase
-Gun Sight Elevation Control - Decrease
-Station 1 Selector Switch - OFF
-Station 2 Selector Switch - OFF
-Station 3 Selector Switch - OFF
-Station 4 Selector Switch - OFF
-Station 5 Selector Switch - OFF
-Station 1 Selector Switch - READY
-Station 2 Selector Switch - READY
-Station 3 Selector Switch - READY
-Station 4 Selector Switch - READY
-Station 5 Selector Switch - READY
-Master Arm - OFF
-Master Arm - ON
-AWRS DROP INTVL Control - CCW
-AWRS DROP INTVL Control - CW
-AWRS DROP INTVL Control - 20
-AWRS DROP INTVL Control - 50
-AWRS DROP INTVL Control - 80
-AWRS DROP INTVL Control - 110
-AWRS DROP INTVL Control - 130
-AWRS DROP INTVL Control - 150
-AWRS DROP INTVL Control - 170
-AWRS DROP INTVL Control - 200
-AWRS MULTIPLIER Switch - x1
-AWRS MULTIPLIER Switch - x10
-AWRS Quantity - OFF
-AWRS Quantity - 2
-AWRS Quantity - 3
-AWRS Quantity - 4
-AWRS Quantity - 5
-AWRS Quantity - 6
-AWRS Quantity - 9
-AWRS Quantity - 12
-AWRS Quantity - 15
-AWRS Quantity - 20
-AWRS Quantity - 30
-AWRS Quantity - 40
-AWRS Quantity - CCW
-AWRS Quantity - CW
-AWRS Mode Select - STEP SALVO
-AWRS Mode Select - STEP PAIRS
-AWRS Mode Select - STEP SINGLE
-AWRS Mode Select - Ripple SINGLE
-AWRS Mode Select - Ripple PAIRS
-AWRS Mode Select - Ripple SALVO
-AWRS Mode Select - CCW
-AWRS Mode Select - CW
-ARC-51 UHF Frequency Mode - PRESET CHAN
-ARC-51 UHF Frequency Mode - Manual
-ARC-51 UHF Frequency Mode - Ground Transmit
-ARC-51 UHF Squelch Disable Switch - ON
-ARC-51 UHF Squelch Disable Switch - OFF
-ARC-51 UHF Squelch Disable Switch - Toggle
-ARC-51 UHF 10MHz - Increase
-ARC-51 UHF 10MHz - Decrease
-ARC-51 UHF 1MHz - Increase
-ARC-51 UHF 1MHz - Decrease
-ARC-51 UHF 50MHz - Increase
-ARC-51 UHF 50MHz - Decrease
-ARC-51 UHF  Mode - OFF
-ARC-51 UHF  Mode - Transmit Recieve
-ARC-51 UHF  Mode - Transmit Recieve + Guard
-ARC-51 UHF  Mode - ADF
-ARC-51 UHF  Mode - CCW
-ARC-51 UHF  Mode - CW
-TACAN Channel 1s - Increase
-TACAN Channel 1s - Decrease
-TACAN Channel 10s - Increase
-TACAN Channel 10s - Decrease
-TACAN Mode - OFF
-TACAN Mode - REC
-TACAN Mode - T/R
-TACAN Mode - ILS
-TACAN Mode - CCW
-TACAN Mode - CW
-TACAN Volume - Increase
-TACAN Volume - Decrease
-Compass Latitude Knob - CCW
-Compass Latitude Knob - CW
-Compass Heading Knob - CCW
-Compass Heading Knob - CW
-Compass Mode Switch - FREE
-Compass Mode Switch - SLAVED
-Compass Push to Sync
-Seat Switch - UP
-Seat Switch - DOWN

**Describe alternatives you've considered**
None.

**Additional context**
Named switch positions are capitalized.

**Comment by asherao** [comment]
I would like to see all controls keybound so that all user are "on the same page" if a utility, such as VoiceAttack or a custom HOTAS setup is used and shared.

**Comment by callmepartario** [comment]
an extensive request like this implies one is building their own control surface. if you want to pull a branch and develop these inputs, let's talk, but these kinds of extensive input requests are a bit out of scope for the project.

**Comment by asherao** [comment]
> an extensive request like this implies one is building their own control surface. if you want to pull a branch and develop these inputs, let's talk, but these kinds of extensive input requests are a bit out of scope for the project.

No, just for voiceattack and to match the level of some of the other DCS modules. Understood.
