### ISSUE TITLE
improve kneeboard

### ISSUE THREAD

**Issue by asherao** [heclak/community-a4e-c#213]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i cant remember how to start the aircraft.

**Describe the solution you'd like**
A step by step, immersive, Startup Procedure kneeboard page.

**Describe alternatives you've considered**
Implemented Autostart function

**Additional context**
The A-4E Community Guide may be useful for reference.

**Comment by heclak** [comment]
I'm not too sure about this one. It's very easy to add too much clutter to the kneeboard. If we add a startup procedure then we'll need to add for all the other stuff too. When does it end? Before you know it, its 60 pages long.

Autostart might be something. Although we honestly never had to look into it as the startup procedure is already so short.

**Comment by asherao** [comment]
"When does it end?" When contributors don't what to make more kneeboard pages :D.

**Comment by callmepartario** [comment]
i will work to add the following pages to kneeboard set:
- a quick-start checklist
- bombing computer setup
- a bombing table
- a case III recovery landing reference (do not steal, create an original)
