### ISSUE TITLE
implement IFF panel

### ISSUE THREAD

**Issue by asherao** [heclak/community-a4e-c#214]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
IFF panel implemented to at least the level of switches doing what they say

**Describe alternatives you've considered**
None.

**Additional context**
Having a working IFF panel will possibly integrate with SRS and future DCS.

**Comment by callmepartario** [comment]
given DCS doesn't properly simulate IFF to begin with, i'm closing this issue as a lost cause for now.
