### ISSUE TITLE
create external variants (bent refuelling probe, no hump, etc.)

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#215]
**Is your feature request related to a problem? Please describe.**
No issue.

**Describe the solution you'd like**
Is it possible to consider options in future releases for:

- the bent refuelling probe instead of the straight one.
- humpless fuselage the same as the A-4G and many variants that were converted from earlier a-4B & C airframes.

I'd go so far as to suggest that the A-4M would be a nice offshoot as I always thought they looked nicer, but that may be too much of an ask...   :-)

Possibly as separate models (like the L-39C/ZA have, or the Spitfire IX regular and CW variants do).

**Describe alternatives you've considered**

**Additional context**
Many of the bundled liveries and community created liveries are for these pre-hump versions, with/without the bent refueling probes, or in the case of the Brazilian livery (dare I say it) variants of the A-4M/N/KU

All as food for thought suggestions.

regards

Braedon

**Comment by callmepartario** [comment]
closing this due to lack of capacity and plausible interest.
