### ISSUE TITLE
external airframe unwrap issues

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#216]
**Describe the bug**
Some texture mapping issues that need be documented for future attention.

**Screenshots**
![Screen_200521_010539](https://user-images.githubusercontent.com/64348065/82466590-f8d2e780-9b03-11ea-9d85-bc17e1337fef.jpg)
![Screen_200521_010659](https://user-images.githubusercontent.com/64348065/82466748-228c0e80-9b04-11ea-8655-e7ee613d6b5e.jpg)
![Screen_200521_010611](https://user-images.githubusercontent.com/64348065/82466385-b14c5b80-9b03-11ea-9e3d-bb9c19359332.jpg)

**Software Information (please complete the following information):**
 - DCS Version:    2.5.5.41371 stable
 - A-4E Version:   1.4 Beta 7 and before

**Additional context**

**Comment by heclak** [comment]
The spoilers are an easy fix. Done that already. The rest is a little more extensive so I'll leave them for a future fix.

**Comment by heclak** [comment]
Normals issue with the spoilers is fixed in beta-8

**Comment by Merker6** [comment]
Was the probe fixed? Fairly easy fix from a 3d perspective, but I can only make an attempt to line it up with the proper texture in our files to avoid having to redo all the skins

**Comment by Merker6** [comment]
Looked at this, appears the probe is just a scaling issue between segments. Will come back to it later
