### ISSUE TITLE
Wheel Brakes - assign 2 controls so can assign 2 axes to apply brakes.

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#218]
**Is your feature request related to a problem? Please describe.**
There is only one brake axis, and turning left while putting on the right brake is counter intuitive (along with the reverse if that's how you configured it).  You can only assign one axis to a control (unlike keypresses which can have multiple).

**Describe the solution you'd like**
Have a left and right brake option in the axis control config that either or both will apply the brakes.  Given there isn't a left and right brake modeled, this would be use either or both toe brakes and all the brakes come on.

**Describe alternatives you've considered**
Pressing W and ignoring the pedal brakes.

**Additional context**

**Comment by heclak** [comment]
Done as of beta 9
