### ISSUE TITLE
Compressor and turbine blades don't rotate in MP for other players in F2 view

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#219]
**Describe the bug**
Compressor and turbine blades don't rotate in MP for other players in F2 view.  Appear to rotate for the player in F2 view.

**To Reproduce**
go into MP server an have someone else look into the intakes and up the tailpipe in F2 external view.

**Expected behavior**
They should rotate for everyone
**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: DCS Stable 2.5.5.xxxxxx
 - A-4E Version:  1.4 beta 7

**Additional context**

**Comment by heclak** [comment]
I've attached this to the net code so I hope it works for now. But there seems to be a larger issue as this is also the case of AI aircraft. I'm'not sure what's wrong as we're already using the correct arg number so something else must be happening here.

**Comment by heclak** [comment]
should be fixed in the beta-10. Let me know if isn't.
