### ISSUE TITLE
Support for Supercarrier

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#225]
This thread will hopefully serve as a place to consolidate information about what currently works and what doesn't. Supercarrier is **NOT** in progress as we do not have access to the module to understand and work on it. There is no guarantee that getting access to it would allow for our ability to unofficially add support to it too. 

This post will hopefully serve as a gathering point for everything related to the A-4E and the Supercarrier module. And if a coder who owns the Supercarrier would like to work on it then the information here might be useful.

Feel free to add to this thread with any information that you might think would be relevant/useful.

**Comment by ninchistudios** [comment]
@heclak I'm happy to donate a copy of the supercarrier to the team if it will help.
