### ISSUE TITLE
A-4 moving on the aircraft carrier

### ISSUE THREAD

**Issue by denissoliveira** [heclak/community-a4e-c#226]
The A-4 is not stopped on the conveyor, it is moving alone to the south side, at all. I thought it was only in the São Paulo transpotadora, but no, it happens in any carrier, I don't know if this has already been reported.
Acho que não é necessário vídeo ou foto, simplesmente ele move para trás até cair da transportadora.

**Comment by malamem** [comment]
Denis, it's an issue that can not be solved by this time. To be straight as the coder has already talked about, from my point of view it's a good thing. Give us more flexibility to maneuver it on the deck.

Usa o freio ou pede calços para GROUND CREW. Isso não pode ser resolvido por agora e como escrevi acima, muitos de nós consideram uma coisa boa para poder manobrar no deck.
Se precisar de ajuda com o A-4 ou o A-12 pode me chamar. Estou como MALAMEM!

abx
