### ISSUE TITLE
"FLAP Switch UP/DOWN" quite inconsistent.

### ISSUE THREAD

**Issue by Dani3lNL** [heclak/community-a4e-c#227]
When clicking "FLAP Switch - UP/DOWN", it does often only switch between "stop" and "up" instead of also going to "down" position.

See trackfile:
[A-4 inconsistent Flaps UP-DOWN.zip](https://github.com/heclak/community-a4e-c/files/4774373/A-4.inconsistent.Flaps.UP-DOWN.zip)

DCS 2.5.6.50793 Open Beta
A-4E Version 1.4.0

**Comment by callmepartario** [comment]
Odd, there should be a "UP ELSE STOP" and "DOWN ELSE STOP" binding options for flaps that are often denoted as HOTAS binds. recommend searching for these functions to bind, and see if that solves your issue.

**Comment by ninchistudios** [comment]
I have noticed that if I move quickly from UP ELSE STOP through the middle position to DOWN ELSE STOP or vice versa it occasionally fails to recognise the second command. Doing it more slowly and deliberately works every time.
