### ISSUE TITLE
AN/ASN-41 navigation BDHI needle animations swapped in test mode

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#232]
**Describe the bug**
The Navigation Computer has its TEST behaviour simulated, but instead of BDHI pointer 2 (the thicker one) indicating 30 degrees, it is pointer 1 (the slim one) the one doing so.

**To Reproduce**
1. Place the Nav.Computer in TEST
2. Place BDHI switch to NAV CMPTR
3. Look at the BDHI needles.

**Expected behavior**
Pointer 2 should indicate 30 degrees +/- 1

**Screenshots**
![Image of BDHI during TEST](https://i.imgur.com/ZvI7kgi.jpg)

**Software Information (please complete the following information):**
 - DCS Version: DCS/2.5.6.50979 OB
 - A-4E Version 1.4

**Additional context**
The NAVAIR manual describes the TEST behaviour:

"Displayed on the face of the indicator are two pointers, pointer 1 (a single-bar pointer for UHF/ADF operation) and pointer 2 (a double-bar pointer for TACAN).

PRIOR TO FLIGHT

1. Turn the AN/ASN-41 function selector switch knob to TEST.

2. BDHI switch in NAV CMPTR position. 

WIND SPEED indicates 223.6 +/- 2.5 knots. 
WIND DIRECTION indicates 0914 +/- 1.5 degree. 
LATITUDE PRESENT POSITION shows South integration. 
LONGITUDE PRESENT POSITION shows East integration. 
BDHI No. 2 pointer indicates 30 +/- 1 degrees right. 
BDHI No. 1 pointer indication depends on present position and destination data set in."

**Comment by callmepartario** [comment]
is this still the case in the EFM?

**Comment by callmepartario** [comment]
this might be fixed. is this fixed?

**Comment by Cubeboyy** [comment]
Non-replicable from initial testing. Will test further.

**Comment by callmepartario** [comment]
this has been fixed in the develop branch!
