### ISSUE TITLE
add T-50 pod and CAP-9M to weapons

### ISSUE THREAD

**Issue by ataribaby42** [heclak/community-a4e-c#234]
Please if possible to add for next version loadout T-50 pod and CAP-9M missiles that works normally except actual launch? Both pod and CAP-9M are already in vanilla DCS and can be loaded on F-14, F-18, F-5.

My "hacked" loadout without proper launcher rail pylons:
["pylons"] = 
{
	[2] = 
	{
		["CLSID"] = "CATM-9M",
	}, -- end of [2]
	[3] = 
	{
		["CLSID"] = "{DFT-150gal}",
	}, -- end of [3]
	[4] = 
	{
		["CLSID"] = "{AIS_ASQ_T50}",
	}, -- end of [4]
}, -- end of ["pylons"]

If possible lets make CAP-9 behave like for example in F-5 module - You get tone like normal winder, just do not launch on pickle.

Pod should be able to load on all pylons (even centerline per photos), CAP-9 same as normal sidewinders.

Thanks

**Comment by callmepartario** [comment]
let's talk about this on discord sometime

**Comment by callmepartario** [comment]
see also: #334

**Comment by callmepartario** [comment]
we'll be pursuing our own ACMI pod solution, see #334 for further development.
