### ISSUE TITLE
VR view jump when taking off and landing (WOW dependent?)

### ISSUE THREAD

**Issue by moonmanh3** [heclak/community-a4e-c#235]
My setup: DCS 2.5.6 standalone, Oculus CV1 , GEeForce RTX 2070 GPU

When taking off, from land or from a ship, the aircraft  instantaneously shifts attitude (rotates slightly left). Happens on landing as well. I can see it happening on the external views.

This started as soon as I upgraded to the newest A4 last week.

**Comment by skuvosk** [comment]
Can confirm it's not only in VR.
From my experience the attitute flickering seems to happen just when the wheels lose or get contact with the ground.
Here are a takeoff and a landing clip showing the phenomenon:
[https://www.youtube.com/watch?v=jMvRNzdz_1Q](url)
[https://www.youtube.com/watch?v=AJ8FsrBUwiM](url)

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
