### ISSUE TITLE
add TACAN keybind

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#237]
**Is your feature request related to a problem? Please describe.**
I’d like to be able to control the Tacan from my Hotas. Also, having keybinds would allow the mission designer to setup the Tacan from within a trigger.

**Describe the solution you'd like**
I’d like to see keybinds for the following:

TACAN mode
TACAN channel CW/CCW major (Tens) and minor (units).

**Describe alternatives you've considered**
![95111F6B-158F-4827-85BF-CB5CA69D34B5](https://user-images.githubusercontent.com/51679833/85902569-54168a80-b7d2-11ea-8be1-c409afd54515.jpeg)

**Additional context**

**Comment by callmepartario** [comment]
see #314 - closing this duplicate issue for now.
