### ISSUE TITLE
add radar altimeter warning keybind

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#238]
**Describe the bug**
The keybinds to increase or decrease the Radar Altitude Warning don't autorepeat if the keys are held.

**To Reproduce**
Affected keys are:
Radar_Altitude_Warning-Lower = {RCTL -}
Radar_Altitude_Warning-Raise = {RCTL =}

**Expected behavior**
Keys should autorepeat if held.

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.50979 Open Beta
 - A-4E Version: v1.4

**Comment by callmepartario** [comment]
there will be a continuous keybind for these (and a toggle button for the radar altimeter) in the next beta.
