### ISSUE TITLE
cat hookup on open beta dedicated server

### ISSUE THREAD

**Issue by ninchistudios** [heclak/community-a4e-c#239]
**Describe the bug**
Catapult hookup only works on open beta dedicated server if the client immediately hits esc twice on connect, then selects role. If they select a role without first hitting esc twice, the catapult hookup will not work.

**To Reproduce**
1. host a mission with the A-4 on the Stennis, set up as per the community guide, on an open beta dedicated server
2. connect with a DCS client
3. immediately select the A-4 role
4. taxi into position on any catapult and hit the cat hookup keybind
5. note that the "you are hooked up" message displays, but the aircraft does not hook up and continues rolling backwards
6. disconnect from the server
7. reconnect to the server and immediately on connect, hit esc twice to display the menu
8. click "select role" and choose the A-4
9. taxi into position on any catapult and hit the cat hookup keybind
10. note that now the hookup functions as expected

**Expected behavior**
2 x esc should not be required for cat hookup to work normally

**Software Information (please complete the following information):**
 - DCS Version: DCS OB DS 2.5.6.50979
 - A-4E Version 1.4
 - Tacview 1.8.3.200
 - LotATC 4 (installed but disabled) 
 - Tested on PG map

**Comment by ninchistudios** [comment]
Note that it's perfectly possible this is a DS issue and not the A-4 specifically. Reporting as much for the workaround as for the bug.

**Comment by ninchistudios** [comment]
On further testing, this may not be specifically with DS but with a particular script-heavy mission using MOOSE, CTLD, CSAR and MIST. Will continue testing with a minimal mission.

**Comment by heclak** [comment]
Let me know if this is still happening or if I can close this.
