### ISSUE TITLE
Please make Wheel Chocks default on for Cold Start

### ISSUE THREAD

**Issue by jonshrives** [heclak/community-a4e-c#240]
Love this module!

But could you please make it so that Wheel Chocks are on as default for Cold Start / take off from ramp Client Spawns - this is what ED do for the F-18 and I think it would prevent sliding off carrier decks in MP. I know people can tap brakes (W key) or I could make missions hot start and give a bit of thrust, but I fly mainly multiplayer and pilots logging in with different lag etc - not always possible to tap brakes in time before splashy splashy boom.

Default "Chocks On" for cold start "take off from ramp" would be amazing! Please please please!

Would be a huge quality of life update!

Thanks

**Comment by heclak** [comment]
I'll need to check if ED changed anything about ground crew. When I implemented the wheels chocks, I didn't have the ability to control the ground crew state which would affect how a player would remove the wheel chocks.

eg. if I did it the only way that I could and have the wheel chocks on at spawn, the player would need to request the ground crew to put it on again but they can ask to remove it. This is why the wheel chock aren't on by default.

**Comment by 08jne01** [comment]
v2.0.0-beta-1 fixes the sliding issue and therefore this issue.

**Comment by jonshrives** [comment]
Thanks and keep up the great work! Love this module! Wish it was officially in DCS then we could use it in our GR campaigns more.
Thanks for the reply :)
    On Friday, 12 February 2021, 04:01:35 CET, Joshua Nelson <notifications@github.com> wrote:  
 
 


v2.0.0-beta-1 fixes the sliding issue and therefore this issue.
