### ISSUE TITLE
Communication menu only has options for contacting ground crew.

### ISSUE THREAD

**Issue by Brutus748** [heclak/community-a4e-c#243]
While in game the only options available for communications are to contact the ground crew and all sub actions within. I have bound the comms button to other keys and have tried enabling/disabling easy communications. I have also uninstalled and reinstalled the complete files.

**To Reproduce**
1. Enter any game mode with the A-4E
2. Attempt to use communications menu
3. Only available option : Ground crew

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6]
 - A-4E Version [e.g. v1.4.0]

**Comment by callmepartario** [comment]
Radio functions are locked behind the SDK. This is a non-issue.

**Comment by Brutus748** [comment]
Sorry but I have no idea what that means or what SDK is. Is there a way for me to use the comms menu as I have seen videos of others using it?

Sent from Mail for Windows 10

**Comment by twanmal** [comment]
no.
