### ISSUE TITLE
"Ability to set "Start From Ground" and "Start From Ground Hot" on the Mission Editor

### ISSUE THREAD

**Issue by Baco1170** [heclak/community-a4e-c#244]
I would like to ask for teh A-4E-C to be able to be placed on the ME as "Start From Ground"

A-4 Skyhawk
![Screen_200822_161217](https://user-images.githubusercontent.com/70073631/90963924-840ca200-e492-11ea-92dd-0fb6b242a56e.png)

AV-8II Harrier
![Screen_200822_161658](https://user-images.githubusercontent.com/70073631/90963965-ed8cb080-e492-11ea-94e1-eb635d5f8251.png)

I read that the problem might be that the AI would take off vertically or land vertically, or something. When I asked ED to give every aricraft this properties, they said it woudl screw up the Taxi logic of the planes...

So I dont know if its even possible Or maybe create a clone of teh A4 that can take off form ground and you know its onlly for clients and the AI will not be able to function...

This would eneable us to create bases wherer tehre are none and be able to use them for Spawn points.
Razbam South Atlantic map will only feature 1 Argentinian BASE, and there are three more that were very active historicaly. I would like to crate this bases with Sustangs MAT mod, but I cant make teh A-4 Spawn from a Farp  like runway.
This woudl be usefull for uninprovved Marine bases in Vietnam for instance.. and opens up many posibilities for mission making...

**Comment by heclak** [comment]
Trying to understand what the request is here. Are you asking to designate the A-4E as a VTOL aircraft so that they will be no spawn restrictions like how the Harrier works? If so then I don't think it would be a good idea for us to do that as it might mess up a number of other things.

**Comment by Baco1170** [comment]
Yeap That was preciselly it Heclak. 
But yeah I understand that it messes up AI taxying and other stuff. 
So I found an alternative way. I hack my ME install instead.

Thanks anyway.

**Comment by heclak** [comment]
ok. I'll close this then.
