### ISSUE TITLE
 flight computer not working

### ISSUE THREAD

**Issue by ECV-Daaron** [heclak/community-a4e-c#248]
**Describe the bug**
When placing a ship from the mission editor and giving it the command "attack a point" the flight computer of the A4 stops working.

**To Reproduce**
1. He placed a ship in the editor and in advanced orders I order him to shoot a point or a unit.
2. I fly the mission, enter the cockpit, energize the plane and the flight computer does not show the flight coordinates, nor the current position-

**Expected behavior**
he should be able to command a ship to attack without interfering with the plane's flight computer.

**Screenshots**
![Screen_200911_115641](https://user-images.githubusercontent.com/67554053/92941177-6a71d100-f426-11ea-9237-ca9603562597.png)
Order to fire a point to ship.
![Screen_200911_115757](https://user-images.githubusercontent.com/67554053/92941290-91300780-f426-11ea-9bc2-ac403e5f9fb5.png)
Flight computer off.

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6.54046 Open Beta]
 - A-4E Version [1.4.1]

**Comment by Andrew8604** [comment]
I think I noticed many things not working with A-4E-C v1.4.0 and DCS v 54046, or the version prior to it.  The flight computer (ASN-41 Nav Computer) displayed all zeros and although the input knobs would turn and make sound, they did not change any digits, nor did the computer seem functional.  The Doppler system was similarly dead.  And the TACAN was not functioning on any channel.  A couple other things may not of worked, I can't recall.  This was all from Nellis AFB in the Nevada map, so no carrier involved.

After upgrading A-4E-C to v. 1.4.2, these things worked again.  However, I still don't seem to be able to change the inputs on the  ASN-41.  It seems to be reading current position okay, and coords of waypt 1 and waypt 0 for target 1 and target 2, respectively.  I cannot input wind and Mag Var., but when the doppler unit is reading the ground, some wind info is displayed...not sure if it's the correct info.  TACAN seems to work ok.  With DCS v 55960, the behavior seems the same; however, I was not able to test v1.4.0 or 1.4.1 with DCS v 55960.  Another thing, I do not seem to see messages about the status of the Doppler unit, such as warming up and when ready.

Oh, how SWEET it would be to have in-flight refueling.  I know you can't get it to work without, apparently, being a full mod...I still think how sweet it would be if it worked, though. :)  ...and if the "buddy tanker" pod worked for both player and AI.  And if radios worked, even though DCS AI radio calls need lots of work.

**Comment by callmepartario** [comment]
error here is likely to be user error and confusion about how the slew knobs work; i am closing this issue.
