### ISSUE TITLE
adjust mirror reflection surface area

### ISSUE THREAD

**Issue by rmacan** [heclak/community-a4e-c#249]
**Describe the bug**
Both mirrors in A-4E cockpit show the wrong area behind the plane. The mirrors show the screen under an angle 45 degrees up.

**To Reproduce**
1. Look in mirrors in the cockpit

**Expected [behavior**]
The mirrors must show the area directly behind the tail. 

**Screenshots**
![area behind tail](https://user-images.githubusercontent.com/65828217/93723582-01195d00-fba0-11ea-9c2a-27091c2f26a6.png)
![mirrors](https://user-images.githubusercontent.com/65828217/93723584-07a7d480-fba0-11ea-9ab9-3ecae17f99a1.png)

**Software Information (please complete the following information):**
 - DCS Version: latest 2.5.6.54046
 - A-4E Version v1.4.1. beta 3

**Additional context**
-

**Comment by callmepartario** [comment]
heclak has addressed this issue for the next beta.
