### ISSUE TITLE
AFCS / TRIM does not work

### ISSUE THREAD

**Issue by M4tUt3** [heclak/community-a4e-c#250]
The AFCS does not work the trim either, I tried everything, I saw all the turotials and manuals, but I still cannot make it work.
I suspect it is from the FF of my logitech G940 but I'm not sure.
reinstalled everything but did it again

 - DCS Version: [e.g. DCS 2.5.6.54046 Open Beta]
 - A-4E Version [e.g. v1.4.1]

**Comment by heclak** [comment]
yea. there is a problem with the AFCS when using a FFB stick. This will take quite a long time to fix and it is needing a full rewrite of the AFCS and trim system to be compatible. So don't expect this to happen anytime soon. I hope to fix this too as I have a FFB stick too.
