### ISSUE TITLE
Integrity Check Fails on last DCS update 2.5.6.55363 Open Beta

### ISSUE THREAD

**Issue by AthosARG** [heclak/community-a4e-c#251]
**Describe the bug**
Exits when entering A-4E Slot on Multiplayer Dedicated Server
models/an-m66.edm @ c:/users/USER/saved games/dcs/mods/aircraft/a-4e-c/shapes

**To Reproduce**
connecct to server as usual
mission loads and choose coalition
enter A-4E slot.
Fails and Exit whit model is tainted msg  

Int-Check remains Red not able to connect anymore to server

**Software Information (please complete the following information):**
Dedicated Server and Client running
 2.5.6.55363 Open Beta
Both server and client runs 
 - A-4E Version v1.4.1

TXS.-

**Comment by heclak** [comment]
Been working on this. Patch is with the testers to confirm.

**Comment by callmepartario** [comment]
fixed in 1.4.2 release!
