### ISSUE TITLE
allow gunsight depression adjustment by mouse scroll wheel

### ISSUE THREAD

**Issue by dlwalter** [heclak/community-a4e-c#253]
**Is your feature request related to a problem? Please describe.**
Currently reticle depression requires a click and drag with the mouse. This doesn't work in VR using "head-look" to control the cursor. 

**Describe the solution you'd like**
Most continuous knobs in game support a mouse wheel scroll to adjust position.  I'd recommend the same for the gunsight reticle. 

**Describe alternatives you've considered**
Another option is supporting both the scroll wheel and click+drag

**Comment by clutchtomcat** [comment]
I could have sworn this worked in previous versions. With click and drag it's impossible to set precise mils.

**Comment by callmepartario** [comment]
an improved set of gunsight bindings should make it very easy to get the settings you need in the next beta.
