### ISSUE TITLE
There should be a way to fold wings.

### ISSUE THREAD

**Issue by Brojustuserandomgenerationusername** [heclak/community-a4e-c#254]
I noticed there's no button that i noticed in the cockpit or bind in the controls to fold the wings, and you cant order the ground crew to do so if the plane had manual operated wing folding. Considering that it was a navy plane i think it would be cool to have the option to fold the wings when starting a mission or to end it.

**Comment by heclak** [comment]
Ermm.. The A-4 doesn't have folding wings in real life. It was already designed to be small enough to not need the wings to be folded.

**Comment by Brojustuserandomgenerationusername** [comment]
You are correct. I saw the pics of the custom made blue angels A4s with folding wings and i thought they were standar.
