### ISSUE TITLE
low aircraft visibility

### ISSUE THREAD

**Issue by Martinisk** [heclak/community-a4e-c#256]
**Describe the bug**
Comparing to other DCS modules I cannot see flying aircraft (hot aspect) as soon as in other planes

**To reproduce**
Steps to reproduce the behavior
1) Fly hot in a4e against mig 21 from 30 miles
2) Fly hot in F5 against mig 21 from 30 miles

**Expected behavior**
Visibility range should be same. Now If I fly F5 I can see that mig from aprox. 25nm but in a4e its hard to see till 7-10nm (same conditions, wheather, time...)

**Software information**
DCS open beta 2.5.6.55960
Latest version a4e downloaded 10.10.2020

**Comment by 08jne01** [comment]
Can you provide a comparison screenshot please?
