### ISSUE TITLE
canopy frame unwrap error

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#257]
top, canopy unwrap appears to be incorrect and is mirroring the left side rather than using the entire unwrapped space:

![unknown](https://user-images.githubusercontent.com/17432407/96340703-e20acf80-1066-11eb-84fc-de0534396d00.png)

![unknown2](https://user-images.githubusercontent.com/17432407/96340759-e636ed00-1066-11eb-87cf-d0c17de40fa8.png)

**Comment by Merker6** [comment]
Issue effects both interior and exterior of canopy model.

Resolved for exterior, will require more effort for interior

**Comment by Merker6** [comment]
Resolving, interior would be identical anyway
