### ISSUE TITLE
add HMAS Melbourne support

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#259]
I am developing the HMAS Melbourne (R21) for DCS, and the deck height is 12m above datum (sea level?)

Apparently the A-4 considers this outside the the acceptable range to detect that it is on a carrier as a Human trying to launch results in the "You are not on a carrier" message in game.  The AI launches when Malamem adjusted the code the same as he did for the Sao Paulo and Clemenceau to get them working, but the Melbourne is even lower than those.

Maybe in carriers.lua, change

function on_carrier()
	if  tostring(Sensor_Data_Mod.nose_wow) == "1" and Sensor_Data_Mod.self_alt > 16 and Sensor_Data_Mod.self_alt < 23 and
		Terrain.GetSurfaceType(Sensor_Data_Mod.self_m_x,Sensor_Data_Mod.self_m_z) == "sea" then
		return true
	else
		return false
	end
end

to 

function on_carrier()
	if  tostring(Sensor_Data_Mod.nose_wow) == "1" and Sensor_Data_Mod.self_alt > 11 and Sensor_Data_Mod.self_alt < 23 and 
		Terrain.GetSurfaceType(Sensor_Data_Mod.self_m_x,Sensor_Data_Mod.self_m_z) == "sea" then	
		return true
	else
		return false
	end
end

Not sure if that is all that is involved, but it's a start.

Regards

Braedon

**Comment by callmepartario** [comment]
can we get a revisit on this issue with the EFM? does the a-4 function with the melbourne now? closing this issue in the meantime since the old carrier system should not need to be used.
