### ISSUE TITLE
Included "Community A-4E-C Readme.pdf" file in download not a valid pdf file

### ISSUE THREAD

**Issue by Stix-09** [heclak/community-a4e-c#260]
**Describe the bug**
Included Community A-4E-C Readme.pdf file in download is corrupted and can't open in ver 1.4.2

**To Reproduce**
If you attempt to open "Community A-4E-C Readme.pdf"  it fails.
If you open file in a text editor it shows following content.
![Untitled](https://user-images.githubusercontent.com/60739090/97123150-29900a80-178f-11eb-9138-4c68fd088027.jpg)

```
<HTML>
<HEAD>
<TITLE>Temporary Redirect</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Temporary Redirect</H1>
The document has moved <A HREF="https://doc-08-cc-docstext.googleusercontent.com/export/ia52bcj3b99qnjcka3ud80m79c/33io66kjlf6svqj54pjh0smnlk/1601997520000/105664648954659284305/*/1Yew1IKZ7HDFZYTtJ2D7unLosBFeCrtcJmlVU0iOzBtQ?format=pdf">here</A>.
</BODY>
</HTML>
```

**Expected behavior**
Previous version 1.4 does not have this problem

**Software Information:**
 - DCS Version: not relevant
 - A-4E Version 1.4.2

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-2
