### ISSUE TITLE
external lighting

### ISSUE THREAD

**Issue by pistolwil** [heclak/community-a4e-c#261]
**Describe the bug**when I click any external light switch the lights on the outside of craft do not come on. uninstalled
[bad lights.txt](https://github.com/heclak/community-a4e-c/files/5443539/bad.lights.txt)
 and deleted everything. reboot and clean install still same issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by pistolwil** [comment]
latest version of dcs and skyhawk on stable dcs as of oct 27th 1:21 am mst.

**Comment by callmepartario** [comment]
you failed to enable the master exterior lighting switch located on the outside of the throttle handle.
