### ISSUE TITLE
MK4 HIPEG gun pod behavior

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#263]
**Describe the bug**
The NAVAIR Procedure for firing the Mk 4 Gun Pod is:

1 Set Gunsight Depression. Set per tables.
2a Weapons Function Selector. Set to OFF
2b Station Select Switches. All OFF
3 Gun Pod Station Select switches. As required.
4 Gun Pod Charge switch. Set to CHARGE
5 MASTER Arm switch. Set to ON
6 Fire by pressing the trigger.

However, on the simulated A-4E the gunpods will not fire if at least one of the Weapons Panel STATION SELECT switches (step 2) is not ON. It has to be a station mounting one of the Gun Pods, no need to have all of them ON, any will do as long as it has a GunPod on it.

Do not confuse with the Station Select switches on the GUN POD Panel on the Left Console, those have to be ON as per setp 3. 

**To Reproduce**
1. Arm the Skyhawk with at least one Mk4 Gun Pod
2. Follow the NAVAIR procedure.
3. The gun Pods will not fire.
4. Set the Gun Pod station switch (on the center panel) to ON. Now the Gun Pod will fire.

**Expected behavior**
The Gun Pods should fire even if the Weapon Station switches are OFF, as per the Procedure.

**Screenshots**
- Navair Procedure.

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.6.55960 Open Beta
 - A-4E Version: 1.4.2

![Guns Procedures](https://user-images.githubusercontent.com/51679833/98109269-0d215b80-1e7c-11eb-9fc9-6ac2e34f02ac.jpg)

**Comment by callmepartario** [comment]
in accordance with #503 , this issue should be addresed next. identical sound assets can be used to hear/feel charge and safes through pylons, as similar nitrogen charges are used in the operation thereof. in addition to unique L/C/R placement, a lowpass filter for those sdefs should be used to deaden the sound for being further away from pilot position, and felt more by induction (cutoff ~120 hz).

**Comment by callmepartario** [comment]
having tested this today in 2.0.0, i'm finding the gunpods do not require any station selector positioning to fire, only for them to be readied by station and charged on the gunpod panel, and, of course the master armament switch engaged. anyone else who would like to reproduce this in 2.0.0 is welcome to.

an unsimulated behavior would be to disable a mounted gun once it has been safed, which i will add. i might add some light sound feedback for this.

**Comment by callmepartario** [comment]
As of https://github.com/heclak/community-a4e-c/commit/36e9f54c154203c1a1ad38a7b94b8c34dad7ba56 gunpod procedure is programmed as follows in accordance with this ![video](https://www.youtube.com/watch?v=_6c4k2RsVpc) - barring some additional SME help from a ground crew who can enlighten us on the complete wiring diagram for the gun pod, the following is my best guess as to the behavior of the gun pods.

CHARGE
- The aircraft has power.
- A gun pod is present on the station.
- The corresponding Gunpod Station Switch is in the READY position.
- The Gunpod Switch is in the CHARGE position.
- _The gun pods are charged and ready to fire._

FIRE
- The aircraft has power.
- The Master Armament Switch is in the ON position.
- The Gun-Rocket trigger can be used to fire the gun pods. 
- _Station Selector Switch positions have no effect on gun pod behavior of any kind._

SAFE
- The Gunpod Station Switches can be used to safe and re-ready the gun pods. 
- The Gunpod Switch can also be set to the OFF position to prevent firing of gun pods en masse.

CLEAR
- The aircraft has power.
- The Gunpod Switch is in the CLEAR position.
- All equipped gun pods are cleared.
- _Once cleared, a gun pod cannot fire again until the ground crew completes a rearm procedure on the plane._

**Comment by callmepartario** [comment]
behavior finalised in https://github.com/heclak/community-a4e-c/commit/eb696de7a032977c12fc0c585e6ef7718672579b

**Comment by callmepartario** [comment]
as of https://github.com/heclak/community-a4e-c/commit/d2d625200801168aae52d40b5b1f9aaf054bb1ed the Gunpod Panel's switches will be returned to their safe and default positions during re-arming. this should prevent any gunpods from accidentally charging or clearing at the end of a hot re-arm.
