### ISSUE TITLE
Multiplayer failing to report aircraft position

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#264]
**Describe the bug**
Aircraft position is not being recorded by the server and sent to other connected clients. Despite this, the aircraft appears able to fly normally while connected to the server.

**To Reproduce**
1. Launch or join a multiplayer session with at least two A4-E-C pilots.
2. Start the aircraft, taxi and takeoff.
3. Other players will not see the plane move from its starting position or on the map, although other animations might reproduce.

**Expected behavior**
Aircraft movement should be recorded by the server and replicated across connected clients.

**Software Information**
 - DCS 2.5.6.57264 Open Beta
 - A-4E v1.4.2

**Additional testing, bug replication, or solution-seeking are appreciated**
- Enemy units in single player missions track aircraft location appropriately. The aircraft is fired upon and is dealt damage by gunnery and SAMs.
- Are in-air starts working to get client rep in multiplayer?
- Are enemy AI units firing on the aircraft in multiplayer?
- The EFM test alpha no. 1 build does not seem to have these issues. Only SFM clients are experiencing client rep issues, so I suspect this is either SFM deprecation or is somehow LUA-related.

**Comment by Baco1170** [comment]
Yesterday in a MP Sesion I was hosting. Clients didn´t sea the movement of each other.
Planes did not received any fire, so apparently AI can not see them.

Now, The clients DID cause damage to Environment AI. dropping bombs. and everybody (clients) could see the damage and explosions, only coming from nowhere...

![image](https://user-images.githubusercontent.com/70073631/98317984-5aa4e200-1fbc-11eb-91a2-8f3b17d2c2eb.png)

that is my plane HOST as seen by clients. 3 respawns.

**Comment by callmepartario** [comment]
This bug appears to be confirmed by other users affecting other SFM and AI aircraft: https://forums.eagle.ru/forum/english/digital-combat-simulator/dcs-world-2-5/bugs-and-problems-ai/multiplayer-issues-ab/7127344-major-desync-issue-in-new-open-beta

Hopefully this means ED will consider issuing a fix of some kind in the coming weeks.

**Comment by callmepartario** [comment]
There is a new open beta today which purports to fix the issue in the Su-25T. Let's get online and see if the fix is in for this aircraft as well, please!

**Comment by Baco1170** [comment]
Looks like its Fixed.. Just flew a mission in the Vietnam Server and saw another Scooter flying around

**Comment by callmepartario** [comment]
agreed, looks like this issue has been fixed. 
thanks, ED!
