### ISSUE TITLE
static objects immune to weaponry

### ISSUE THREAD

**Issue by FlanchiFL** [heclak/community-a4e-c#265]
First of all BIG THANKS for the module and support, you're doing a GREAT WORK, I enjoy a lot flying this bird!

**Describe the bug**
Since last open beta update (DCS 2.5.6.57264 Open Beta) It's impossible to destroy static objects. I can attack vehicles, infantery, ... but not deposits, houses, etc...added in a mission). No effective to use bombs (only if a direct hit), rockets neither guns). 

**To Reproduce**

1. Install DCS 2.5.6.57264 Open Beta
2. Edit a mission adding static objects
3. Run an attack on those targets

**Expected behavior**
Targets as houses, deposits, tanks, bridges should be able to be destroyed ( I can do that with any other aircraft, even with A4  before last Open beta update)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6.57264 Open Beta]
 - A-4E v1.4.2

**Additional context**
I've tested this on single player

**Comment by 08jne01** [comment]
I mean the bombs are not handled by us are you using ED's weapons IE the MK80 series?

**Comment by callmepartario** [comment]
without more information, this seems to be user error or a universal DCS issue for the patch.
