### ISSUE TITLE
inverted flight does not deprive engine of fuel

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#266]
**Describe the bug**
The real Skyhawk is limited to no more than 10 seconds of inverted or negative G flight, as the fuel system needs positive G to feed the engine continuously.

**To Reproduce**
1. Just fly inverted, the aircraft will do it just fine for much longer than the maximum allowed time.

**Expected behavior**
After 10 seconds, the fuel should cease to feed into the engine and the engine should light off.

**Screenshots**
See screenshots below

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.57530 Open Beta
 - A-4E Version: 1.4.2

**Additional context**

![Inverted](https://user-images.githubusercontent.com/51679833/99259188-654f4a80-27f8-11eb-865e-006550ce5a74.jpg)

**Comment by Brojustuserandomgenerationusername** [comment]
Hey, sorry to be skeptic but what's the source on 10 second limit?

**Comment by rudel-chw** [comment]
> Hey, sorry to be skeptic but what's the source on 10 second limit?

Natops flight manual, section 1, part 4, operating limitations.
![AC499F7A-6CEC-4881-A4C6-C3BC69919A44](https://user-images.githubusercontent.com/51679833/102689376-4c153180-41dc-11eb-9b67-3c597e6de28f.jpeg)

**Comment by zelosos** [comment]
There is probably a safety margin. So its most likely the starving time is more like 12 - 15 seconds.

**Comment by 08jne01** [comment]
Added in v2.0.0-beta-3.
