### ISSUE TITLE
mission editor failures support

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#267]
**Describe the bug**
Most of the Failures listed have no effect on the aircraft. The only one that seems to work is L-ENGINE

**To Reproduce**
1. Set a Trigger for an A-4, with the action SET FAILURE, like shown on the illustration.
2. Fly the aircraft, the failure will activate within one minute. It will show up on the debriefing (see illustration)

**Expected behavior**
The failed system should stop working and illuminate warning lights if appropiate. For example, currently the HYDRO failure does not lit the warning light, and also doesn't seem to affect the hydraulically-operated devices.

**Screenshots**
See below:

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.6.57530 Open Beta
 - A-4E Version: 1.4.2

**Additional context**
![Test Failure](https://user-images.githubusercontent.com/51679833/99260409-17d3dd00-27fa-11eb-9901-14ffaba41716.jpg)
![Failures](https://user-images.githubusercontent.com/51679833/99260428-1d312780-27fa-11eb-9c47-fc76f251f682.jpg)
![Failure Debrief](https://user-images.githubusercontent.com/51679833/99260436-20c4ae80-27fa-11eb-8ba9-a66bb5633b2c.jpg)

**Comment by 08jne01** [comment]
This is a huge task, likely not going to be complete for years.

**Comment by callmepartario** [comment]
some preliminary damage modeling has been added in version 2.2, so closing this. if we can expand meaningful damage modeling further through that framework, we will.
