### ISSUE TITLE
Re-starting the Engine in flight.

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#268]
**Describe the bug**
The procedure of the real A-4E for an in-air restart,  does not work on the Sim. The Sim requires the use of the Engine Start button.

**To Reproduce**
a. Start on a free-flight mission, with the A-4 at an altitude of at least 20,000 feet and 300 KIAS of speed.
b. Cut off the fuel supply.
c. Wait for the engine to die, the electric power will go out.
d. Enable the fuel supply.
e. Attempt an air start following the procedure of the real aircraft:

AIRSTART Procedure

1. Throttle - OFF
2. Emergency generator - EXTEND
3. Fuel control switch - PRIMARY/MANUAL
4. If practicable, descend to 30, 000 feet or below, at best glide speed.
5. Establish 250 KIAS glide.
6. Throttle - IGN THEN IDLE
7. Monitor RPM and EGT.

The engine will not start.

**Expected behavior**
The engine should re-start. Currently, it needs a click on the Engine Start button before step 6.

**Screenshots**

![fig01](https://user-images.githubusercontent.com/51679833/99390000-af970100-28b6-11eb-95da-3dcc71d35719.jpg)

![fig02](https://user-images.githubusercontent.com/51679833/99390004-b0c82e00-28b6-11eb-933d-b6ecae600ee5.jpg)

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.6.57530 Open Beta
 - A-4E Version: 1.4.2

**Additional context**
Not a critical issue by any means, but I intended to do a training mission for this emergency and would like to be able to follow the real procedure, rather than have to modify it.

**Comment by 08jne01** [comment]
Fixed in EFM.
