### ISSUE TITLE
A-4E-C not authorized

### ISSUE THREAD

**Issue by Smiler21** [heclak/community-a4e-c#269]
I installed it as instructed. However when I load DCS I get "The following DLCs are not authorized and will be disabled:
A-4E-C ".  what could be the reason? the version of DCS I am running is  non-steam  2.5.6

**Comment by callmepartario** [comment]
there is a high probability you have installed the module incorrectly. revisit the installation instructions at https://heclak.github.io/community-a4e-c/#installation

**Comment by JohnDeereJay** [comment]
Having the same issue but i've looked a hundred times and my files are installed correctly
I have installed previous mods and they have worked. Pls Help

**Comment by callmepartario** [comment]
without more information, this is not going to get any attention. i recommend joining the discord if you need live troubleshooting. 

if you're getting an authorization error, there is a high probability you have installed the module incorrectly (or did to and forgot to remove your incorrect installation before you made a correct one, and the two are in conflict). revisit the installation instructions at https://heclak.github.io/community-a4e-c/#installation
