### ISSUE TITLE
A-4Ec Not showing on the ME if you select Argentina as country. (recently added to DCS)

### ISSUE THREAD

**Issue by Baco1170** [heclak/community-a4e-c#272]
If you select teh country Argentina in the Mission Editor, you dont see the A-4E-C in the planes menu options... 

**To Reproduce**
1. open  Mission editor
2. Add a Plane group
3. Select Argentina as country.
4. No A-4E-c on the list...

 - DCS Version:  DCS 2.5.6.59398 Open Beta
 - A-4E Version 1.4.2

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1.
