### ISSUE TITLE
add ARC-51 manual frequency keybind

### ISSUE THREAD

**Issue by dcsstinger** [heclak/community-a4e-c#273]
**Is your feature request related to a problem? Please describe.**
We use the A4 in my squadron to train the cadets. They think it is uncomfortable to use  the mouse when they need to use different channels for internal communications, ATC etc.

**Describe the solution you'd like**
Include two key commands Keys.arc51_freq_preset_up and Keys.arc51_freq_preset_down to turn the preset know right/left allowing the pilot to select a different channel

**Additional context**
I have already implemented that in my local installation

**Comment by callmepartario** [comment]
some groundwork has been laid for increase/decrease for the three frequency knobs.

**Comment by callmepartario** [comment]
these items will be available as keybinds in the next beta/RC
