### ISSUE TITLE
Cant Rearm on airfield and carrier

### ISSUE THREAD

**Issue by Arkios366** [heclak/community-a4e-c#276]
**Describe the bug**
I cant rearm on airfield and carrier, the ground teams says ok, but do nothing...
But If I pre-install the loadout in mission editor, no problem.

**To Reproduce**
1. Go into the module
2. try to rearm

**Expected behavior**
it should rearm properly

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.60720 (OpenBeta)
 - A-4E Version: 1.4.2

**Comment by callmepartario** [comment]
ensure your canopy is open, and the engine is off. (this is an SFM restriction)
