### ISSUE TITLE
Flaps hydraulic noise sometimes sticks near the end of transit

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#280]
**To Reproduce**
When changing the flaps position, the sound appears to occasionally 'stick' (continuously playing, although no hydraulic motion is occuring) - it happens most often near the lower extreme position. Could use some help on reproduction to figure out what might be causing it.

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6 Open Beta]
 - A-4E Version [e.g. v2.0.0-beta-1 (develop)]

**Comment by 08jne01** [comment]
This is the hydraulics trying to operate when the blowback valve is open.

**Comment by callmepartario** [comment]
cool. the sound restart sounds like a struggle, so if it's working correctly, we can just close this one!
