### ISSUE TITLE
AI unable to launch from carriers

### ISSUE THREAD

**Issue by jhgunter** [heclak/community-a4e-c#282]
**Describe the bug**
A-4s with non-human pilots (either on their own or as wingmen to a player) are incapable of launching correctly from carriers (either Supercarrier or Stennis) unless set to "Takeoff from runway".

**To Reproduce**
1. Open the mission editor, and create a new mission. (FWIW, I used the Persian Gulf map.)
2. Place a carrier (either Supercarrier or Stennis) in the water, and give it a single waypoint.
3. Place an A-4 on the carrier, and set it to "Takeoff from ramp" or "Takeoff from parking hot".
4. Save and run the mission. If using a Supercarrier, the A-4 will get stuck after the holdback bar is attached, with the deck crew waiting for it to taxi forward into the shuttle. If using the Stennis, the catapult will shoot correctly, but the A-4 will get stuck immediately before its rear wheels leave the deck.

**Expected behavior**
The AI plane should attach to the catapult, and the catapult should be able to fully launch the plane.

**Screenshots**

[This is where it gets stuck on a Supercarrier.](https://user-images.githubusercontent.com/6609297/107134907-2e9f4280-68c4-11eb-8c42-2b11043764bf.png)

[This is where it gets stuck on the Stennis.](https://user-images.githubusercontent.com/6609297/107134943-8342bd80-68c4-11eb-87e6-46a16b61cd3d.png)

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.60966 Open Beta
 - A-4E Version v2.0.0-beta-1

**Additional context**
I disabled all other mods for the test described above. Most of my testing was with the 2.0.0 beta, but I also observed the same behavior after reverting to the latest 1.4 release. A-4s piloted by humans seem to be able to launch just fine. AI A-4s set to "Takeoff from runway" are able to launch correctly from both types of carrier.

Thanks for all that y'all have done to bring this plane to DCS! I'd be happy to conduct any further tests or provide any additional info that would be helpful.

**Comment by 08jne01** [comment]
Looks related to the issue #245

**Comment by CrashMcGee** [comment]
Also occurs on DCS stable, so it's not a specific issue to open beta

**Comment by callmepartario** [comment]
according to discord user @mmarques#2678 , adding the following to **a-4e-c.lua** might address this error:

```
mechanimations = {
        FoldableWings = {
           {Transition = {"Retract", "Extend"}, Sequence = {{C = {{"Arg", 8, "to", 0.0, "in", 10.0},{"Arg", 555, "to", 0.0, "in", 6.0},}}}, Flags = {"Reversible"}},
           {Transition = {"Extend", "Retract"}, Sequence = {{C = {{"Arg", 8, "to", 1.0, "in", 15.0},{"Arg", 555, "to", 1.0, "in", 6.0}}}}, Flags = {"Reversible", "StepsBackwards"}},
        },
    },
```

**Comment by jhgunter** [comment]
Thanks @callmepartario! That seems to fix the issue for the Stennis, but the issue remains for the Supercarriers.

**Comment by callmepartario** [comment]
user mission files that can reliably reproduce this issue for testing and debugging would be most helpful

**Comment by mmarques** [comment]
Hi, I don't know if this is sensitive information, but I'm not the discord
user mmarquesjr, I'm the github user mmarquesjr, I suggest you start
another thread without mention me.

Thanks,

**Comment by callmepartario** [comment]
my apologies, i did not realize i would create a github mention doing what i was doing!

**Comment by mmarques** [comment]
I also think traceability its very cool but github didn't make it work this
time eh? Good luck with what you are doing.

**Comment by jhgunter** [comment]
[Here's a mission](https://www.dropbox.com/s/hkw22ne606yrp7c/a4_carrier_test.miz?dl=0) that constitutes a minimal example needed to reproduce the behavior. Just two A-4s on two carriers (one Stennis, one Supercarrier). If it behaves as it does for me, then both A-4s should get stuck (or, with the Lua fix applied, the Stennis one should take off successfully while the Supercarrier one still gets stuck). Let me know if you want a track as well.

**Comment by callmepartario** [comment]
for anyone actively using the dev branch, this issue should be resolved. please test!

**Comment by heclak** [comment]
I've yet to push the code for this fix. More clean up to be done first. It will also need a new dll so I'll update you folks when it's ready.
