### ISSUE TITLE
Aircraft and cockpit blinks 

### ISSUE THREAD

**Issue by patton610** [heclak/community-a4e-c#284]
I can't describe it as anything else. I rolled off the runway and into the grass after I missed a taxiway and it started blinking in and out. . For brief second the aircraft seemed to turn black and then it would blink out and back in.like a stop motion animation almost. It didn't do it till I ran off the runway. I've had no issue along these lines with other aircraft, but cannot say for certain it is not a universal issue since the last open beta patch. I have only flown this aircraft since the last client uodate.

**Comment by 08jne01** [comment]
Was your engine off and the emergency generator deployed? There is a known issue which will cause the power to turn off and on.

**Comment by patton610** [comment]
Not to unless it had stalled out and I didn't realize it. The emergency generator was not on. I had started to apply throttle to get back to thr runway and that's when it started I believe. But, I'm reconstructing this in my head. This was not a power issue I had power and throttle response. It just reminded me texture stretching bugs but here I was briefly seeing what was behind  the aircraft  (or below it if in cockpit view)

**Comment by patton610** [comment]
I was able to replicate it. Seems to not be purely graphical because when this glitch occurs the cursor changes when it is over left hovering over a control. In my case I left it over the radar mode switch. The aircraft actually looks like its jumping between to spots with no user input. The cursor changed from a yellow reference one to a green interaction one when thr glitch occurred. Its like the aircraft doesn't know where its supposed to be and is trying to choose between two surfaces. The effect is a sort of matrix like fluctuating that doesn't seem to end.

**Comment by patton610** [comment]
It does seem to end when back on a paved surface. Might be connected with the odd rolling bit when on a carrier.

**Comment by 08jne01** [comment]
Closing this because there is no clear procedure to replicate. If you think this is still an issue please open another issue.

**Comment by patton610** [comment]
Ok. As succinctly as possible.  Get the aircraft. Taxi off runway. There isn't magical involved.
