### ISSUE TITLE
Radar antenna tilt angle resetting

### ISSUE THREAD

**Issue by 4535jacks** [heclak/community-a4e-c#286]
**Describe the bug**
When the radar tilt angle is changed, it is reset to zero when the radar mode is set to TC or back to Stby

**To Reproduce**
1. Adjust radar tilt to any value other than zero
2. Move radar selector to TC and radar tilt will reset to zero
3. While on TC change radar tilt to any value other than zero
4. Switch mode back to Stby and it the radar tilt switch will flick back to zero.

**Expected behavior**
The radar tilit switch should remain in the same position regardless of the selected mode.

**Screenshoe errorts**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta] 2.5.60966
 - A-4E Version 2.0

**Additional context**

**Comment by 08jne01** [comment]
![image](https://user-images.githubusercontent.com/1359572/107724829-add5b180-6cdc-11eb-9a8b-cdb4a9f9940e.png)
