### ISSUE TITLE
Decrease sensitivity of trim hat

### ISSUE THREAD

**Issue by 4535jacks** [heclak/community-a4e-c#288]
**Is your feature request related to a problem? Please describe.**
I find the trim too sensitive and difficult to trim or a straight and level attitude

**Describe the solution you'd like**
Make the trim less sensitive so each press of the trim hat results in a smaller trim change

**Describe alternatives you've considered**
None

**Additional context**

**Comment by callmepartario** [comment]
a trim strength slider is on the to-do for the next beta.

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-2.
