### ISSUE TITLE
Pitot Heat/Engine Icing Simulation

### ISSUE THREAD

**Issue by xanstin** [heclak/community-a4e-c#289]
A nice simulation addition but if not possible perhaps just flippable switches to simulate the simulation

**Comment by 08jne01** [comment]
There is no humidity in DCS, therefore it's not possible to simulate this with any accuracy, when this changes I'll be open for implementing it.

**Comment by xanstin** [comment]
Hmm I know several planes if you don’t turn on the pitot heater the indicated speed stops working properly maybe some type of timed response. A-10 F 86 are two that come to mind can’t remember if the F 18 did this

**Comment by 08jne01** [comment]
Yea but there is no humidity, it just happens at a certain outside air temperature, that's not realistic. You don't get icing if it's not humid enough. I'd rather not model it than model something silly and unrealistic.

**Comment by xanstin** [comment]
Ok makes sense, I know it happens in other planes never really dug deeper. I’ll pretend to flip the switches till then. :)
