### ISSUE TITLE
radar altimiter difficult to adjust

### ISSUE THREAD

**Issue by 08jne01** [heclak/community-a4e-c#290]
**Describe the bug**
Radar altimeter is horrible to set altitude.

**To Reproduce**
Use scroll or click and drag on the radar altimeter.

**Expected behaviour**
Needle moves with a speed proportional to my mouse speed.

**Actual behaviour**
Needle moves faster when I scroll slower.

**Software Information (please complete the following information):**
- v2.0.0-beta-1 (but also versions below)

**Additional context**
I suspect the drag is so fast it's actually going past the limit of the animation. Needs investigating.

**Comment by 4535jacks** [comment]
Confirmed.  I too find it difficult to change.

**Comment by callmepartario** [comment]
the radar altimeter will be much easier to enable, disable and set the indexer (including by keybinds instead of the mouse) next release.
