### ISSUE TITLE
allow radio on ground power

### ISSUE THREAD

**Issue by ataribaby42** [heclak/community-a4e-c#291]
UHF Radio doesn't work just on ground power. Engine needs to be actually started to be able to get reply for example on "Request Startup"

Radio should work just on ground power connected.

**Comment by 08jne01** [comment]
This is likely not going to get fixed as the impact is potentially large as we need to either connect the ground power using more exported functions which is asking for more crashes and degrades or we add a fake battery to the A-4 and have to check the impact of this on the existing electrical system. The gain is being able to hail ATC for startup which is pointless anyway. Sorry.

**Comment by callmepartario** [comment]
would doing this allow a pilot to communicate with ground crew without the canopy being open? might be worth considering from a QOL perspective. what do we think?

**Comment by callmepartario** [comment]
no progress, but let's make a call on this before 2.0.

**Comment by 08jne01** [comment]
> no progress, but let's make a call on this before 2.0.

not sure but this is fixed
