### ISSUE TITLE
incorrect engine ignitor timing

### ISSUE THREAD

**Issue by malamem** [heclak/community-a4e-c#295]
The ignitor sound plays from the moment we move the Lever to IGN for just 2-3 seconds.

The most close to the real engine start should be:

Ignitor sound starts to play from the moment u move the Lever to IGN and remains playing until the FUEL FLOW increases and the engine light up.

**To Reproduce**
1. Start the engine trough the normal procedure.

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
A-4E Beta 2 

**Additional context**

**Comment by callmepartario** [comment]
given discussions on this recently, have we decided the sound is playing appropriately (just a tad too loud?). please weigh in, OP.

**Comment by callmepartario** [comment]
note to self: if the throttle lever is in the ignition position and the rpm is between 1-21%, it should be sparking

**Comment by callmepartario** [comment]
fixed in beta-3
