### ISSUE TITLE
add continuous input controls for keyboard users

### ISSUE THREAD

**Issue by LeonXD123** [heclak/community-a4e-c#296]
I want to talk about a problem that I told you about, which is flight ability for keyboard players.
Due to the fact that many like me do not have a control stick or hotas, we cannot simulate what would be the flight, but flying like this is not bad, and that is why I am talking about that in this case the control stick when doing yaw the stick returns to your site which is not ideal for a comfortable and easy flight for those of us who do not have tools to simulate.
sincerely LeonXD
![ezgif com-gif-maker](https://user-images.githubusercontent.com/78982480/107818206-06956080-6d56-11eb-9d7e-96754eef0018.gif)

**Comment by 08jne01** [comment]
This should be fixed in v2.0.0-beta-2 please test them out and give feedback. Thanks.

**Comment by 08jne01** [comment]
So you want the aileron to reset?

**Comment by callmepartario** [comment]
it seems decided among keyboard users that the roll should reset to center; the pitch can hold (although should there be a reset-to-center keybind in this scenario?)

**Comment by 08jne01** [comment]
This is fixed in v2.0.0-beta-3
