### ISSUE TITLE
cockpit flickers in multiplayer on carrier deck

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#297]
**Describe the bug**
Whilst on a carrier deck in multiplayer, the cockpit occasionally momentarily flickers black (almost as if lacking out for less than 1 frame?) 

**To Reproduce**
- not happening in single player, however, only multiplayer (as a client)
- occurs on both stennis and supercarrier decks
- does not seem to trigger when hosting my own multiplayer server (non-dedicated)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6.60966 Open Beta]
 - A-4E Version [e.g. v2.0.0 beta 2]

**Comment by 08jne01** [comment]
Did you manage to reproduce this again?

**Comment by callmepartario** [comment]
still having trouble reproducing this one, but i've been slacking on carrier ops in favor of other things. anyone else?

**Comment by 08jne01** [comment]
Since we couldn't reproduce this I'll just close it.
