### ISSUE TITLE
new nose wheel steering system 

### ISSUE THREAD

**Issue by patton610** [heclak/community-a4e-c#298]
on the old flight model the nose wheel steering was toggled on with a key press and controlled with the rudders. Now rather than a toggle, the nose wheel steering requires a button to be held down. this complicates flight deck navigation because the activation of the brakes often leads to the release of the nose wheel steering button. An option to treat the nose nose wheel steering as a toggle rather than constant press button would help. The experience as is, is somewhat like playing twister. 
    Additionally It does not seem to act like actual nose wheel steering. It acts like a office chair wheel  in that it just reacts to momentum applied to it rather than asserting directional control on its own. It has not been unusual to find the nose   perpendicular to the long axis of the aircraft.   This may be the result of the  individual wheel brakes.

**Comment by patton610** [comment]
yeah, I remapped it and tested again. The nose wheel button may allow it to swivel, but so far as I can tell it is not taking directional inputs from the rudder axis like 1.4 was.

**Comment by 08jne01** [comment]
The nosewheel steering is correct as is please see the natops.
