### ISSUE TITLE
Tiller bar (nose wheel steering) 

### ISSUE THREAD

**Issue by patton610** [heclak/community-a4e-c#299]
Tiller bar/ nose wheel steering system 
The nose wheel system of the current version is subpar compared to the one in the previous flight model. This is a result of the interaction between reality and the limitation of pc hardware. 
As is, the aircraft is correct... to a point? It has nose wheel steering but acts like it doesn't. By this I mean Its more of a nose wheel lock release. The nose wheel steering does not function. What us actually modeled is an earlier a4 without nose wheel steering. The nose wheel just swivels. 

The differential braking is functional to get from one side of a carrier to another, but is not precise or reactive enough to interact with the supercarrier deck crew instructions.

The great number of people have joysticks, less have Hotas throttles, fewer have rudder peddles. In practice attempting to brake and hold down a nose wheel steering key is problematic because it requires digit aerobics.

Options as I see them :

1. A script that automates the alignment of the aircraft with the shuttle as if guided by a tiller bar (historical). This could be accompanied by an animation or not.
2. A functional nose wheel steering system similar to the version 1.4 model. Not historical but perhaps easier to implement. 
3. Assign differential braking to the rudder axis with a mod key thst also functions as the nose wheel steering key. This would roughly approximate the previous version without actually creating a new system.

**Comment by 08jne01** [comment]
![image](https://user-images.githubusercontent.com/1359572/107850628-b53fac80-6dfb-11eb-9a6a-394d65b55e47.png)

This is how the nosewheel steering is implemented. If you wish to turn tight make sure you are not depressing the nosewheel steering button so that the nosewheel can freely castor and then apply brake in the direction of turn.

> It has nose wheel steering but acts like it doesn't. By this I mean Its more of a nose wheel lock release. The nose wheel steering does not function. What us actually modeled is an earlier a4 without nose wheel steering. The nose wheel just swivels.

This is just incorrect. If you find any evidence that the current system is modelled incorrectly then please do open another ticket but in the meantime, this is not a bug.

**Comment by patton610** [comment]
i apparently had mismapped the key and that was what was leading me to believe it was not active. The  nose wheel steering was introduced on the F  and was not on the E. Where mentioned alongside other models , nose wheel steering is mentioned as being specific to F forward.   
![image](https://user-images.githubusercontent.com/78847493/107853144-f45d0600-6dd9-11eb-838b-8a3cde1d8024.png)

**Comment by callmepartario** [comment]
without someone to lead the aircraft around by hand on a deck, we decided nosewheel steering would be a good addition to the simulation.

**Comment by 08jne01** [comment]
Also I believe some E models were retrofitted with NWS. As it specifically specifically mentioned aircraft upgraded with AFC 429.
![image](https://user-images.githubusercontent.com/1359572/107855487-6e14e400-6e1a-11eb-8c2f-f16df70675c0.png)
