### ISSUE TITLE
can't take control of aircraft (enter cockpit) (add to README and installation instructions)

### ISSUE THREAD

**Issue by StormILM** [heclak/community-a4e-c#300]
Myself and a couple of other people I have talked to are having an issue where we can't start the flight from the cockpit (player control), the flight start shows Creech AFB in a general walk around camera mode but does not settle into the A-4 cockpit. I have done everything I can think of to assure the model and all the old A-4 elements were removed prior to the installation but still can't get it to work. The original A-4 works fine when re-installed. Any ideas?

**Comment by callmepartario** [comment]
The module is installed correctly, but I am unable to take control of the aircraft.
Ensure you have installed Visual Studio 2015, 2017 and 2019 Redistributable libraries. Windows users running DCS world are typically running x64, so you will want to download and install vc_redist.x64.exe (~15 MB) from the following page, install the library, and then restart their computer:

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by StormILM** [comment]
Thank you! That fixed the problem. I have passed this to the others who were having the same issue.
    On Saturday, February 13, 2021, 07:26:02 PM EST, Joshua Nelson <notifications@github.com> wrote:  
 
 


Closed #300.

**Comment by callmepartario** [comment]
re-opening this issue so this information can be added to installation instruction troubleshooting and readme.
