### ISSUE TITLE
smokewinder pod ON/OFF not functioning

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#302]
**Describe the bug**
No combination of weapon armament and depressing the smoke ON/OFF trigger (default: T) triggers the smokewinder pods. Addressing this should be a part of reassigning weapon selector switch labels.

**To Reproduce**
1.4.2 implemented behavior:
1. Equip Smokewinder pods
2. Press T to toggle ON/OFF

Suggested EFM behavior (if possible):
1. Equip Smokewinder pods
2. Master Arm ON
3. Weapon function selector to BOMBS & GM ARM
4. Weapon Release (hold)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.6.60966 Open Beta]
 - A-4E Version [e.g. v2.0.0-beta-2]

**Comment by 08jne01** [comment]
The implementation I chose is:
1. Master Arm On
2. Select Pylons
3. Trigger or weapon release to toggle.

I thought about putting the function selector to something but if people want to have fun with intervals of smoke and stuff it would get annoying. The gun pods are hooked up similarly so it's not too much of a stretch.

**Comment by 08jne01** [comment]
Fixed in commit 405d1f350ab9c41e8dc528aa48f7bdfc6ec5d2ca
