### ISSUE TITLE
nosewheel animation does not align with aircraft movement

### ISSUE THREAD

**Issue by SpaceEnthusiast** [heclak/community-a4e-c#304]
**Description**
When you enable nose wheel steering and turn a bit, the movement looks a bit odd when you look at the nose wheel animation, as if the wheel is slipping.

**To Reproduce**
1. Spawn on a flat surface
2. Press the nose wheel steering button
3. Throttle up a bit
4. Take a look at the nose wheel and how it's drifting

**Expected behavior**
The movement of the aircraft should correlate with the animation of the nose wheel.

**Video**
[Here's a video of it happening](https://imgur.com/a/CYKP1OA)

**Software Information**
 - DCS Version: DCS 2.5.6.60966 Open Beta
 - A-4E Version: v2.0.0-beta-2

**Comment by 08jne01** [comment]
This has been fixed in commit 5667f6eb93cba5da0e1e4ce41a2cf567908ca132.

Thanks for the report.
