### ISSUE TITLE
make the A-4E-C available for Chile

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#305]
I know that Chile never used the Skyhawk on real life, but in order to allow "what-if" scenarios, please add Chile to the list :)

**Describe the solution you'd like**
On the A-4E-C.lua file, there is this table within:

-- enable A-4 for all countries.  It is CHEAP and easy to maintain
	Countries = {"Abkhazia","Argentina","Australia","Austria","Belarus","Belgium","Brazil","Bulgaria","Canada","China","Croatia",
                 "Czech Republic","Denmark","Egypt","Finland","France","Georgia","Germany","Greece","Hungary",
                 "India","Insurgents","Iran","Iraq","Israel","Italy","Japan","Kazakhstan","The Netherlands","North Korea",
                 "Norway","Pakistan","Poland","Romania","Russia","Saudi Arabia","Serbia","Slovakia","South Korea",
                 "South Ossetia","Spain","Sweden","Switzerland","Syria","Turkey","UK","Ukraine","USA","USAF Aggressors"},

Please add "Chile" to it. Thanks a lot.

**Comment by callmepartario** [comment]
we are using the three-letter country codes -- i will look this up, but am assuming it's CHL for chile?

**Comment by rudel-chw** [comment]
Hello, on the LUA file you are not using the three-letter codes ... but anyway, here is the complete list of Country codes:
[Countries.pdf](https://github.com/heclak/community-a4e-c/files/6144669/Countries.pdf)

**Comment by callmepartario** [comment]
this is addressed in the upcoming beta-3!

**Comment by rudel-chw** [comment]
Thanks a lot :)
