### ISSUE TITLE
AFCS: setting HDG SEL off does not interrupt heading turn

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#306]
**Describe the bug**
When using the AFCS in PRE-SELECTED HEADING Mode, the heading select switch may be placed in the OFF position at any time. If placed in the OFF position prior to the completion of a turn, the aircraft should roll smoothly to a level attitude and maintain the compass heading indicated at that time. This worked fine on v1.4 but on the latest OpenBeta 2.0 the turn is not stopped even if the HDG SEL switch is turned OFF.

**To Reproduce**
1. Fly the aircraft level and ensure that the AFCS has been on STDBY at least 90 sec.
2. Select a Heading different than the current one, using the Heading Select Knob.
3. Enable the HDG SEL switch, the aircraft will begin to turn towards the selected heading.
4. Before completing the turn, turn OFF the HDG SEL switch ... the aircraft will keep turning.

**Expected behavior**
If placed in the OFF position prior to the completion of a turn, the aircraft should roll smoothly to a level attitude and maintain the compass heading indicated at that time.

**Software Information (please complete the following information):**
 - DCS Version: DCS/2.5.6.60966
 - A-4E Version 2.0.0-Beta-1

**Additional context**
Detected the problem while updating my AP & Navigation Training Mission.

**Comment by rudel-chw** [comment]
Hi. Upgraded to A-4E Version 2.0.0-Beta-2 and it shows the same issue.

**Comment by 08jne01** [comment]
Thanks for spotting this I forgot to implement this behaviour when I redid the AFCS. This will be fixed in the next update.

**Comment by rudel-chw** [comment]
Glad to help :)

**Comment by 08jne01** [comment]
Fixed in commit c12678823ff44f597c8a71393bb02889cf85a0c0.
