### ISSUE TITLE
key binding for the AFCS override

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#307]
**Is your feature request related to a problem? Please describe.**
On v1.4 all the Flightstick buttons had a default Binding. On the current v2, the AFCS Override button has no default.

**Describe the solution you'd like**
Assign as a default the same binding as on v1.4:  Left Control + A

**Describe alternatives you've considered**
I can easily bind my own on my DCS, but I'm editing a Training Mission for the AP that will be used by all new users. IIt would be much easier to have a default than having to teach new users how to bind this themselves.

**Additional context**
Current default bindings of the Flight Stick:

![Screen_210221_193157](https://user-images.githubusercontent.com/51679833/108641094-2f1b0a00-747c-11eb-8dcd-656171da4351.jpg)

**Comment by callmepartario** [comment]
this default binding will be restored in the next beta.
