### ISSUE TITLE
Can't get to cockpit view nor control the aircraft

### ISSUE THREAD

**Issue by julpeuzin** [heclak/community-a4e-c#308]
Hello dear community,

I'm having troubles with the new 2.0 beta 2 release, when I start a flight I can't get the cockpit view and control of the aircraft. The flight starts with the map view (like F10) and I can't get in the cockpit or control the aircraft, it's like I'm a spectator, the plane flies by itself. I thought it was because I was running DCS stable, so I switched to the open beta version of DCS 2.5.6, followed the instructions as stated by deleting my old 1.4 version and bindings, but nothing changed. Same for 2.0 beta 1. When I put back the 1.4 it works just fine. I tried to rename the Saved Games/DCS folder to get a fresh one at launch, then re unzip the module, but it didn't work. Couldn't find anyone reporting that kind of situation with the Skyhawk, but I found a similar situation with the Black Shark, seemed to be a licence issue but I guess that's not the case here ?.. Any help would be great, can't wait to test the new EFM.

Thanks in advance

Julien

**Comment by callmepartario** [comment]
see https://github.com/heclak/community-a4e-c/issues/300
