### ISSUE TITLE
Dedicated Server Crash when you try to join into A-4E slot

### ISSUE THREAD

**Issue by ucnanoman** [heclak/community-a4e-c#309]
Dedicated Server Crash when you try to join into A-4E slot.
I'm using 2.0.0 beta version, I really like everything you've done.
I get a 'flight is delayed' and then it crashes the entire dcs dedicated server =( .
Maybe i should just stick with the stable version of the mod?

**Comment by 08jne01** [comment]
This is a weird dedicated server bug. 

There is a workaround which is to load in once to a land slot before trying any carrier slot.

I think it may also be resolved if the A-4 is put on the actual dedicated server.

**Comment by ucnanoman** [comment]
YOU WERE RIGHT, as soon as I put the folder in the dedicated server dcs/saved games/mods/aircraft ... no more problems THANKS!
