### ISSUE TITLE
Animation Request - JBD on Carrier

### ISSUE THREAD

**Issue by DISCOVMA131** [heclak/community-a4e-c#31]
Evaluate if possible to manually request or automagically call JBD deployment on the Boat (maybe based on positioning?) of client operated A-4E-C like AI driven A-4

**Comment by DISCOVMA131** [comment]
This will probably involve the Boat code and not necessarily anything for the Scooter itself - I will dig into the Boat a little and see if I can figure anything out

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
