### ISSUE TITLE
mission starts in ''map''

### ISSUE THREAD

**Issue by HBr69** [heclak/community-a4e-c#311]
I installed A-4E-c and it shows up as an installed module on the DCS-startpage and in the module manager. But when I enter a mission, or instant action it starts in map-view and I can not exit this. When I go to mission editor, hawk is not listed with ''player'' option.

I am new to DCS, so maybe this is not a bug, and I a doing something wrong, if so please excuse me.

A-4E-C version 2.0.0-beta 1
DCS: 2.5.6.

kind regards,
Hans

**Comment by 08jne01** [comment]
Please see the installation instructions, if the issue persists then contact us on discord and we can help, this is not a bug however.
