### ISSUE TITLE
add empty external fuel tanks as loadout option

### ISSUE THREAD

**Issue by APen-FPT** [heclak/community-a4e-c#313]
Because it is common to take off with empty fuel tanks and refuel them in the air. 

[Empty external tanks.zip](https://github.com/heclak/community-a4e-c/files/6054725/Empty.external.tanks.zip)

**Comment by 08jne01** [comment]
Hi thanks for the code to go with this. If you have any changes in future you can make a pull request and we can merge the code in directly.

**Comment by callmepartario** [comment]
empty fuel tanks are slated for the next beta / RC
