### ISSUE TITLE
add keybind for TACAN Mode and ARC-51 mode knobs 

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#314]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but there are several keybindings that would allow improvements to the Training Missions, in order to have more control of the A-4 Cockpit from within a Trigger.

**Describe the solution you'd like**
I'd like to have keyboard bindings for the following:
- Oxygen Switch.
- APR27 - ON/OFF switch.
- ARC-51 UHF Mode Knob. Could be one keybinding for each position or a CW-CCW binding.
- TACAN Mode Knob. Could be one keybinding for each position or a CW-CCW binding.
-  Radar Altitude ON/OFF. Currently we can only set the Altitude Alarm.

**Describe alternatives you've considered**
There are no alternatives available.

**Additional context**
None.

**Comment by callmepartario** [comment]
just noting here that APR27 - ON/OFF, Oxygen Switch and Radar Altitude ON/OFF are already bound up for the next beta.

TACAN Mode and ARC-51 mode knobs will take a little more doing. I will change this issue title accordingly.

**Comment by callmepartario** [comment]
note: ARC-51 UHF mode knob keybinds are added and will appear in the next beta.

**Comment by callmepartario** [comment]
TACAN mode switch keybind will also appear in the next beta.
