### ISSUE TITLE
change default keybind for gun (spacebar)

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#317]
**Describe the bug**
The Backspace and the Spacebar are hard-wired keys that are used on the X:START WAIT USER RESPONSE trigger. The Backspace is not currently used by the A-4E ... but the Spacebar is binded by default to the Gun trigger. This makes it impossible to edit any Training Mission where the Gun trigger is used, as it confuses the trigger logic.

**To Reproduce**

**Expected behavior**
Assign a different key binding to the Gun trigger, for example the keys Left Control + Spacebar.

**Screenshots**
Screenshot of the default binding.

**Software Information (please complete the following information):**
 - DCS Version: DCS/2.5.6.61527
 - A-4E Version: 2.0.0-Beta-2

**Additional context**
![Spacebar keybind](https://user-images.githubusercontent.com/51679833/110495759-95866600-80d3-11eb-813f-a68ae4660ba4.jpg)

**Comment by callmepartario** [comment]
since the hornet and f-14 and countless other modules use the spacebar as the gun trigger, i think the best thing to do for these types of mission is to use the backspace key instead of spacebar for the trigger logic.
