### ISSUE TITLE
Add the instructions concerning Visual Studio from Discord to the Readme

### ISSUE THREAD

**Issue by Rizn-Nuke** [heclak/community-a4e-c#318]
Reminder, as [requested](https://www.reddit.com/r/hoggit/comments/m51jaf/a4_mod_installed_but_wont_load_in/):

The module is installed correctly, but I am unable to take control of the aircraft. 

Ensure you have installed Microsoft's Visual Studio 2015, 2017 and 2019 Redistributable libraries. Windows users running DCS world are typically running x64, so you will want to download and install vc_redist.x64.exe (~15 MB) from the following page, install the library, and then restart your computer: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by callmepartario** [comment]
this will be done by release time. the installation notes provided are concurrent to official releases only.

**Comment by Rizn-Nuke** [comment]
As stated in the link provided, I added this ticket at the request of JNelson.

**Comment by callmepartario** [comment]
cool; i will re-open the original issue with those instructions for tracking, then.

**Comment by callmepartario** [comment]
see issue #300
