### ISSUE TITLE
After deleting the old A4 mods  and bindings in the config folder in the saved game folder of  dcs i tried different ways to install. icon on startsite is shown, exterior 

### ISSUE THREAD

**Issue by Glider59** [heclak/community-a4e-c#321]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by 08jne01** [comment]
I'm sorry what exactly is wrong? Can you fill out the bug proforma please?

**Comment by Glider59** [comment]
DCS Version 2.5.6.61527
A4 Skyhawk 2.....
Before installation all concerning folders of the older A4 were deletet mods and bindings
After downloading and unzipping in DCS/USER/SAVEDGAMES the icon showed up on DCS Sartpicture
clicking cold start 
xternal pictures so standing in parking lot or flying are all seeable BUT
I could not get into the cockpit to fly

any idea?

Best regard gerd "glider henseler

**Comment by 08jne01** [comment]
Hi please post in installation-help in the discord: https://discord.gg/K3BhJBfQwZ.
