### ISSUE TITLE
The controls indicator is not showing

### ISSUE THREAD

**Issue by FraggerNut** [heclak/community-a4e-c#323]
**Describe the bug**

The controls indicator which shows the stick, rudder and throttle position is not turning on

**To Reproduce**

1. Go to settings -> controls
2. Find the action "Show controls indicator"
3. Confirm that the default keybind (RCtrl+Enter) is assigned
4. Press RCtrl+Enter while in the A-4E 
5. The indicator will not be turning on like it should be

**Expected behavior**

A controls indicator showing stick, rudder and throttle position will appear on the bottom right corner of the screen like it does on other aircraft.

**Software Information**

 - DCS Version: 2.5.6.61527
 - A-4E Version 2.0.0 Beta 2

**Comment by 08jne01** [comment]
An indicator has not been programmed for the controls.

**Comment by FraggerNut** [comment]
Oh okay, thanks for the quick reply, hope it gets added soon!
