### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Flinzas** [heclak/community-a4e-c#324]
So when i install the mod do everything that the notepad README says and i open up dcs and it says authorization is valid for 2d 23h 59m the following DLCs are not authorized and will be disabled: A-4E-c... pls pls pls help

**Comment by callmepartario** [comment]
you have installed the module directly to the game files. revisit the installation instructions and ensure you are installing to the saved games directory as directed here:
https://github.com/heclak/community-a4e-c/#installation

**Comment by Flinzas** [comment]
![image](https://user-images.githubusercontent.com/81762999/113322824-d877da00-931d-11eb-84ec-1ff4274e7aeb.png)
well i am 
and heres the file idk the prob :/ ive done everything right

**Comment by callmepartario** [comment]
give us a screenshot of the contents of this folder, please.

**Comment by Flinzas** [comment]
![image](https://user-images.githubusercontent.com/81762999/113324013-483a9480-931f-11eb-8b55-040c0258f442.png)

there

**Comment by callmepartario** [comment]
did you at any time make an incorrect installation? check your DCS World installation files, and ensure there's nothing mirroring these files down there. As far as I'm aware, the error you are experiencing only happens if there are main game file conflicts.

**Comment by Flinzas** [comment]
![image](https://user-images.githubusercontent.com/81762999/113324694-1a098480-9320-11eb-99fd-8a306881f49a.png)
it does so should i uninstall it?

**Comment by callmepartario** [comment]
yes, that's what is causing your errors. remove that entire A-4E-C folder, and you should be in business; a proper installation must account for both doing what you should have done and **not** doing what you shouldn't have done!

**Comment by Flinzas** [comment]
YES! it works thank you so much
