### ISSUE TITLE
Can't pilot the a4e-c V2 beta 2

### ISSUE THREAD

**Issue by yeti57450** [heclak/community-a4e-c#325]
Hello,

I downloaded the a4e-c and installed it in the DCS open beta game. I have followed the installation process which appears in the read me carefully. when I launch the game, I can clearly see the icon on the game opening page. When I launch a mission I cannot access the F1 view which corresponds to the player view in the cockpit. Help from you can be. I want to clarify that I am under window 10.

**Comment by twanmal** [comment]
Where did you install the module exactly ? Can you provide the path ?

**Comment by yeti57450** [comment]
C:\Users\BIGEL\Saved Games\DCS.openbeta\

**Comment by yeti57450** [comment]
But I think that it's a beta version and I'm not a beta testeur!

**Comment by yeti57450** [comment]
ok I'm my answer

Assurez-vous d'avoir installé les bibliothèques redistribuables Visual Studio 2015, 2017 et 2019 de Microsoft. Les utilisateurs Windows exécutant DCS World exécutent généralement x64, vous souhaiterez donc télécharger et installer vc_redist.x64.exe (~ 15 Mo) à partir de la page suivante, installer la bibliothèque, puis redémarrer votre ordinateur:

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by callmepartario** [comment]
see #300
