### ISSUE TITLE
add anti-ship option for mission type

### ISSUE THREAD

**Issue by mmarques-88** [heclak/community-a4e-c#326]
**Is your feature request related to a problem? Please describe.**
The A-4 being a primarily carrier based aircraft should be able to perform the anti-ship strike mission.

**Describe the solution you'd like**
Being able to assign the Anti-Ship mission type to A-4 squadrons.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by callmepartario** [comment]
added in next beta (runway strike, too)!
