### ISSUE TITLE
ARC-51 radio T/R+G setting does not monitor 243.00MHz guard channel

### ISSUE THREAD

**Issue by anaander** [heclak/community-a4e-c#328]
**Describe the bug**
The A-4E-C's ARC-51 UHF radio has a T/R+G setting, however the +G is non functional. Further in my brief testing the radio is incapable of receiving any game audio on the appropriate radio channels.

**To Reproduce**
1. Create or edit an A-4E-C mission with a trigger on mission start, specifically Action: Radio Transmission, with a sound file on repeat. Attach it to a trigger zone, set the modulation to AM, frequency to 243 and power to 10000.
2. Load into the mission
3. Request ground power
4. Turn on ARC-51 radio and select T/R+G

**Expected behavior**
In modules where the T/R+G functions properly (F/A-18C, UH-1H, etc) selecting it will monitor the military guard frequency (243AM) for the UHF radio or the civilian guard for the VHF radio (121.5). You should hear the sound file you assigned to your radio transmission on 243MHz in the mission editor.

Additionally since I can't receive any transmission broadcasts at all, I suspect the manual radio tuning function isn't working.

- DCS Version: 2.5.6.61527.3
- A-4E Version v2.0.0-beta-3

**Comment by 08jne01** [comment]
There is likely nothing we can do about this because the radio does tune to the correct frequency otherwise. I will have a look but it's not very high priority.

**Comment by 08jne01** [comment]
Tuning the radio to 243 MHz with a mission broadcasting on that frequency works for me. As for TR+G and TR they operate the same as to listen on two channels two radios would have to be created. This is not something I particularly want to do since it is already a hack, this might decrease the stability further.
