### ISSUE TITLE
IN RANGE lamp flickers when TEST is pressed

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#329]
**Describe the bug**
Overriding conditions for turning the IN RANGE ladder lamp need to be revisited.

**To Reproduce**
With main electral bus powered, press the grey TEST button above the central weapons panel.

**Expected behavior**
Pressing the TEST button should enable a steady on state for the IN RANGE ladder lamp.

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7 Open Beta]
 - A-4E Version [v2.0 beta 3]

**Comment by 08jne01** [comment]
Yea this is on my list. I've reworked the other lamps that I've changed the behaviour of, I can come back and visit this now.
