### ISSUE TITLE
Leading-edge slats currently are not activating properly under G load

### ISSUE THREAD

**Issue by JazAero** [heclak/community-a4e-c#33]
Leading edge slats on the A4 are gravity controlled.  They retract automatically above a certain airspeed, but they also deploy automatically as the aircraft maneuvers under G load to increase wing efficiency, which currently, the aircraft does not do.  Possibly a big coding problem.  I'm not sure how you would solve with an SFM.

**Comment by heclak** [comment]
Will look into this but this would require more data on the factors influencing the slats operation. Currently, slats are only influenced by speed.

**Comment by 08jne01** [comment]
Fixed in v2.0.0-beta-1
