### ISSUE TITLE
Slats behavior

### ISSUE THREAD

**Issue by arturojgt** [heclak/community-a4e-c#330]
Dear.
My CFI is a former Pucara pilot here in Argentina, the other day I sent a question about the slats behavior in the A4 to his active A4 CFI in the Argentinian airforce and he sent this audio file.
Kind regards. 
Arthur from Argentina.

[WhatsApp Audio 2021-04-15 at 17.02.58.zip](https://github.com/heclak/community-a4e-c/files/6321040/WhatsApp.Audio.2021-04-15.at.17.02.58.zip)

**Comment by callmepartario** [comment]
can i get a consult on the contents of this file? it's not a valid zip file or audio file format i recognize.

**Comment by 08jne01** [comment]
You could transcribe what they said. I could not play the file either.

**Comment by arturojgt** [comment]
Hi, no problem. It's an .ogg audio file from WhatsApp in. rar file changed to zip extension.
He said the slat doesn't emit any sound in flight when it is open or close, no stop sound, no rail movement sound, and some times the slats are partially deployed, the relationship between AoA and the position is welll know for you.

Kind regards.
Arthur.

**Comment by 08jne01** [comment]
> and some times the slats are partially deployed, the relationship between AoA and the position is welll know for you.

The position can be half way provided the AOA is correct. 

Regarding the sounds our A-4M pilot said they could hear a metallic noise.
