### ISSUE TITLE
throttle position ocassionally stuck in OFF position after rearm

### ISSUE THREAD

**Issue by jzimmer111** [heclak/community-a4e-c#332]
sometimes after I rearm the plane on the ground or on the Stennis the throttle gets stuck in the off position. It doesn't respond to the step up keybind at all and will make the clicking sound but not move or begin spooling up the engine with mouse right click.

**Comment by 08jne01** [comment]
What version of the A-4 are you using?

**Comment by flat235** [comment]
I'm not the original reporter, but I just ran into this in version 2.0.0-beta-3

**Comment by jzimmer111** [comment]
Ive ran into it on 2.0.0-beta-1 but only once or twice and Ive run into it very frequently on 2.0.0-beta-3 but only since 2.7 came out

**Comment by callmepartario** [comment]
so far unable to reproduce this, myself - anyone else?

**Comment by callmepartario** [comment]
closing a long inactive issue. if you are experiencing this, you probably need to clean and reset all your keybindings to solve the issue.
