### ISSUE TITLE
Feature: Huffer sound when deployed.

### ISSUE THREAD

**Issue by LevelPulse** [heclak/community-a4e-c#34]
Feature Request: Play a sound queue for when the huffer is activated on the ground.

**Comment by callmepartario** [comment]
Recommended DCS assets located in "\DCS\Sounds\Effects\Aircrafts\Engines" to explore hooking up:

CONNECT/START
APU_AI9V_Start.wav

OPERATION DURATION  (requires crossfade in from the startup noise)
APU_AI9V_tone.wav
APU_AI9V_noise.wav

DISCONNECT (probably okay to quick crossfade the others out)
APU_AI9V_Shutdown.wav

**Comment by callmepartario** [comment]
these sounds have been implemented, thanks heclak!
