### ISSUE TITLE
UHF Frequency Mode switch Key and button map on the Input menu.

### ISSUE THREAD

**Issue by Baco1170** [heclak/community-a4e-c#343]
The A-4 has only one radio. so in order to coordinate with different squads you need to use the Guard channel. Now in the A-4 in order to transmit on the Guard Channel you need to turn the frequency selector switch on the VHF radio to Guard.
To do this right now you have to do it via Mouse click on the cockpit. If you are in combat or flaying really low, to do this you need to look down and it can result in a hazardous encounter with the earth or water.

Would it be posible to map it to a key and or hotas button please, so we can alternate from Channel to manual to guard without having to look at the console?

Thanks in advance!

**Comment by callmepartario** [comment]
these hotkeys have been added and will appear in the next beta!
