### ISSUE TITLE
radio, TACAN, ILS issues and limitations

### ISSUE THREAD

**Issue by MatAWG** [heclak/community-a4e-c#350]
TACAN and ILS is not working in modded aircraft carriers like the HMAS Melbourne, and are not working on tankers as well.

**To Reproduce**
1. set up an tanker like the KC130 and/or the aircraft carrier mod HMAS Melbourne (in which the A-4 was used in many nations) with a TACAN and an ICLS in the case of the carrier.
2. set a frequency that is not being used in the map (i've tried in persian gulf and in caucasus)
3. set the frequency in the cockpit, while playing. turn everything on and make sure the TACAN is working.
4. See that it doesnt show neither direction nor distance.

**Software Information (please complete the following information):**
 - DCS Version: 2.7
 - A-4E Version 2.0.0 beta 3

**Comment by callmepartario** [comment]
we're aware. radio functions have to be reverse engineered one at a time.

**Comment by callmepartario** [comment]
see also: #353
