### ISSUE TITLE
Gun Sight Brightness Knob resets at 1/2 way mark

### ISSUE THREAD

**Issue by WingTipVortice** [heclak/community-a4e-c#352]
**Describe the bug**
When turning the gunsight brightness knob with a bound encoder 1/2 way through the turn the gunsight turns off again and then brightens as you continue the turn until max where it is full bright again

**To Reproduce**
1. Aircraft power on
2. Gun Brightness Knob
3. Turn CW and CCW

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7 Open Beta]
 - A-4E Version [2.0beta-4]

**Additional context**
Discord Username is BirdFarm if more details are needed

**Comment by callmepartario** [comment]
this is how the gunsight brightness works! (see the helpful labeling on the outside of the knob)!
