### ISSUE TITLE
ARC 51 UHF  - Frequency MODE switch (the one that changes from Guard to manual to Preset.) and preset Channel key bind.

### ISSUE THREAD

**Issue by Baco1170** [heclak/community-a4e-c#354]
I asked for it before but it was closed.

Please read this one closely.

The new beta 4 implements change in ARC 51 Mode (tunrs ON, TR, TR+Grd and ADF) and the manual frequency-
Those are grate bindings but those you do on ground or in a level flight.

The ones we need in combat are precisely the ones left:
ARC 51 UHF FREQUENCY Mode  - The switch that changes from Preset, to manual to Guard.

and Preset Channels switch. self explanatory 

![Key Binds request](https://user-images.githubusercontent.com/70073631/117524905-22478600-af96-11eb-96a1-565b3564b0da.jpg)

Thanks again for the GRATE job !!!

**Comment by callmepartario** [comment]
thanks, will look into this soon

**Comment by Baco1170** [comment]
Thanks Mate!!! and again THANK YOU! and awesome job!

**Comment by callmepartario** [comment]
i've improved bindings for the radio again - there'll be single commands for switch positions (sorry i neglected the xmit mode last time), and i've added incremental input keybinds for the channel presets.
