### ISSUE TITLE
Can't select CMPTR

### ISSUE THREAD

**Issue by KumaRS4S** [heclak/community-a4e-c#355]
**Describe the bug**
using "Function selector switch - CW" and "Function selector switch - CCW" keybinds, it is impossible to select CMPTR. 

**To Reproduce**
1.bind one of the above commands to any key. 
2. use them to rotate the selector switch
3. Switch stops at Bombs / GM

**Expected behavior**
Switch needs to keep turning. 

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [newest version as of 09/05/2021]
 - A-4E Version [v 2.0.0 Beta 4]

**Additional context**

**Comment by callmepartario** [comment]
thanks, this is fixed and will be reflected in the next build.
