### ISSUE TITLE
Board Roughmet not aligned with Diffuse

### ISSUE THREAD

**Issue by HellesBelle** [heclak/community-a4e-c#356]
**Describe the bug**
a-4e_boards_1_RoughMet text in some areas is not aligned with a-4e_boards_1 diffuse text.
Mostly on the ENG panel left hand consul.

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7]
 - A-4E Version [v2.0 Beta 4]

**Comment by callmepartario** [comment]
ah yes, engine panel was relabeled, i'll re-align that map, thanks!

**Comment by callmepartario** [comment]
thanks, eagle eye! i've re-aligned these for the release.

**Comment by HellesBelle** [comment]
I only noticed because I invert the panel colour so I can read it better in low light (old age)

:)

**Comment by callmepartario** [comment]
dev note: updated textures are on the binary repo
