### ISSUE TITLE
left wheel animation issues (taxi)

### ISSUE THREAD

**Issue by HellesBelle** [heclak/community-a4e-c#357]
**Describe the bug**
Left main wheel locked (not rotating during taxi)

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7]
 - A-4E Version [v2.0 Beta 4]

**Comment by heclak** [comment]
I've fixed this with a new EDM. There was an animation change required for AI to work. Just need to make sure the latest ones are pushed in the build.

**Comment by HellesBelle** [comment]
Thanks heclak

**Comment by callmepartario** [comment]
seems like jnels may have addressed this one? can we get some repro?

**Comment by callmepartario** [comment]
resolved!
