### ISSUE TITLE
Function Selector Switch Binding

### ISSUE THREAD

**Issue by HellesBelle** [heclak/community-a4e-c#358]
**Describe the bug**
Binding the function selector switch CW or CCW to a key/button only allows selection of:
- Rockets
- GM Unarm
- Spray Tank
- LABS &
- Bombs & GM Arm

The switch will not rotate to CMPTR

Binding the function selector switch - CMPTR will take the switch in the cockpit to the selection.
(I know it's new and WIP)

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7]
 - A-4E Version [v2.0 Beta4]

**Comment by callmepartario** [comment]
thanks for the catch, we've already found and fixed this one, see #335
