### ISSUE TITLE
SFM Extender (in the works/ideas)

### ISSUE THREAD

**Issue by NeroDCS** [heclak/community-a4e-c#36]
Workflow:
Ground:
Steering handling beeing less instant

Air:
Departure at high AOA
Less controll authority at high AOA
trying to prevent the breakdown of the SFM at low speeds

**Comment by DISCOVMA131** [comment]
Happy to assist with pilot input and testing if\as neede

**Comment by DISCOVMA131** [comment]
Rudder should be primary roll control at high AOA and would be necessary to remain 'in control' - See Section IV of the NATOPS, pgs 4-4C through 4-5
