### ISSUE TITLE
improve afcs, radar gunpod, ecm, countermeasure, panel keybindings

### ISSUE THREAD

**Issue by WingTipVortice** [heclak/community-a4e-c#362]
**Describe the solution you'd like**
In the attached photo I have screenshot and descriptions of proposed button assignments that would improve the usability of some of the A-4s controls. Discord Username is Rob if any clarification is needed.

EDIT: IT WOULD ALSO BE NICE TO GET ON ELSE OFF TOGGLE COMMANDS FOR THE GUNPOD STATIONS AND AFCS
AS WELL INSTEAD OF A SINGLE BUTTON INPUT
![DCS 2021-05-11 10-43-57](https://user-images.githubusercontent.com/75806807/117861275-1aae0880-b246-11eb-9835-1659dd15a9fb.png)

**Additional context**
![DCS 2021-05-11 09-24-20](https://user-images.githubusercontent.com/75806807/117851777-7fb03100-b23b-11eb-8f3e-13afdebe4c78.png)

**Comment by callmepartario** [comment]
added improved gunpod panel bindings as requested

**Comment by WingTipVortice** [comment]
> added improved gunpod panel bindings as requested

You are the man!

**Comment by callmepartario** [comment]
added on/else off for countermeasures power and audio alq (note: this switch doesn't actually do anything functional at the moment, so i am not building a toggle key for it just yet)

**Comment by sobe1205** [comment]
Are you sure that the AFCS has keybinding?  I don't see them.

**Comment by callmepartario** [comment]
all requests from this are filled (on the develop branch), and will appear in the next issued beta (or release candidate). the only remaining issue here is SRS keybindings, which are duplicated and will be further tracked on #353
