### ISSUE TITLE
Radio and TACAN

### ISSUE THREAD

**Issue by matty260191** [heclak/community-a4e-c#363]
No matter what I do The aircraft never get a reply from a tanker. I have tried manually tuning in and just using the coms menu. Radis in T/R or T/R G and still no reply. SRS shows correct freq and the Coms menu goes white so show it sees in already on the frequency I send intent to refuel and no reply comes back. volume is 100% I have tried with KC135 boom and drogue and S3 no one reply's to my request. the tankers work for all my other aircraft.  when I talk to awacs they do reply so do airfields. i know they mad the tankers so they wont reply to aircraft that cant take fuel from them but the KC135 Drogue and S3 should reply.

I have similar issue with the TACAN wont pick up the carrier on 42X or any of my tanker TACANS. in REC or T/R. will pick up ground based tacans.

**Software Information (please complete the following information):**
 - DCS Version: [2.7]
 - A-4E Version 2.0.0.0 beta 4

**Comment by callmepartario** [comment]
you might want to join the discord to get appropriate operational assistance and mission settings for these functions. not all tacan functions, etc. are available (see #350 )

**Comment by matty260191** [comment]
For anyone who wanted the answer here. You need to install the A4E to the server so it knows what you are. For TACAN it needs warm up and only ground and SEA based TACANS work currently
