### ISSUE TITLE
add transient function to trim reset keybinding

### ISSUE THREAD

**Issue by WingTipVortice** [heclak/community-a4e-c#365]
**Describe the bug**
Trim reset results in a snap to 6 degrees when it should be a transient action

**To Reproduce**
1. Airplane on
2. trim resent bind

**Expected behavior**
I believe when trim reset it hit it should be a 1 deg/sec response rate or maybe even as slow as .5 deg/sec

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7]
 - A-4E Version [2.0-beta4]

**Additional context**

**Comment by callmepartario** [comment]
this has been added in for the next release -- the trim reset will now move all trim toward its default position, at the same speed it moves when given input by a user (and is modified as set in the aircraft's special menu). the nose trim will reset to 2 on the gauge, identical to start-up position, so as to avoid pointing your nose down.
