### ISSUE TITLE
Not a request...

### ISSUE THREAD

**Issue by karpiyon** [heclak/community-a4e-c#367]
I was wandering if you could direct me/assist in exporting DCS communication menu, either to a file or export.lua.
As long as I can read it.
I developed a **free** Voice Attack plugin for DCS, currently only for F-16 and want to implement the communication menu as well.
Yes VAICOM can do this but mine is free...

You can see a short intro (BMS but it works the same for DCS) here:

[(https://www.youtube.com/watch?v=2M3eduw7Lgo)]
[https://www.youtube.com/watch?v=s-2tSeMKevU]
[https://www.youtube.com/watch?v=2M3eduw7Lgo&t=20s]
[https://www.youtube.com/watch?v=VDv6Mk3VIWU]

**Comment by 08jne01** [comment]
If you want to speak to us contact us on our discord. https://discord.com/invite/tQZbkTQ
