### ISSUE TITLE
Input: Function selector switch in 2.0 beta 4

### ISSUE THREAD

**Issue by GRRK** [heclak/community-a4e-c#368]
Function selector does not turn to newly added CMPTR position when keymapping Function Selector Switch - CCW and CW are used.

Also there is inconsistency in category definition in lua files. Some positions are under Weapons & Instrument Panel, some are not. (this issue might bleed to other keymappings as well)

**Comment by callmepartario** [comment]
thanks, function selector is fixed in #355 -- that'll be fixed in the next beta. i 've gone through to revisit all those armament panel bindings and ensured everything has proper categorization, though, thank you.
