### ISSUE TITLE
LABS Bombing doesn't work

### ISSUE THREAD

**Issue by hulu7811** [heclak/community-a4e-c#370]
**Describe the bug**
LABS Bombing doesn't work

**To Reproduce**
Follow the step in the video 
A-4E Skyhawk: LABS Standoff Bombing Tutorial | DCS WORLD
[https://www.youtube.com/watch?v=7yjDYPXn0vw](url)

**Expected behavior**
In LABS light is on and LABS process is starting..
But in beta v4 , LABS function is not working. LABS is not turned on.
Beta v3 worked well.

**Comment by 08jne01** [comment]
Please don't link a poorly made an informed video as evidence the system doesn't work. The LABS system has not been implemented on the A-4 yet, the bombing system in the v2.0.0 is the CP-741/A. In every patch note up to beta-3 it has described that the LABS switch was a placeholder until the correct switch was animated.
