### ISSUE TITLE
change APC warm-up time to 15 seconds?

### ISSUE THREAD

**Issue by WingTipVortice** [heclak/community-a4e-c#372]
**Describe the bug**
APC warm up period seems way too long. In my recent test I waited about 90 seconds before engagement. Seems to work fine after 180 seconds

**To Reproduce**
1. Turn APC to STBY and wait 15 seconds
2. Wheels down
3. Flaps Down
4. Spoilers Out
5. Hook up
5. Throttle 70%<
6. on AOA
6. APC will not engage under that short of a wait period

**Expected behavior**
PER NAVWEPS 1-40AVM-01

**Screenshots**
![Screenshot 2021-05-20 143111](https://user-images.githubusercontent.com/75806807/119051460-0a99d580-b978-11eb-9946-418802483457.png)

**Software Information (please complete the following information):**
 - DCS Version: [2.7 Open Beta]
 - A-4E Version [2.0.0 beta4]

**Additional context**
This was tested during an AF landing not CVN.

**Comment by callmepartario** [comment]
this has been updated. the kneeboard for case3 landings will include a few quick instructions on enabling the APC.
