### ISSUE TITLE
Canopy black tinted problem

### ISSUE THREAD

**Issue by AdnanBuyuk** [heclak/community-a4e-c#373]
I have problem with latest version of mod and 2.7 dcs. I see the canopy tinted black but it is transparent and it is like some part of it are cutt off. Like when you have tinted foil on your car and some part of them are missing and you see clearly on that parts but rest of canopy is tinted

**Comment by callmepartario** [comment]
perhaps you are experiencing #312 ? (if this is the case, the only solution for the time being is to remove the installation of the conflicting mod. we've resolved this conflict and it will not be present in the next beta.)

can you provide a screenshot?

**Comment by AdnanBuyuk** [comment]
I will shortly just to take it

**Comment by 08jne01** [comment]
Closing this since no response it's a known conflict.
