### ISSUE TITLE
Comms menu disappearing when in air

### ISSUE THREAD

**Issue by Eagle01ph** [heclak/community-a4e-c#375]
On the ground, the comms menu works normally.  But whe you get in the air, the comms menu no longer shows up when pressing the comms menu keybind.  

Even when using Vaicom commands, on the ground everything is ok.  But once in the air, the voice commands don't work anymore.

 - DCS Version: 2.7.1
 - A-4E Version 2.0 beta-4

**Comment by 08jne01** [comment]
Use the PTT key. This is the same as every other DCS module.

**Comment by 08jne01** [comment]
> I did. Even saying "options" wouldn't bring it up. I can hear the beep where vaicom recognizes the command, but nothing happens. It's for all commands, i.e., "engage bandits", "Return to base", etc...
> 
> Anyways, thatnks for looking into to it. Probably just a setup error on my end with Voice Attack or Vaicom.

The VAICOM creators need to update their software for the A-4 most likely.
