### ISSUE TITLE
Supersonic A-4E-C (post specific munition deployment)

### ISSUE THREAD

**Issue by NatiroHadashi** [heclak/community-a4e-c#378]
Getting the A-4E-C (v2.0.0-beta-4) into supersonic flight will "stick" the aircraft in supersonic flight indefinitely, even with throttle pulled to idle.  
Slowing the aircraft to get below supersonic is difficult. Speed brakes do not deploy above Mach ~0.80

-----to replicate-----
Load 16x **M-81** bombs, 5x on each wing, 6x centerline station. stations (1 and 5 do not matter, empty or loaded seems to work)
drop those bombs, there might be a weight calculation issue with dropping certain ordnance. (for example **Mk-81** will not trigger the bug, but **M-81** will)  

A-4 Version = A-4E-C (v2.0.0-beta-4)
DCS Version = 2.7.1.6709 Open Beta

![Screen_210527_202041](https://user-images.githubusercontent.com/79599393/119927244-ecab1280-bf2d-11eb-8dae-934b59b7310a.png)
![Screen_210527_202253](https://user-images.githubusercontent.com/79599393/119927899-3e07d180-bf2f-11eb-855b-285f9c2b4730.png)

images to show altitude, airspeed, engine RPM / fuel flow

**Comment by 08jne01** [comment]
This is a very good spot, looks like there is a bigger problem with how the racks are defined, specifically though the drag defined for the M81 is higher than that defined for each bomb on the rack so when you drop them it subtracts the larger drag causing the result to be negative drag when all bombs are set.

**Comment by 08jne01** [comment]
Hello thanks for the report. This has been fixed in commit c36216c6185b930d721b695cfd47c7b6e0dfdc3c. Please check it is fixed. If there is still an issue reopen or submit a new issue thanks.

**Comment by NatiroHadashi** [comment]
I will test it tomorrow in Beta5.  I was concerned the report was too close to the event to make it in.

**Comment by 08jne01** [comment]
> I will test it tomorrow in Beta5. I was concerned the report was too close to the event to make it in.

No this is a pretty hight priority defect, I fixed it this morning.
