### ISSUE TITLE
Bomb Drag Counted Twice

### ISSUE THREAD

**Issue by 08jne01** [heclak/community-a4e-c#379]
![image](https://user-images.githubusercontent.com/1359572/119955658-287ac200-bf98-11eb-9faa-9437b77d9c28.png)

This adds the drag for the number of bombs, however DCS already adds this drag when mounting the bombs on the rack. This results in the drag being added twice, which effectively makes for a very draggy MER rack.

**Comment by heclak** [comment]
Did they change this? When we implemented this, they were doing this on their MER mounted weapons too.

**Comment by 08jne01** [comment]
> Did they change this? When we implemented this, they were doing this on their MER mounted weapons too.

No this isn't true, I just created this issue while I was investigating. There is some strange behaviour. A lot of official DCS stores do not have their drag correctly calculated. For example the MER wit the BDU-33 will have negative drag when they are all dropped.

This effects us because we multiply the total drag by a factor of 0.85 and 0.9 for the MER and TER respectively. In the case where the total Cx_pil is less than bomb_variant.cx * count then after releasing all the bombs it will have negative drag for that pylon.

There isn't really anything we can do about this, luckily the rack has enough drag that the resultant drag is still a sufficiently large value, although still less than the actual drag of the rack.
