### ISSUE TITLE
address radar and speed hold keybinds

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#380]
i added these FC3 commands to the joystick, but am wondering if they really function or do anything now that we are off SFM-land.

if these are indeed nonfunctional, i think we should comment them out or remove them entirely to eliminate any user confusion from pilots who are taking their first steps outside the FC3 world.

**Comment by 08jne01** [comment]
I searched the code base looks like they were used in the original afcs as debug commands. They can be commented out in case we need them for debugging in future.

**Comment by callmepartario** [comment]
excellent. done.
