### ISSUE TITLE
TACAN Channel 1s Increase/Decrease mappings missing

### ISSUE THREAD

**Issue by Nick-Thain** [heclak/community-a4e-c#388]
The new A-4E-C Beta has new key mappings for the TACAN controls, but the controls to Increase and Decrease 'TACAN 1s' are still missing (see screenshot):

![image](https://user-images.githubusercontent.com/71908888/120339962-6c2c3f00-c2aa-11eb-8ce8-770b5b4d6964.png)

**To Reproduce**
1. Open Control Settings
2. Scroll down to TACAN
3. All TACAN settings are available to map except TACAN 1sec Increase/decrease

**Expected behavior**
I expect to see TACAN 1SEC Increase/Decrease mappings as well

**Screenshots**
![image](https://user-images.githubusercontent.com/71908888/120340148-9847c000-c2aa-11eb-9fa8-cd2fc09b70e8.png)

**Software Information (please complete the following information):**
 - DCS Version: 2.7.1.6709 Open Beta
 - A-4E Version v2 beta 5.1

**Comment by callmepartario** [comment]
it was in the keyboards twice, and missing from the joystick, a paste error on my part. fixed it.
