### ISSUE TITLE
Tomcats livery has a extra dynamic number on the rudder and is missing one on the nose 

### ISSUE THREAD

**Issue by Wolfdog20** [heclak/community-a4e-c#390]
The Tomcats skin has a extra dynamic number on the rudder
![unknown](https://user-images.githubusercontent.com/83850835/120421128-d41d7b00-c3b9-11eb-9477-f1532fa48e99.png)

**Comment by Wolfdog20** [comment]
[USMC VMA-311 Tomcats.zip](https://github.com/heclak/community-a4e-c/files/6581908/USMC.VMA-311.Tomcats.zip)
Version with no dynamic number on the rudder

**Comment by Wolfdog20** [comment]
[USMC VMA-311 Tomcats.zip](https://github.com/heclak/community-a4e-c/files/6581946/USMC.VMA-311.Tomcats.zip)
Added the missing dynamic number and removed the extra one

**Comment by callmepartario** [comment]
fixed
