### ISSUE TITLE
CH-53E "Super Stallion" mod incompatibility

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#391]
A bug in DCS World is causing the presence of CH-53E "Super Stallion" module installation to shut down a mandatory system in the A-4E-C. 

At this time, there is no solution for this incompatibility short of the user choosing to keep only one of these two modules installed.

**Comment by 08jne01** [comment]
All missions.

**Comment by callmepartario** [comment]
the module will now notify the user of this incompatibility (thanks jnels)

**Comment by callmepartario** [comment]
incompatibility is also noted in the "known issues"
