### ISSUE TITLE
MCL course-needle offset on HMAS Melbourne

### ISSUE THREAD

**Issue by Bremspropeller** [heclak/community-a4e-c#392]
The course-needle of the MCL does not coincide with the angled-deck of the HMAS Melbourne (Mod Carrier), but creates a course about 10° to port/ left.

**Expected behavior**
The course should coincide with the angled deck.

**Screenshots**

![MelbourneICLS1](https://user-images.githubusercontent.com/85362270/120836132-86457600-c565-11eb-8a0a-38b1f8f38e14.jpg)

![MelbourneICLS2](https://user-images.githubusercontent.com/85362270/120836249-a37a4480-c565-11eb-9b2d-f79f844b40fa.jpg)

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.1.7139 Open Beta
 - A-4E Version 2.0.0-beta-5.1

**Comment by callmepartario** [comment]
in light of better cat launch facilities, is this worth pursuing for 2.0?

**Comment by callmepartario** [comment]
closing this issue; melbourne and hermes data has been incorporated for RC4/release
