### ISSUE TITLE
gunsight glass displaying raindrops

### ISSUE THREAD

**Issue by peeecet** [heclak/community-a4e-c#395]
**Describe the bug**
Gunsight Glass Getting Wet During Rain

**To Reproduce**

1. Cold start in a day with "Overcast And Rain 1"
2. Look at the gunsight, it has droplets on it

**Expected behavior**
The glass of the gunsight should not have the droplets effect during rain

**Screenshots**
`https://ibb.co/7RLZ2MR`

**Software Information (please complete the following information):**
 - DCS Version: 2.7.1.7139 Open Beta]
 - A-4E Version v 2.0.0-beta-5.1

THANK YOU THIS MOD IS AMAZING!

**Comment by callmepartario** [comment]
thanks, this will be fixed by release time. heclak's already provided an updated 3-d model with the fix in.
