### ISSUE TITLE
clickable cockpit feature loss

### ISSUE THREAD

**Issue by vfaco** [heclak/community-a4e-c#398]
Periodically the cockpit mouse click feature completely fails and the icon becomes a yellow cross. It happens both before and  during flight for no apparent reason. The aircraft continues to fly normally and features are available via keyboard and hotas. Then suddenly it starts working for no reason -- it happened while I was typing this with the sim running in the background. 

DCS 2.7;  A4 2.0.0 beta 5

P.S.  I have lots of real world time in the A7A and the A7E as well as the F18. This sim is the closest to the real world that I've seen. Most DCS aircraft are what I call "squirrely", as they don't accurately simulate the effect of inertia on the flight characteristics. Nice work.

Bob

**Comment by 08jne01** [comment]
User has not sent a track closing this. If you encounter it again and have a track file please submit another defect report.
