### ISSUE TITLE
wing vapour client replication

### ISSUE THREAD

**Issue by clutchtomcat** [heclak/community-a4e-c#401]
Overwing vapor doesn't appear to be visible to other clients online.

Very minor issue that's probably low priority, but is somewhat disappointing compared to the synced vapes on other modules.

**Comment by callmepartario** [comment]
Replicated this issue on the Vietnam War server this morning on A4-E-C 5.1 / DCS OB 2.7.1.7139

**Comment by 08jne01** [comment]
This is a limitation for the LERX which is what is used to generate the vapours. If ED makes it the case such that LERX are not client side then this will be fixed however until that point this will remain a DCS limitation.

A workaround is to have some 3d modeling to create an overwing vapour animation however they don't look as cool as the LERX implementation and this would be a feature request.

**Comment by clutchtomcat** [comment]
LERX is a different technique than what ED uses for wing/LEX vapor? I noticed the F-14 has the same issue.

**Comment by 08jne01** [comment]
LERX is the same technique that ED uses. I believe if you check the hornet it's LERX vortices are client side only on multiplayer. The overwing vapour is a 3d model animation which can be easily synced over multiplayer.

**Comment by clutchtomcat** [comment]
Now that you mention it I have noticed a lack of LEX vapor on the Hornet when on multiplayer. I thought I saw LEX vapor on the Viper in multiplayer, though.
