### ISSUE TITLE
Fuel gauge anomalies

### ISSUE THREAD

**Issue by clutchtomcat** [heclak/community-a4e-c#402]
I'm finding the fuel gauge to act a bit funny. 

**Symptoms**

Crusing at 3000 PPH, I would expect to burn 500lbs (0.5) of fuel in 10 minutes. During an OPS check I note fuel gauge reading around 2.5 or 2.6. Upon checking again 10 minutes later the fuel gauge is reading around 2.9, thus increased in 10 minutes. Later on in the flight, I did another OPS check about 10 minutes prior to rolling in on the target with the gauge still at 2.9. Upon rolling in on the target 10 minutes later, the fuel gauge was still reading 2.9. Throughout this period I was maintaining an engine setting of 3000 PPH.

Additionally, the fuel gauage has a tendency to rise ~500lbs after refueling from a KC-130.

**Variables**

Unsure if it only happens in certain situations or all situations, so I'll list my specific variables when I see this happen.

-Multiplayer
-Supercarrier "runway" start
-300gal centerline tank
-70% fuel load at start (if I recall correctly)
-Cruising at FL180; also observed at FL150
-Assorted weapons configs (e.g. 2xAGM45 2xMk20; 2xZuni 10xMk81)

**Comment by 08jne01** [comment]
You are starting with an external tank + 70% fuel, this means the external tank will feed into the integral wing tank and into the fuselage tank, this results in your internal state staying roughly the same, where you external tank is likely being drained. I checked the fuel consumption it matched exactly with the gauge readouts.
