### ISSUE TITLE
Add single keybind for STOPWATCH start/stop/reset.

### ISSUE THREAD

**Issue by NatiroHadashi** [heclak/community-a4e-c#404]
The stopwatch at the top of the canopy, next to the whiskey compass has a clickable 3D button that accurately starts, stops and resets the stopwatch,  however there is no associated keybind for that action.

A single keybind could be used as "Stopwatch start/stop/reset"

**Comment by callmepartario** [comment]
good catch. i've added this, and it appear in the next release.
