### ISSUE TITLE
remove D-704 Buddy Refueling Pod from loadout options

### ISSUE THREAD

**Issue by Cubeboyy** [heclak/community-a4e-c#406]
The D-704 Refueling Pod still shows up as available to equip through pre-set loadouts. 

**Steps to reproduce:**
1. Go to the mission editor
2. Spawn an A-4
3. Scroll through the loadouts until the loadout appears, then proceed to select.

**Expected behavior**
This loadout should not be available as the D-704 Refueling Pod is a deprecated feature.

**Screenshots**
![Screen_210623_181754](https://user-images.githubusercontent.com/59150119/123176550-a2944e80-d451-11eb-9c96-922ef6ca9a89.png)

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.2.8165.2
 - A-4E Version: EFM Beta 5.1 (Build fetched from develop branch on 6/22/2021)

Consider removing the edm file from the repo to avoid any future inquiries about the deprecated buddy refueling concept.

**Comment by callmepartario** [comment]
pretty sure these should be gone, but i will look into this and ensure we're up to speed.

**Comment by callmepartario** [comment]
got it, this is cleared out now.
