### ISSUE TITLE
Cockpit console background lighting misaligned

### ISSUE THREAD

**Issue by HellesBelle** [heclak/community-a4e-c#407]
ENG panel background lighting misaligned

Turn ARG 119 on in model viewer on.
Background lighting is from the old panel.

![a-4 background lighting 1](https://user-images.githubusercontent.com/55719739/123184011-26901a00-d4d6-11eb-9525-a10278fde838.jpg)

**Comment by callmepartario** [comment]
this has already been fixed in current binaries, but good spot!

![image](https://user-images.githubusercontent.com/17432407/123184270-581ace00-d461-11eb-8bf9-bcdd51e23729.png)

**Comment by HellesBelle** [comment]
Thanks buddy 😀
