### ISSUE TITLE
jettisoning Mk-77 mod 0 and mod 1 bombs causes CTD

### ISSUE THREAD

**Issue by AusRedNeck** [heclak/community-a4e-c#408]
**Describe the bug**
Crash to desktop immediately after selective jettison of station 2

**To Reproduce**
1. Have stores on stations ( i was loaded with MK 77 )
2. Click on station 2 to make it active,
3. Select station 2 on selective jettison dial
3. Pull the jettison handle
4. crash to desktop

**Expected behavior**
While jettison on stations 3 and 4 worked just fine, repeated testing showed CTD on station 2

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.2  Open Beta]
 - A-4E Version - latest release as of 6/22/2021

**Additional context**
Haven't had a chance to test if it does it on empty pylons or with different weapons.

**Comment by callmepartario** [comment]
Confirmed -- 
- CTD when jettisoning MK-77 mod 0 or MK-77 Mod 1 bombs from any station (including WNG or AL drops). 
- Oddly enough, Station 3 jettisons the above weapons just fine, when using the 2-MER rack option.
- In my testing other jettisons, no other weapons cause similar crashes, including the MK-81 and MK-88 (the other A-4 custom weapons).

**Comment by 08jne01** [comment]
Can someone post a log when able?

**Comment by callmepartario** [comment]
didn't get much from the log, but hope this is useful:
[dcs.log](https://github.com/heclak/community-a4e-c/files/6729272/dcs.log)

**Comment by callmepartario** [comment]
weapons lua mentions drag variables being "fucked" for these - is this something that could be causing a bad interaction with the EFM?
