### ISSUE TITLE
add CW/CCW keybindings for AWRS drop interval

### ISSUE THREAD

**Issue by Whiskey75** [heclak/community-a4e-c#410]
There is no key bindings for the emergency release selector and AWRS drop interval (selector)

Can the key bindings follow along the lines of the weapons station selection key bindings?
Emergency release station 1-2-3-4-5?

AWE-1 AWRS drop interval can use a  CW/CCW binding.

**Comment by callmepartario** [comment]
there's an axis bind for the AWRS, i think, but i'll work on getting any needed keybinds in. the emergency selector has already been added, see #409

**Comment by callmepartario** [comment]
as i thought, keybinds for the AWE-1 are already defined. 
look for "AWE-1 DROP INTVL - Increment" and "AWE-1 DROP INTVL - Decrement".
