### ISSUE TITLE
Training Mission 05 VFR Landing - causes shader error upon loading

### ISSUE THREAD

**Issue by danw-eth** [heclak/community-a4e-c#411]
**Describe the bug**
Training Missions 05,10,11,12,15 - all cause shader error upon loading, DCS crashes. Consistently reproduceable.

**To Reproduce**
1. Open DCS training missions
2. Select A-4
3. Select training mission 05,10,11,12,15
4. Click Start
5. Loading proceeds through a few items
6. Error as per screenshot

**Expected behavior**
Mission should load as per other training missions (eg 1-4 work)

**Screenshots**
![image](https://user-images.githubusercontent.com/12576248/123918058-d37f0100-d9c6-11eb-8914-5763072a174f.png)

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7.3.8494 Open Beta]
 - A-4E Version [Version 2.0.0-beta-5]

**Comment by danwatto** [comment]
UPDATED: Training mission 7 also causes issue

**Comment by danwatto** [comment]
Updated: All training missions tested, 05,10,11,12,15 cause this same error.

**Comment by rudel-chw** [comment]
Hello. Those missions use the VPC Airfield Mod, which on DCS 2.7 needs a fix to work, get it here: https://forums.eagle.ru/topic/152272-vp-airfield-equipment-082-beta/page/15/#comment-4627921

**Comment by callmepartario** [comment]
closing this, as this is interaction related, thanks for the assist, rudel.
