### ISSUE TITLE
Not able to exit map screen to fly the SkyHawk

### ISSUE THREAD

**Issue by JimmyPP** [heclak/community-a4e-c#412]
Dear all,
First of all thank you for developing the free Skyhawk module – I enjoyed it very much.
That is my got to plane for little buzzing around in Dubai downtown or SEADs vs. Iranian SA-2s.
I am struck since a couple of weeks in a situation identical to this with A-4 SkyHawk mod:
https://steamcommunity.com/app/223750/discussions/0/1744479063990253835/?ctp=1
Old and new missions and instant action always start in the map view without the possibility to switch inside the airplane. (Other planes do work)
Reinstall etc does not worked. The Steam community Thread indicates that this is an registry issues.
I have “cleaned” the registry in between the reinstalls and afterwards with ccleaneer – no solution there.
With regedit I could not find an obvious reference to the DCS Skyhawk mod.
The link https://www.digitalcombatsimulator.com/en/support/faq/564/#1780273 showed a solution to that very problem with other planes.
Next thing would be a new setup of the computer fully fresh – but this is quite a lot of work including the loss of multiple other now working software. 
Any suggestion were to look might be helpful. Thank you and best regards

**Comment by callmepartario** [comment]
a fresh download and complete cleaning of your user files might be in order; if you're experiencing issues with other modules, the issue is likely not sourced from the A-4E-C.

**Comment by callmepartario** [comment]
a fresh download and complete cleaning of your user files might be in order; if you're experiencing issues with other modules, the issue is likely not sourced from the A-4E-C.
