### ISSUE TITLE
add aerodynamic fairing to the zuni rocket pods (reduce drag)

### ISSUE THREAD

**Issue by Bungo71** [heclak/community-a4e-c#413]
A full loadout of Zuni rocket pods is like flying with a barn door attached to the centre pylon.  Can we add the aerodynamic fairings to the front and rear of the Zuni pods and reduce the drag on them?

The step on the pod that the fairings sit on are already modelled, just need the fairings to go over them,

![119460808_1198766903834060_3515401137190357958_n](https://user-images.githubusercontent.com/64348065/124451130-6dc8b580-ddc8-11eb-8b86-5e0811a12fe3.jpg)
![27650004167_e3f5d8cb69_o](https://user-images.githubusercontent.com/64348065/124451208-80db8580-ddc8-11eb-896b-a9f3b077115b.jpg)

**Comment by callmepartario** [comment]
as the zunis we're using are now the DCS-native launchers, we're not in a position to do additional modeling upon them, i'm going to close this one.
