### ISSUE TITLE
Mislabelled AP disconnect button

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#414]
**Describe the bug**
Button should be labelled "AP" instead of "AF"

![image](https://user-images.githubusercontent.com/46121009/124462921-b9796000-ddc4-11eb-8876-3fc34e20e074.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]: NA
 - A-4E Version [e.g. v1.3]: Dev branch

**Additional context**

**Comment by callmepartario** [comment]
thanks, will update binaries today.
