### ISSUE TITLE
Sidewinder seeking sound of is replaced by that of the Flaming Cliffs' F-15C after first use of the F-15C

### ISSUE THREAD

**Issue by carlosborca** [heclak/community-a4e-c#415]
**Describe the bug**
After using an AIM-9 in the F-15C for the first time after the installation of the Flaming Cliffs 3 module the default seeking sound of the A-4E gets substituted by that of the F-15C. Note that the default locked-on-growling sound of the A-4E-C is correctly preserved and it is only the seeking sound that gets replaced by the awful grinding sound of the F-15C. Note also this happens in offline mode. I have not tested it in a multiplayer setting. Additionally, switching on and off the master arm will not fix the issue (as has been suggested when sound issues with the growl appear in multiplayer mode). Please let me know if I can be of any further help.

**To Reproduce**
1. Install a clean DCS or DCS openbeta.
2. Add the A-4E-C module.
3. Load an AIM-9 on the A-4E-C and have it reproduce its seeking tone (This is the correct sound).
4. Now add the FC3 module.
5. Load an AIM-9 on the F-15C and have it reproduce its seeking tone (This is the wrong sound).
6. Next, load an AIM-9 on the A-4E-C and have it reproduce its seeking tone (This will now be the wrong sound, equivalent to the one from the FC3 F-15C).

**Expected behavior**
I would expect the A-4E-C's AIM-9 seeking sound to be preserved, whether I have installed the FC3 module or not. I would expect it to sound like in this YouTube video (https://www.youtube.com/watch?v=vvX_YDxAy6U&t=245s), not like in this file I recorded: 
https://user-images.githubusercontent.com/23508182/124852407-431a6080-df72-11eb-8d78-ebf235e4be3a.mp4

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.2.8165.2]
 - A-4E-C Version [e.g. v2.0.0-beta-5.1]
 - Flaming Cliffs 3.0

**Acknowledgement**
Just a sincere congratulation for the amazing work that has been put in this awesome DCS module, likely one of the best. Thank you. I just post this as an improvement suggestion.

**Comment by callmepartario** [comment]
the aim-9 sounds in the next version will be original to the module, and fix the missing / replaced sounds issue.
