### ISSUE TITLE
Wing Spoilers activate at incorrect RPM

### ISSUE THREAD

**Issue by HellesBelle** [heclak/community-a4e-c#416]
In the A-4 manual one of the conditions for the wing spoilers to extend is RPM below 70%.
Currently they only stow when RPM increases above 85% and then extend when RPM reduces below 85%.

**Comment by pohlinkzei** [comment]
From a first glance it looks like:
* In the manual it says: The throttle position is below 70% RPM. 
* In the code only the throttle position is evaluated, so this might translate from 70% throttle to 85% RPM.

**Comment by 08jne01** [comment]
> From a first glance it looks like:
> 
> * In the manual it says: The throttle position is below 70% RPM.
> * In the code only the throttle position is evaluated, so this might translate from 70% throttle to 85% RPM.

Yea I think it is a case of adjusting the value of the trigger for the throttle position. I don't believe it checks RPM but rather throttle position judging by the manual's wording.

**Comment by 08jne01** [comment]
> Fixed, tested and verified with the attached patch and the mission file.
> [0001-Set-spoilers-to-engage-at-70-RPM-instead-of-70-throt.patch.txt](https://github.com/heclak/community-a4e-c/files/6975163/0001-Set-spoilers-to-engage-at-70-RPM-instead-of-70-throt.patch.txt)
> [01-A-4E-C-throttletest.zip](https://github.com/heclak/community-a4e-c/files/6975171/01-A-4E-C-throttletest.zip)
> Unzip the mission if you want to verify and remove the txt from the patch. (I have to figure out, how I can commit to github, things changed in the last couple of years)

It's easier probably if you submit a pull request. Also that way you get credit for your contribution.

**Comment by pohlinkzei** [comment]
I already forked, but have issues committing to the repo. I"ll figure that out.

**Comment by 08jne01** [comment]
> I already forked, but have issues committing to the repo. I"ll figure that out.

You commit to your own forked repo on your develop branch. Then you submit a pull request on github. That will create a code review we can look at. Once that is checked then we can approve it and it will be merged into our repo.

**Comment by 08jne01** [comment]
This is resolved thanks to @pohlinkzei
