### ISSUE TITLE
Does not show up on dropdown menu

### ISSUE THREAD

**Issue by EOIH** [heclak/community-a4e-c#418]
**Describe the bug**

I am trying to create a quick mission however the A-4E does not show up on the dropdown menu. I am not sure If I installed correctly however, so it may be my fault.

**To Reproduce**
1. Go to: Quick Mission
2. Click on: Aircraft dropdown menu
3. See error

**Software Information**
 - DCS Version: [DCS 2.7.3]
 - A-4E Version [2.0.0 Beta 5.1]

**Comment by callmepartario** [comment]
the most likely issue is that you've got the historical filter checked (see the clock at the bottom-center of the mission editor). seeing as this is a common user error, i am closing this issue.

if you continue to have issues or are worried about the integrity of your installation, pop by the discord.
