### ISSUE TITLE
add interior lights brightnes switch keybind

### ISSUE THREAD

**Issue by danwatto** [heclak/community-a4e-c#419]
Could we please have bindings available for:
1. TACAN/NAV switch that switches the HSI navigation
2. Interior lighting flood/bright 3 way switch including a binding to toggle between the 3 on one joystick button
3. Bomb interval buttons instead of axis so we can bind to an encoder dial

Thanks!

**Comment by callmepartario** [comment]
items 1 and 3 on your list are already implemented, at least in the dev build. i will look into no. 2.

**Comment by callmepartario** [comment]
i've added bindings for single position, 3-position switch and a cycle for this switch. thanks for spotting the missing binding!
