### ISSUE TITLE
New Cockpit

### ISSUE THREAD

**Issue by JT-Jonson** [heclak/community-a4e-c#424]
I would like to give a suggestion of the panel, cockpit for this beautiful A-4,
in this case, they are the A-4 used by Brazil, called VF-1, with the HOTAS concept, Elta 2032 radar.
It would be great to be able to struggle with these changes.

![2_anos_modernizacao_af_021](https://user-images.githubusercontent.com/63390188/130385969-e4cb7dd2-1786-4e1d-8084-992af95c073f.jpg)
![AF-1M-Cockpit](https://user-images.githubusercontent.com/63390188/130385972-e562aa54-cd55-45a8-9dfc-2fce30ed5475.jpg)
![Painelmodernizacao_af-11](https://user-images.githubusercontent.com/63390188/130385974-9cc661ac-e9cd-4f92-bd76-12d4b812a358.jpg)
![vfground021-600x313](https://user-images.githubusercontent.com/63390188/130385978-f6d706e1-2b83-4d21-a230-6e7e8e8fd7ac.jpg)
![Painel_AF-1M-600x399](https://user-images.githubusercontent.com/63390188/130385979-c04e8d4a-35d0-41e9-9be7-67a4cc329aae.jpg)
This is the Brazilian F-5EM panel
![Tigerbr-cabine](https://user-images.githubusercontent.com/63390188/130385980-8e7aee42-6c8d-4c88-845d-f41fd24cb2cc.jpg)
![AF-1B-painel](https://user-images.githubusercontent.com/63390188/130385982-1c671f85-432a-491e-9049-91a239f1862c.jpg)

**Comment by 08jne01** [comment]
Sorry but this will never happen, we can neither model all the systems with the current API and there likely isn't enough information out there to model these systems. Not to mention the required man-hours to do this.

**Comment by JT-Jonson** [comment]
This is really bad.
I thought there was a way, because I have an A-29B from another group that has this same system.
here is the link.
https://github.com/luizrenault/a-29b-community
Thank you anyway!!

**Comment by 08jne01** [comment]
> This is really bad.
> I thought there was a way, because I have an A-29B from another group that has this same system.
> here is the link.
> https://github.com/luizrenault/a-29b-community
> Thank you anyway!!

I mean you could probably do all the pages but anything that interacts with DCS, ie guided weapons or targeting pods etc would be impossible. In other words still not worth it.
