### ISSUE TITLE
Keybinds for Emergency Release station selector

### ISSUE THREAD

**Issue by danwatto** [heclak/community-a4e-c#426]
**Is your feature request related to a problem? Please describe.**
The emergency release station selector is not able to be mapped to buttons on a joystick. 
For example the 5 position mode switch on throttles like Virpil, most use as a Jettison position selector.

**Describe the solution you'd like**
Discrete mappings for position 1, position 2, position 3 etc so we can map them individually.
Also useful would be a CW/CCW for people who want to move it directionally with a hat switch.

**Describe alternatives you've considered**
Using the mouse is not ideal when under attack and needing to jettison quickly.

**Additional context**
n/a

**Comment by callmepartario** [comment]
this has already been implemented and will appear in the next release.
