### ISSUE TITLE
DCS liberation mission TACAN settings causing CTD

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#429]
user TheRidiculousRoSchbin#5794 reports DCS liberation mission missions are having difficulties with the TACAN system which cause crashes to desktop.

Possible interactions might include setting a Y channel or engaging the TACAN A/A switch

dcs 2.7
5.1 beta

**Comment by callmepartario** [comment]
Crash logs attached

[dcs.log-20210911-200628.zip](https://github.com/heclak/community-a4e-c/files/7148445/dcs.log-20210911-200628.zip)

**Comment by zelosos** [comment]
Yes can confirm. Use the following mission to reproduce:
[liberation_nextturn.zip](https://github.com/heclak/community-a4e-c/files/7978919/liberation_nextturn.zip)

Set TACAN to A/A and Channel to 37.
This will yield a Crash to Desktop reproducable.

**Comment by callmepartario** [comment]
Looks like Liberation 7.0 has been addressed to fix this issue.
