### ISSUE TITLE
Can't steer nose wheel (not steering with rudder either)

### ISSUE THREAD

**Issue by farbod1277** [heclak/community-a4e-c#436]
**Describe the bug**
I am unable to steer the nose wheel. I am aware that it was removed in the latest pre-release, but I need it while taxiing.

**Software Information (please complete the following information):**
 - DCS Version: Steam
 - A-4E Version: v2.0.0-RC1

**Additional context**
I thought the nosewheels were now remapped to steer at the same time as the rudders, but I checked from external view and the nose wheel isn't moving when I move the rudders. I'd ideally like independent control of the nose wheels with the Rz axis of my joystick anyway and not have it bound to rudder movement.

**Comment by farbod1277** [comment]
Update: I found I can steer the nose wheel when I use differential toe braking. So when braking on the left pedal the nose wheel slowly turns left, so on. Is this the expected behaviour? Why can't I just use my joystick's Rz to control the wheel's direction? Thanks

**Comment by farbod1277** [comment]
I was told on discord that this is how it's meant to behave since the A-4E doesn't actually have nose wheel steering.

**Comment by cerealexfpv** [comment]
True, I found out today that it does not have nws, anyway for the carrier it is very difficult to orient the plane towards the catapult, it would be great if they enable the nws option for those of us who want to use it. Please nws option on next update!!
