### ISSUE TITLE
Radio Microphone Push to Talk (PTT) inoperable after manual adjustment of AN/ARC-51A UHF Radio frequency

### ISSUE THREAD

**Issue by heiko-jakob** [heclak/community-a4e-c#443]
Radio Communication button sometimes stops working after changing frequencies manually.
Communications also can't be recovered by switching to the preset frequencies. 

A-4-V2.0.0beta5
DCS OpenBeta 2.7.7.15038

**Comment by callmepartario** [comment]
have never encountered this phenomenon. do you have the AH-6, CH-47, or CH-53E mods installed?

**Comment by 08jne01** [comment]
> Radio Communication button sometimes stops working after changing frequencies manually. Communications also can't be recovered by switching to the preset frequencies.
> 
> A-4-V2.0.0beta5 DCS OpenBeta 2.7.7.15038

Do you mean the actual radio PTT or the communication menu button?

**Comment by callmepartario** [comment]
oh good question, i hadn't considered they were still hitting backslash and trying to do it through the regular comms menu.

**Comment by heiko-jakob** [comment]
I was able to drill it down a bit. 
-> Communications button doesn't work on the stick, as well as on the keyboard
-> Works on the ground before take off and after landing
-> Happens some time after take off so i'm unable to do any ATC stuff after take off

I have the following non official mods installed:
A-4
T-45C Goshawk (which i also have trouble getting Radio to work)
Hercules ( Haven't tried yet, the A-4 was too much fun to fly and it got me hooked ...)

**Comment by 08jne01** [comment]
> I was able to drill it down a bit. -> Communications button doesn't work on the stick, as well as on the keyboard -> Works on the ground before take off and after landing -> Happens some time after take off so i'm unable to do any ATC stuff after take off
> 
> I have the following non official mods installed: A-4 T-45C Goshawk (which i also have trouble getting Radio to work) Hercules ( Haven't tried yet, the A-4 was too much fun to fly and it got me hooked ...) SRS

You need to use the radio PTT not the communication menu button when you are airborne and trying to use the radio and the difficulty is set to realistic for radios.

**Comment by heiko-jakob** [comment]
It seem's to be a no-bug. Works fine if i rebind the PTT button instead of COMM. 
But what's the reason behind it if the A-4E has only one radio anyway ?
