### ISSUE TITLE
A-4 falls from deck after repair on CV-59 Forrestal

### ISSUE THREAD

**Issue by heiko-jakob** [heclak/community-a4e-c#444]
**Describe the bug**
A-4 falls from deck after repair on CV-59 Forrestal.
After repair on board the Forrestal, the A-4 immediately falls from the deck backwards.
Tried this now several times, always with the same result.

**To Reproduce**
1. Land on the CV-59 Forrestal
2. Repair the A-4
3. Fall over board immediately
4. See attached Track (Needs Hercules+ T-45 Goshawk mod to replay)

**Expected behavior**
The A-4 should be in a stable parked position on the deck

**Screenshots**
See the attached track file

**Software Information (please complete the following information):**
A-4-V2.0.0beta5
DCS OpenBeta 2.7.7.15038
[A4-Falls from Forrestal.zip](https://github.com/heclak/community-a4e-c/files/7479473/A4-Falls.from.Forrestal.zip)

**Additional context**

**Comment by heiko-jakob** [comment]
[A4-Falls from Forrestal-Short.zip](https://github.com/heclak/community-a4e-c/files/7488020/A4-Falls.from.Forrestal-Short.zip)
Created a simple mission and track without the need for other modules to reproduce.

**Comment by pohlinkzei** [comment]
Hi, I tried this with RC2 and did not fall off the ship. The A4 moved when it was reased down but did not fall off. Apllied brakes reduced the amount of movement.

**Comment by callmepartario** [comment]
i'm experiencing the same @heiko-jakob - try updating your installation to version 2.0.0-RC2 at https://github.com/heclak/community-a4e-c/releases/ and let us know if this is persisting for you.

**Comment by 08jne01** [comment]
Since there is no confirmation I'm gonna close this until someone can provide evidence.
