### ISSUE TITLE
Since DCS 2.7 the external power unit seems to float over the ground.

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#445]
**Describe the bug**
Since DCS 2.7 the external power unit seems to float over the ground.

**To Reproduce**

While parked at any airbase, call up external electric power from the Ground Crew menu, after a few seconds the external power unit appears.

**Expected behavior**
The 3D Object should be closer to the ground.

**Screenshots**
Attached

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.7.15038 Open Beta
 - A-4E Version: A-4E-C Version 2.0.0-RC2

**Additional context**
![Screen_211113_181445](https://user-images.githubusercontent.com/51679833/141659558-41f62784-fdaa-4bc8-9815-ddf766284c86.jpg)
![Screen_211113_181603](https://user-images.githubusercontent.com/51679833/141659559-ab21ec70-32cb-4182-af84-4bc81dd66213.jpg)

**Comment by callmepartario** [comment]
closing for duplication, see #181
