### ISSUE TITLE
Speedbrake  Slider Switch working but as the inverse.

### ISSUE THREAD

**Issue by YSIAD-PIR** [heclak/community-a4e-c#452]
**Describe the bug**
Speedbrake Switch is working but is in the opposite direction when using Slider Switch on X56 Throttle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to \input\joystick\default.lua
2. Go to line 90:   See that it is currently listed as  {down = iCommandPlaneAirBrakeOn, up = iCommandPlaneAirBrakeOff,   name = _('Speedbrake Switch - OPEN else CLOSE'), 
3. This Binding, when selected, causes Speedbrake to extend when the switch is moved forward and retract when moved back. This is the opposite to what the real plane and the animation shows in the cockpit
4. I propose adding another binding as listed below:
{down = iCommandPlaneAirBrakeOff, up = iCommandPlaneAirBrakeOn,    name = _('Speedbrake Switch - CLOSE else OPEN'),            category = {_('Throttle Grip'), _('Flight Control')}},  -- Added for X56 Slider, Invert default --																																																																	  

**Expected behaviour**

I expect the Speedbrake to Extend with the X56 Slider Switch is moved back, and I wish the Speedbrakes to Retract when the X56 Slider Switch is moved forward.

**Screenshots**
Not applicable

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.8.16140 Open Beta]
 - A-4E Version [e.g. v2.0 RC3]

**Additional context**
My current workaround is to update my default.lua with the additional Speedbrake binding line.
This is an incredible mod, and if you can't correct or add the suggested binding fix, I will still love and fly this excellent module!

**Comment by callmepartario** [comment]
no problem, i will add a binding for that for next time.
