### ISSUE TITLE
wingman option is not shown in the Radio menu 

### ISSUE THREAD

**Issue by hulu7811** [heclak/community-a4e-c#454]
**Describe the bug**
No wingman option shows in the radio menu after press the  radio menu key "\"

**To Reproduce**
1. Create a aircraft group with 2 A-4, one is player, the other is AI wingman  in the mission editor and set the Radio frequency for AI wingman
2. run the mission,
3. press the menu key "\", the wingman option isn't shown in the radio menu no matter if the wingman frequency is set in the radio.

**Software Information (please complete the following information):**
 - DCS Version: 2.7.8.16140 Open Beta
 - A-4E Version v2.0.0-RC3

**Additional context**
Wingman option is shown in the radio in A-4E v2.0.0-RC2.

**Comment by callmepartario** [comment]
fixed for RC4/Release
