### ISSUE TITLE
Incorrect bank angle scale on all-attitude indicator AN/AJB-3A

### ISSUE THREAD

**Issue by RAFMuffler** [heclak/community-a4e-c#456]
**Describe the bug**
The bank angle scale on all-attitude indicator AN/AJB-3A has incorrect marks. Should be 2 small marks 10°, 20°, and two big marks 30°, 60°. 

**To Reproduce**
1. Launch the mission with A-4E-C
2. Look at the all-attitude indicator bank angle scale

**Expected behavior**
Expect to see a correct bank angle scale.

**Screenshots**
![AJB-3](https://user-images.githubusercontent.com/77843909/144886977-dec915c2-ded8-4533-a280-a9ba7acf74ec.jpg)
![ANAJB-3A all-attitude indicator](https://user-images.githubusercontent.com/77843909/144886981-95fdb69e-5c5b-4aae-a22a-24f6eff6e86e.png)

**Software Information (please complete the following information):**
 - DCS Version:  2.7.8.161406 Open Beta]
 - A-4E Version 2.0.0-RC3

**Additional context**

**Comment by callmepartario** [comment]
![image](https://user-images.githubusercontent.com/17432407/145254584-08deedb3-c93b-44f6-9131-9a5c55398ac9.png)

thanks for the note on this, i've fixed this texture up a bit. the unwrap for the dots on the side is still a nightmare, but nothing i can do about that on my own. the next release will include this fix to the markings on the ADI.
