### ISSUE TITLE
USMC VMA-124 Memphis Marines livery

### ISSUE THREAD

**Issue by rplcnt** [heclak/community-a4e-c#459]
USMC VMA-124 Memphis Marines livery is same as USMC VMA-142 Flying Gators livery

**Screenshots**
![image](https://user-images.githubusercontent.com/95690276/145032579-e57ae29f-6527-438f-a3c6-849f57b6f42e.png)

**Software Information (please complete the following information):**
 - A-4E Version v2.0.0-RC3

**Additional context**
"a4e_usmc_vma124_memphismarines_top" texture should be like this one
![image](https://user-images.githubusercontent.com/95690276/145032912-433ad3fb-e152-4b8e-89b8-fb309575c149.png)

**Comment by callmepartario** [comment]
This texture was overwritten, the LUA is actually okay. I've re-rendered the erroneous texture and updated the binaries.

**Comment by callmepartario** [comment]
fixed; this will be correct in the next release. good spot, thank you.
