### ISSUE TITLE
Nose wheel steering is not longer in the control setup

### ISSUE THREAD

**Issue by esteban-santiago** [heclak/community-a4e-c#460]
When I tried to setup the control for "Nose Wheel steering" I couldn't find it

**To Reproduce**
1. Go to 'Adjust controls'
2. Click on 'Search' to find the "Action"
4. Type 'Nose wheel ...'
5. The option is not loger there and you can't control the pplane in land

**Expected behavior**
I expect to setup that action to control the plane

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.7.8.16140 Open Beta]
 - A-4E 2.0.0 RC3

**Comment by callmepartario** [comment]
duplicate, see #457
