### ISSUE TITLE
crashes to desktop with v2 RC3

### ISSUE THREAD

**Issue by bwanaaa** [heclak/community-a4e-c#462]
**Describe the bug**
DCS crashes to desktop at random times when flying A4E latest , after 15 to 30 minutes of flight Usually after changing views.

**To Reproduce**
after 15 to 30 minutes of flight Usually after changing views.

**Expected behavior**
no crashes

**Software Information (please complete the following information):**
 - DCS Version:latest open beta-new vanilla install also crashes.
 - A-4E Version latest (v2 RC3)

**Additional context**
full description of errors and troubleshooting here:
https://forums.eagle.ru/topic/288055-a4e-c-version-20-rc3/#comment-4845984

Initially log file pointed to two addons causing errors- simshaker and TheWay
[dcs.log-20211215-011040.zip](https://github.com/heclak/community-a4e-c/files/7720507/dcs.log-20211215-011040.zip)

Made vanilla o
[dcs.log-20211215-014229 (1).zip](https://github.com/heclak/community-a4e-c/files/7720526/dcs.log-20211215-014229.1.zip)
pen beta install and still having issues but cause of crash is different.

Get a lot of these lines:
```

2021-12-15 02:11:11.966 ERROR   DX11BACKEND: failed to create structed buffer. Reason: DXGI_ERROR_DEVICE_REMOVED
2021-12-15 02:11:11.966 ERROR   DX11BACKEND: CreateShaderResourceView FAILED. Reason: E_INVALIDARG
2021-12-15 02:11:11.969 ERROR   DX11BACKEND: DX device removed. Reason: 0x887A0006


```

**Comment by callmepartario** [comment]
anyone else experienced this. i've done plenty of 30+ minute flights with no crashes using RC3.  from the error, it looks like it could be a video card driver issue, but if anyone can reproduce that would be helpful. are you flying any particular mission(s) when this happens?

**Comment by bwanaaa** [comment]
Intel 490 motherboard
10700K, 32 gig ram, samsung nvme
Using win 10 pro updated to latest
resizable bar enabled
nvidia 3090 w 497.09 driver, DCH version


DCS runs official modules no sweat, 100 fps on 3840x1600 monitor

**Comment by bwanaaa** [comment]
looks like this is a gpu error unique to rtx cards overclocked. it was last reported with dcs 2.5.6

https://forums.eagle.ru/topic/193221-dcs25324436-crash-error-dx11backend/page/2/

**Comment by callmepartario** [comment]
good deal, sorry the bug is causing you some issues; hopefully ED will see fit to get that addressed before long!
