### ISSUE TITLE
VIRPIL Throttle causes throttle twitch, APC engage difficulty

### ISSUE THREAD

**Issue by johnv2pt0** [heclak/community-a4e-c#464]
**Describe the bug**
APC tries to engage but can't and will eventually kick off (within a matter of seconds, but it varies).  In the cockpit it present itself by the throttle violently twitching.

** Solution **
I'm using a VIRPLE throttle quadrant. Figured out I had to add more of a "Dynamic Deadzone" within the Virple software.  After doing so, the APC works as intended.  Seems the axis is too sensitive for it's own good as far as the A-4 is concerned.  It should also be noted that after adding more of a dynamic deadzone, performance in all other DCS modules was unaffected.

**Comment by callmepartario** [comment]
Recommend to set dynamic deadzone to ~4 in the VPC software (for both throttle channels)

**Comment by Tuuvas** [comment]
I had this issue too and it took me forever to figure out how to get my dynamic deadzone setting saved.  Just to outline this further for anyone else having the same issue:

1. Open VPC Configuration Tools
2. Select and load your VPC Throttle
3. On the top right, ensure you select PRO and not LITE
4. Select the big blue "AXIS" button
5. Move the throttles forward/backward to find the correct Axis Num rows
6. This is the part I didn't know.  Double click the Axis row to modify its settings
7. Set a Dynamic Deadzone for this axis (I set this to 2)
8. Click Save
9. Repeat for the 2nd throttle axis to keep things uniform
10. Click the big green "Save VPC Device" button at the top
![VPC_Throttle_Dynamic_Deadzone](https://user-images.githubusercontent.com/34009225/148614606-f7deb42a-39fb-4dbe-a957-9d5dd9f67d3f.gif)
