### ISSUE TITLE
Add modifier bindings - gamepads - accessibility

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#469]
As discussed in the Discord, it would be great to introduce A-4E-C "Actions" which function exactly like Modifiers.  Ideally this shouldn't be necessary, but unfortunately DCS simply does not play nice when it comes to including modifiers as part of defaults or imported controller profiles.   Having dedicated Actions as their own kind of modifiers would work around this and allow for far better default bindings... especially for limited controllers like console gamepads.  To summarize what was discussed so far:

- Introduce additional "Actions" which function like DCS' built-in modifiers
- Provide an optimized gamepad layout for console controller users (Tuuvas+Dev to work on this - see https://imgur.com/a/0y4YsYp for an idea of what I'll be putting together)
- Look into adding "Mouse X/Y" movement as well as "Left/Right Click" as module-specific actions.
    - Note: Mouse clicks already exist in UI Layer with "as left mouse button" and "as right mouse button", but would collide with any Module-specific bindings.
    - I'm not sure how feasible this would be?

**Comment by callmepartario** [comment]
this is an intriguing idea, let's keep an open dialogue on this on discord once the best binding schemes are decided upon.

**Comment by Tuuvas** [comment]
Here's my first take on mapping the A-4E-C controls to a gamepad layout.  With the A-4E-C being a relatively simple aircraft controls-wise, I ended up with a bunch of unused buttons... specifically under the LB/L1 modifier.  Because of this, I chose to bind functions which would prove to be useful in a pinch or just nice QoL bindings.  For example:

- QoL
  - Master Arm ON/OFF
  - Gun READY/Safe
  - Weapon Function Selector CW/CCW
- In a Pinch
  - Release Select CW/CCW and Store Release Handle
  - Radar Antenna Tilt CW/CCW (is this really necessary?)
  - Gunsight Elevation INC/DEC

Other bindings might seem unnecessary (ex. Landing Gear Up/Down, Canopy, etc), but I have those bound since I had the space, and this keeps the bindings consistent with all my other layouts seen here: https://imgur.com/a/0y4YsYp

![image](https://user-images.githubusercontent.com/34009225/148014198-4e5397c4-ac0f-4114-8510-69effe10ab47.png)

**Comment by callmepartario** [comment]
see also #475 for additional accomodations related to this

**Comment by Tuuvas** [comment]
Just adding the latest version of my controls layout for the A-4E-C.  I've included the upcoming single-axis brake and replaced the redundant Left/Right Dpad brake with actions I found more useful in practice.

![DCSWorld_A-4E-C](https://user-images.githubusercontent.com/34009225/151095024-691b8c22-4d0f-4651-9860-085812067b43.png)

**Comment by callmepartario** [comment]
looks like mouse vert / horiz is inverted on this diagram. i will get the rest updated into my copy of the kneeboard manual.

**Comment by callmepartario** [comment]
![Screen Shot 2022-01-26 at 9 50 56 AM](https://user-images.githubusercontent.com/17432407/151185814-f1711a9a-338d-444d-afe2-4560210bb7bf.png)

**Comment by Tuuvas** [comment]
/facepalm There's always something I forget lol.  I've updated the above layout picture with the correct Mouse Vertical/Horizontal positions.

Regarding the faded labels for inherited controls, that's a great addition but unfortunately won't work for the Left && Right category.  If the Left || Right categories have something bound to that button/axis, then either of those will be the fallback instead.  In our case, Left && Right's fallback "Rudder Left" and "Rudder Right" will instead be Zoom In/Out due to the Left Modifier binding.  Why Left Modifier in particular?  If I had to guess: "Left Modifier = Joy Button 5, Right Modifier = Joy Button 6, therefore 5 has priority over 6."  It's dumb, I know :(

**Comment by Tuuvas** [comment]
As for a baseline of curves/deadzones/etc, I'll have to do some experimenting with a few friends that also have gamepad controllers.  For deadzone, it'll all depend on the age of their thumbsticks.. the wear and tear.. whether they've calibrated or not.. etc.  For me, I use a deadzone of 5 but that's after windows calibrating for the actual physical center of the stick.  I imagine most players wouldn't do this even though they really should.

Let me get back to you regarding recommended Axis Tune settings.

**Comment by callmepartario** [comment]
a good implementation for this feature is in the develop branch now, would love to see some testing on it from anyone interested. be sure to update your binaries to get the layout diagram in the kneeboard. thanks to tuuvas for all their help so far on this one.

**Comment by callmepartario** [comment]
closing this, as it's been implented. any new issues should have a new issue filed.
