### ISSUE TITLE
Kneeboard errors, typos, todos

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#470]
changes made in master file:
- Removed SPOILERS from Case III Recovery procedure
- Wheel Brake Left - ON else OFF default input changed to `LCTRL+W`
- Emergency Stores Release Handle default input changed to `LCTRL+J`
- Fixed missing `L` in `LCTRL` in a few places
- Removed  `(Hold)` from the Fuel Dump Switch (default input is now a 3-position cycle)
- Removed `(Hold)` from the Drop Tank Pressurization Switch (default input is now a 3-position cycle)
- Removed the Fuel Transfer Switch entry for setting up wing tank bypass. You don't need to do this to fill empty tanks, and the niche case where you'd want this in BYPASS might be causing more confusion than it solves for users unfamiliar with the detail of the fuel system provided in the NATOPS. However, its binding of 'LALT+D' remains, making it ergonomically easy to manage fuel should the wing tank begin leaking.
- Fixed Ground Radar TC instructions, Radar AoA compensation switch is now ON

changes to make in master file:
- complete gamepad layout entries
- document new gun behavior established by #503 and #263

**Comment by Cactus8593** [comment]
In the Manual (page 5-2) Item No. 13. should read All OFF (
A. CVN Day,,,ALL OFF...Ready for cat launch 'Smash' Lights (Anti-Collusion) ON
B. CVN Night,,,ALL OFF...Ready for Cat launch, 'X'mas Tree' (All ON STDY/BRT) with the caveat of no Landing light use

CVN day is not mentioned in any manual, there have been mention in air wing SOP's within the CCZ (10nm).
Light or hand signals are mentioned in the NATOPS for ready to launch from the catapult...or mentions them to NOT use them if there is a problem.

**Comment by Cactus8593** [comment]
In the Manual (page 4-3) in the box labeled FINAL...Item No. 4 does not pertain to carrier landings, recommend removal.

**Comment by callmepartario** [comment]
closing this for the time being, will re-open a new ticket after 2.1.0 is out.
