### ISSUE TITLE
Unlimited fuel and immortal options in ME are unsupported

### ISSUE THREAD

**Issue by mercator650** [heclak/community-a4e-c#472]
First of all: What a great mod! It is so much fun to fly the Scooter! 🙂 Thanks to all the developers for their effort to make this aircraft such a gem!

Maybe I'm doing something wrong, but it seems the "unlimited fuel option" in the ME doesn't work with the A4E. Are their any suggestions, what may cause this problem/bug?

Thanks for any help!

 - DCS 2.7.9.18080 Open Beta
 - A-4E Version 2.0
 - Terrain: Persian Gulf

**Comment by nima3333** [comment]
Hi, I would like to take this one as my first issue for the project. Working on it now.

**Comment by callmepartario** [comment]
fixed in https://github.com/heclak/community-a4e-c/pull/514

**Comment by callmepartario** [comment]
immortal mode added in https://github.com/heclak/community-a4e-c/pull/516
