### ISSUE TITLE
move unwrap locale for speedbrake hydraulics

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#473]
- A-4E Version v2.0

the unwrap locale for the speedbrake hydraulics overlaps with some landing gear and other items. this creates some issues and is most noticeable in application of the RoughMets. these hydraulics probably ought be completely unpainted and metallic, which the unwrap doesn't allow for at the moment.

the current unwrap location is highlighted in red in the following screenshot. i recommend moving this to a shared space between all liveries (e.g. 'a4e_ext_front' or 'a4e_ext_wheels_bays').

![image](https://user-images.githubusercontent.com/17432407/148264496-2a5c7a5d-2c9d-4abf-9642-0f6d9a4862f1.png)

**Comment by Merker6** [comment]
Will adjust during my upcoming 3d model adjustments

**Comment by Merker6** [comment]
Discrepancies noted for the unwrap destination textures in 3ds. a4e_ext_wheels_bays is not currently being used in 3ds

Further work required. Part identifiers for the hydraulics are "AFactu"1-4. Currently assigned to the "BottomUV" material, child of "Fuselage"

**Comment by Merker6** [comment]
Moved to a4r_ext_wheels_bays.dds, see general location below. Template will be included in follow-up

![image](https://github.com/heclak/community-a4e-c/assets/16724430/01bd9dc4-b117-4b48-90fa-d27c1c8d5093)
