### ISSUE TITLE
Add momentary switch-friendly action bindings for cockpit switches

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#474]
There are a few places where binding cockpit switches do not play well with physical two-direction momentary switches.  There could be more, but so far I've found:

- Drop Tank Pressurization Switch - DOWN/FLIGHT REFUEL else PRESS
- Drop Tank Pressurization Switch - UP/DROP TANKS else PRESS
- Guns Charging Switch - READY else SAFE
- Master Armament Switch - ON else OFF

Because these are "else" bindings, these switches have to be held in place when using momentary switches.  It would be nice to have an alternative that will allow momentary switches to work as well:

- Drop Tank Pressurization Switch - DOWN/FLIGHT REFUEL
- Drop Tank Pressurization Switch - UP/DROP TANKS
- Drop Tank Pressurization Switch - PRESS
- Guns Charging Switch - READY
- Guns Charging Switch - SAFE
    - Note: READY/SAFE toggle exists, but this isn't the same as dedicated READY and SAFE positions
- Master Armament Switch - ON
- Master Armament Switch - OFF
    - Note: ON/OFF toggle exists, but this isn't the same as dedicated ON and OFF positions

There could be other switches which could use this love, but I'll need to continue using the module to find them.  Also, probably worth mentioning that this idea already exists for other 2 and 3 position switches like:
![image](https://user-images.githubusercontent.com/34009225/148286529-7c59e574-b8b5-4483-b770-bce99e150f94.png)

**Comment by callmepartario** [comment]
this would be pretty easy to accomplish; all those ELSE bindings can just shunted out into pairs to this end.

**Comment by callmepartario** [comment]
you should be able to sub that file in from git if you wish to make use of these immediately. 
added: https://github.com/heclak/community-a4e-c/commit/6b5fbb9026b2b6fc262625e04929e796b0262d15

**Comment by callmepartario** [comment]
note: i did not do the drop tank switch since that one should behave like other must-hold items: the switch is spring-loaded and returns to the zero position when not explicitly held down by the pilot.

**Comment by Tuuvas** [comment]
> note: i did not do the drop tank switch since that one should behave like other must-hold items: the switch is spring-loaded and returns to the zero position when not explicitly held down by the pilot.

Huh interesting, the funny part is that switch was the original reason I raised this feature request lol. Now I'm super curious how pilots managed to refuel without touching the throttle if their left hand was preoccupied with holding that switch
