### ISSUE TITLE
Add single-axis wheelbrakes and dual-axis rudder

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#475]
I originally raised this as part of the modifier action feature request, but it's best to tackle this as a separate issue.

A lot of people are finding it difficult to steer the A-4E-C while on the ground due to the lack of NWS.  The removal of NWS is completely understandable and it should NOT be reintroduced imo... but there could be a fairly easy way to work around this  with a new axis bind.  Plus it would benefit players with more limited controller devices:
- console gamepads
- rudders w/o toe brakes
- twist sticks
![image](https://user-images.githubusercontent.com/34009225/148301905-c28ef0a4-248b-41f8-80f2-34ee4913088d.png)

As shown above, introducing a single Rudder-like axis for Left/Right Wheel Brakes would allow users with only a single, centering axis to still control the plane's nose direction.  At the press or release of a modifier, the player could easily switch between either Rudder control or Left/Right Wheel Brake control.  For instance:

1. Land on a runway and use twist stick to control nose with Rudder when at speed
2. Slow to taxi speed, and use modifier + same twist stick to control nose with Wheel Brake Left/Right

The nice thing about this is the player doesn't have to rewire their muscle-memory just for ground steering since Rudder effectively does the same thing... but with air speed.  They just need to remember to press the modifier.

**Comment by Tuuvas** [comment]
@callmepartario As discussed, we should also add individual "Rudder Left" and "Rudder Right" axes to accommodate plug-and-play with PS4 and PS5 gamepads.  This is because their L2 and R2 axes are individual and do not share a single axis.  See below:
![image](https://user-images.githubusercontent.com/34009225/149376220-a3fe66c0-bb3b-45b7-ab2f-30ed15c940ec.png)

**Comment by Tuuvas** [comment]
@callmepartario We should also include Zoom Axis separation to Zoom Out and Zoom In if we intend to keep bindings similar between the controller types

**Comment by callmepartario** [comment]
single-axis wheelbrake option is in the dev branch now, still renaming a few items, but we'll circle back on the dual-axis rudder

**Comment by callmepartario** [comment]
this is well implemented in the develop branch, documented in the readme, so i'm clearing the deck on the issue. thanks, everyone! any further questions on this issue can be made on #469
