### ISSUE TITLE
Installing v2.0.0 cause Bulker Handy Wind to lose textures

### ISSUE THREAD

**Issue by Arendellecita** [heclak/community-a4e-c#476]
**Describe the bug**
After installing a4ec v2.0.0, bulker Handy Wind is missing textures.

**To Reproduce**
1. Create a mission with a bulker Handy Wind, make sure the textures are displayed correctly;
2. Install A4EC v2.0.0;
3. Open the mission again, the textures of Handy Wind is missing(showing green “camouflage”);
4. Uninstall A4EC;
5. Open the mission, the textures are back to normal.

**Expected behavior**
Described above

**Screenshots**
Not applicable

**Software Information (please complete the following information):**
 - DCS Version: latest open beta
 - A-4E Version v2.0.0

**Additional context**
None

**Comment by callmepartario** [comment]
i am unable to reproduce this error, the bulker is in tact with the A-4E-C installed. anyone else care to weigh in on this?

DCS 2.7.9.1080 open beta
A-4E-C 2.0.0

**Comment by Arendellecita** [comment]
Sorry, I tested again, the issue ceased to appear. Sorry for the confusion.

**Comment by callmepartario** [comment]
no worries, thanks for the confirmation, glad we were able to resolve this one through rigorous testing!
