### ISSUE TITLE
Unwrap launch hook in wheel well

### ISSUE THREAD

**Issue by Cactus8593** [heclak/community-a4e-c#478]
I'd like to request this feature to get painted please the Launch hook within the wheel well...

![Screenshot 2022-01-06 171105](https://user-images.githubusercontent.com/64085492/148466188-e05e7969-8d14-4903-badd-e9c773e362a4.png)
.

Thanks
Cactus

**Comment by Merker6** [comment]
Will get started on this once I'm back at home next week (6/12). Will be addressing numerous 3d issues at once

**Comment by Merker6** [comment]
Unwrapped, will be included in unwrap bundle. Placed in the top right of the bottom external map
