### ISSUE TITLE
Ground roll at IDLE when at 20% fuel (no loadout, no flares, no chaff, etc)

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#483]
When the A-4E-C is at IDLE power, having little weight on the plane (ie. 20% fuel and nothing else) causes the aircraft to roll.  Unsure if this is intentional, so more research will likely be needed to see if this is legit behavior.  Test steps below:

1. Caucasus Cold Start Mission
2. Simply startup the engine like normal
3. Rearm Refuel and take fuel down to 20%
4. Initially insignificant roll requiring speed time up to notice
5. While crew is at rearming step, roll is far more significant, breaking rearm and classic "HEY! WAT'RE YA DOIN'"

**Comment by callmepartario** [comment]
tested this and was able to reproduce, but i think we can chalk this up to it just being physics, baby, and this is a really unconventional loadout request.
