### ISSUE TITLE
Incompatibility with DCS versions below 2.7.9.18080

### ISSUE THREAD

**Issue by Stilgar75** [heclak/community-a4e-c#485]
Hi, i have an old installation in windows 7 of dcs 2.5.6, is possible to play the a4 mod in this version of DCS?

I tried to installed the mod and in the mission editor  i can place the a4, but when i start to fly the mission, the mission start with the external view, and i cant control the plane! like i havent selected the plane to be playable.

thanks for help

**Comment by callmepartario** [comment]
The A-4E-C requires at least DCS version 2.7.9.1080 to function. I will update the FAQ with this information on discord and leave this issue open until then.

**Comment by callmepartario** [comment]
as this is added to base documentation, closing this issue.
