### ISSUE TITLE
Throttle position continuous and incremental input tuning

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#486]
When the button for throttle up/down is pressed (default: Num+ and Num-), the throttle in the A-4E-C appears to move significantly more than several other DCS modules.  The below comparison was made using a macro which presses throttle up/down for 100ms with a 100ms delay between presses.
![Throttle_Button_100ms](https://user-images.githubusercontent.com/34009225/148723862-be523028-be0a-4e76-9850-165d13ba13e7.gif)

It's possible the A-4E's throttle just doesn't have as much throw as other aircraft.  Hopefully that's not actually the case as currently it feels nearly impossible to manually land back at the carrier due to sensitive throttle inputs on button press.

**Comment by callmepartario** [comment]
this is a really useful visualisation. i tried to time it so i could manage start-up and most operation (it seemed to me you're really not sitting in the middle very much in operation), but getting a more useful gradient should be on order.

**Comment by Tuuvas** [comment]
I will say that being able to go to full/idle power quickly was surprisingly useful for things like carrier traps.  This helps immensely in preventing the aircraft from going overboard after a successful wire catch.

If it's at all possible, perhaps you could explore something like:

- Button press < 150ms = slower axis movement
- Button press > 150ms = faster axis movement
