### ISSUE TITLE
fix Engine Control Panel inputs

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#487]
The Drop Tank Pressurization switch is a spring-loaded switch with the following options:
- Up: OFF
- Center: PRESS
- Down: FLIGHT REFUEL

Since this is a spring-loaded switch, it must be held in either the UP or DOWN position, otherwise it will return to CENTER.   This can be seen happening when using LCtrl + D for FLIGHT REFUEL, but this does NOT happen when clicking the switch.  When clicking, the switch remains in the desired position without need to hold click.

Note: Changing **default_3_position_tumb** to **springloaded_3_pos_tumb** doesn't seem to work as the aircraft can still refuel despite the switch returning to center.  I'm not sure what args need to be changed to correct this.

**Comment by 08jne01** [comment]
Not sure where you found it should be spring loaded is that what it says in the NATOPs? Also you misunderstand this switch's function. Off stops the ext tanks from beibg pressurised ie no transfer from ext tank to wing and FLIGHT REFUEL fills the tanks when mid air refueling but it will not transfer from ext to wing in this condition as it does not pressurise the tanks.

**Comment by Tuuvas** [comment]
> Not sure where you found it should be spring loaded is that what it says in the NATOPs? Also you misunderstand this switch's function. Off stops the ext tanks from beibg pressurised ie no transfer from ext tank to wing and FLIGHT REFUEL fills the tanks when mid air refueling but it will not transfer from ext to wing in this condition as it does not pressurise the tanks.

This is based on @callmepartario's comment on https://github.com/heclak/community-a4e-c/issues/474:
> note: i did not do the drop tank switch since that one should behave like other must-hold items: the switch is spring-loaded and returns to the zero position when not explicitly held down by the pilot.

I tried looking into this and couldn't find anything to refute it.  At the very least, considering LCtrl + D is momentary, I'd expect clicking to also be momentary.

**Comment by 08jne01** [comment]
yea that doesn't seem right I'll ask plusnine.

**Comment by callmepartario** [comment]
if we're agreed that this switch can be set-it-and-forget it (and is not spring-loaded), i'll add those momentary bindings, quick snap!

**Comment by Tuuvas** [comment]
This is pretty minor imo, but if you go the set-it-and-forget it route, then kneeboard page 4-4 for Air Refueling _might_ need to be updated to remove "(Hold)"
![image](https://user-images.githubusercontent.com/34009225/148847023-f20bd099-741b-49b1-9689-45432092ab34.png)

**Comment by callmepartario** [comment]
after updating keybinds, observe the above change to the kneeboard

**Comment by callmepartario** [comment]
fixed as of https://github.com/heclak/community-a4e-c/commit/e7c8d235fd0d688bf465c7715d4bdac3a72023f6
