### ISSUE TITLE
Input bindings are unable to reduce TACAN volume to 0

### ISSUE THREAD

**Issue by Bear21Github** [heclak/community-a4e-c#490]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by callmepartario** [comment]
Got it, i see this occurring now. I'll revisit this and make the control finer for the volume in general so there are more good options for low-volume TACAN at the bottom of the dial.

**Comment by callmepartario** [comment]
Fixed in https://github.com/heclak/community-a4e-c/commit/28846f051f75898509fc56d45cbcadc128033b20
