### ISSUE TITLE
CP-741 locks somewhere around 10mils, should be 0mils

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#492]
As discussed/observed Jan 11 2021, the CP-741 appears to lock just below 0mils on the gunsight.  After some testing, it seems the actual location of the lock is somewhere around 10mils.

1. Launch Caucasus Bomb Trucking mission
2. Setup the following items:
    - Master Arm: On
    - Weapon Function: COMPUTER
    - Radar: A/G
    - Radar AOA Compensation: Off
    - AWRS Mode: Single, Step or Ripple as desired
    - Qty Select: 0
    - Weapon Select: any mk82 station
    - Gunsight: 0mils
3. Initiate dive on a target (ie. 30° dive, 10,000ft, 250knots)
4. Track target with gunsight ^ center and hold for 2 to 4 seconds
5. Press and hold pickle
6. Initiate a 2G pull up and wait for bomb release
7. Press F6 to observe mk82 in flight
- Expected Results: mk82 should reach longitudinal target position (lateral may be off due to pilot error)
- Actual Results: mk82 consistently lands short, as if 10mils was used on gunsight

**Comment by callmepartario** [comment]
this one's been fixed in dev, thanks nelson.
