### ISSUE TITLE
can't take control of aircraft (enter cockpit)

### ISSUE THREAD

**Issue by Pallino365** [heclak/community-a4e-c#493]
Although I can cretae missions with A4-C selected as player, at mission launch unit apperas as AI only, no cockpit view, so I cannot fly it.
latest DCS OB 2.7.9.18080, fresh install, my PC is new with i7 32gb ram and RTX 3080. 
All other planes fly regularly, with highest settings, no issue. I have also removed all mods and kept only the A4 in saved games>DCS OB>Mods>aircraft folder, no change. I also re nstalled the A4 mod following exactly the instructions provided on this github page, but no change. Any idea why this is happening, and if there's any solution to solve this?
PS I have latest DCS OB running also on my other laptop, and I have no issues there, A4 works perfectly both as player and AI.
Thanks

**Comment by callmepartario** [comment]
sounds like you need to review the troubleshooting tips at https://08jne01.github.io/community-a4e-c/#installation-troubleshooting -- most users who have this issue just need to install the Microsoft C++ libraries linked thre.

**Comment by waseemchand** [comment]
If you can load a mission, but can’t take control of the A-4E-C, ensure you have installed [Microsoft’s Visual Studio 2015, 2017 and 2019 Redistributable libraries](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0). Restart your computer after installation of the appropriate libraries. For most users, this is vc_redist.x64.exe

This worked for me.
