### ISSUE TITLE
Keybind Not Working: AN/APG-53A Radar Antenna Tilt - Slew

### ISSUE THREAD

**Issue by docsconz** [heclak/community-a4e-c#499]
**Describe the bug**
The axis keybind 'AN/APG-53A Radar Antenna Tilt - Slew' does not seem to manipulate the in-cockpit radar antenna control knob.  In the Options > Controls page, the keybind is available and bindable and manipulating the IRL axis appears to change the value (the white bar grows to the right or left), but in the cockpit manipulating the IRL axis has no effect. 

**To Reproduce**
1. Go to Options > Controls > Axis Commands
2. Bind 'AN/APG-53A Radar Antenna Tilt - Slew' to IRL axis of choice
3. Verify axis is functioning correctly but manipulating IRL axis and seeing the white bar grow to the right or left
4. Back on main menu, choose Instant Action > Caucauses > A-4E-C > Cold Start
5. Manipulate IRL axis - no result in cockpit
6. Verify radar antenna tilt knob can be moved in this state by clicking and dragging with the mouse

**Expected behavior**
Radar antenna control knob should respond to IRL axis manipulation.

**Software Information (please complete the following information):**
 - DCS Version: DCS Open Beta 2.7.9.18080
 - A-4E Version 2.0

**Additional context**

**Comment by callmepartario** [comment]
this one's fixed in dev.
