### ISSUE TITLE
Not able to select the B version of the Shrike

### ISSUE THREAD

**Issue by LitlHart** [heclak/community-a4e-c#500]
**Describe the bug**
In the Payloads Menu there are weapon loadouts that indicate that there is a B version of the shrike. AGM-45B. When I try and find the B version it is not there.

**To Reproduce**
1. Go to 'Payload menu'
2. Click on 'Select weapon icon'
3. Scroll down to 'AG Missiles'
4. No AGM-45B

**Expected behavior**
No B version of the Shrike 

**Screenshots**

![A-4E mission payloads](https://user-images.githubusercontent.com/97925308/149855036-d5f8e008-2f2f-4325-a3e1-66bccf76ee5f.png)

![No shrike B version is available](https://user-images.githubusercontent.com/97925308/149855200-b817db8c-b2c6-4e55-bbae-71f7250a18c0.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.9.18080 Open Beta]
 - A-4E Version [e.g. v2.0]

**Additional context**

**Comment by callmepartario** [comment]
the option for the B shrike was removed many versions ago. if you have this loadout listed, it's probably because you saved yourself it before its removal, as it's no longer part of the module. i suggest removing your misleading loadout. the A is the only approved shrike for use with the A-4E-C.

**Comment by LitlHart** [comment]
Sorry about the misunderstanding. However I have never added those to the
payload menu so I don't know why they are listed as an option. I will
delete them. Thanks for all you do. I really love this mod.
