### ISSUE TITLE
Develop Branch: APC and Trim do not work well together

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#502]
On the Develop branch, there seems to be an issue where APC and trim are unable to work well with each other.  For instance, if we get into CASE I configuration:

1. Load "Caucasus A-4E-C Case I.miz"
2. APC Standby
3. 250 knts (note this will drop significantly as below is "downwind" configuration) 
4. Flaps Down
5. Speedbrake Open
6.  APC Engaged (assuming warmed up already)
7. Trim aircraft for on-speed AOA

On Master branch, we need roughly 6 nose up trim to maintain on-speed AOA and a controllable descent rate:
![image](https://user-images.githubusercontent.com/34009225/150203223-e256c318-2d19-4b6c-ace4-f06a09ec031c.png)

On Develop branch, we need more than the trim can actually give us:
![image](https://user-images.githubusercontent.com/34009225/150203827-53f50640-25db-4e5f-9232-2690d91d5fd7.png)

**Comment by callmepartario** [comment]
good time to look at #484

**Comment by 08jne01** [comment]
Hi tuuvas, the develop branch is super unstable atm for pitch stability, this is fixed in my local build. I need to commit but I must renew my open source licence first.

**Comment by Tuuvas** [comment]
@08jne01 No worries, I'll keep an eye out for the commit whenever it happens and I'll test for ya
