### ISSUE TITLE
Drop Tank Pressurization Switch disables refueling once set to FLIGHT REFUEL

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#506]
from Wiseman#8167 on Discord:

Here is a video that I captured 1 hour ago. In the first part the video shows a normal refueling without touching the Drop Tank Pressurization Switch (it is set to PRESS). As you can see the needle of the fuel gauge is rising as intented. After that I disconnected (from 1:35 min.), set the Drop Tank Pressurization Switch to FLIGHT REFUEL position and then back to PRESS. I reconnected, but now it was impossible to get fuel from the tanker, no matter in which position I set the Drop Tank Pressurization Switch. I tried to set to OFF, no fuel flow, I set it back to PRESS, no fuel flow. It seems, that as soon you set the Drop Tank Pressurization Switch to FLIGHT REFUEL, even for just a second, refueling isn't possible anymore after that.

Video: https://www.youtube.com/watch?v=KeJTIOqUVC0

**Comment by nima3333** [comment]
Fixed in e8181e098 (https://github.com/heclak/community-a4e-c/commit/e8181e098a5bc2ca4e67276921ef3c687aa8c718)
