### ISSUE TITLE
AI Slats

### ISSUE THREAD

**Issue by WingTipVortice** [heclak/community-a4e-c#507]
**Describe the bug**
By default the slats on the AI are deployed even at cruise conditions. Double checked the AOA conditions in the ctrl+y bar, its 3.8 units.
Also noticed some of the cockpit textures are missing in the exterior model

**To Reproduce**
1. Set AI to 15000ft @ 300knots TAS

**Expected behavior**
Expect slats to be retracted

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.10 Open Beta]
 - A-4E Version [e.g. v2]

**Additional context**
![DCS 2022-01-28 09-04-00](https://user-images.githubusercontent.com/75806807/151590557-a49dc5c0-fda2-41e4-83e2-4ff98c1d8fa9.png)

**Comment by callmepartario** [comment]
folding in with #544
