### ISSUE TITLE
Add in-game manual using DCS Manual ESC Menu feature

### ISSUE THREAD

**Issue by asherao** [heclak/community-a4e-c#508]
**Describe the solution you'd like**
User presses escape. User selects "Manual". User sees manual for A4.

**Describe alternatives you've considered**
No in-game manual. Not optimal for VR users.
Kneeboard manual.  Not optimal for some VR users. Requires multiple page flipping if you need to get to pages behind the kneeboard manual.

**Additional context**

- Must add `set_manual_path('A-4E-C', current_mod_path .. '/Docs/manual')` to the A-4E-C/entry.lua file. I have added it right before `plugin_done()`. 

- Install the attached zip to the A-4E-C folder. It contains a demo of the feature, to include some guidelines for making the manual. Tested and working.

[Docs.zip](https://github.com/heclak/community-a4e-c/files/7963235/Docs.zip)

![image manual page001](https://user-images.githubusercontent.com/15984377/151652543-cb785818-a460-4a5c-9feb-5f5be593c122.png)

**Comment by asherao** [comment]
In game manual display is not affected by "Messages font scale" or "Scale GUI".

**Comment by asherao** [comment]
Other aircraft with in game manuals are:

- Mi-8MT
- P-51D
- F-86

Transparency in the PNG is preserved. 
![image](https://user-images.githubusercontent.com/15984377/151657773-c6039830-6f5d-4578-b708-70c7f583a08b.png)

![image](https://user-images.githubusercontent.com/15984377/151657925-2d425f29-4707-4acd-b3b9-ddab119e24e6.png)

**Comment by callmepartario** [comment]
thanks, i will take a look at this and see what can be put together. looks like text markup is done in lua and images can be added, but i'll see exactly what the deal with that is.

**Comment by callmepartario** [comment]
gonna take a pass on implementing this, it's too redundant for feautures we're already supporting.
