### ISSUE TITLE
update loading screen and mission briefing screen for 4k screens

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#512]
consult with @Tuuvas or other good reliable screenshot folks to make this happen

**Comment by Tuuvas** [comment]
Below are some resolutions I found being used in the Main Menu, Loading Screen, Briefing Screen, and.... DVD cover? Huh. 
 Anyways:

- DCS Main Menu Resolutions:
    - 1920 x 1080
    - 2100 x 1076
    - 2560 x 2048
    - 4096 x 4096
- Loading Screen Resolutions:
    - 2402 x 1080 + Letterbox: 2402 x 308 (F-14)
    - 2560 x 2048 + Letterbox: 2560 x 368 (F/A-18C)
    - 2560 x 2048 + Letterbox: 2560 x 368 (AV-8B)
    - 4096 x 4096 + Letterbox: 4096 x 600 (A-10C II)
- Briefing Map Resolutions:
    - 512 x 512
- DVD Cover Resolutions:
    - 105 x 150

**Comment by Tuuvas** [comment]
Here's my attempts at the 3 pics:

DCS Main Menu:
![A-4E_In_the_Groove](https://user-images.githubusercontent.com/34009225/151690608-9f7f8977-5520-4ebd-9ff9-d5e624e849a5.png)

Load Screen + Letterbox:
![A-4E_Wire_HeadOn](https://user-images.githubusercontent.com/34009225/151690615-06cbb988-c052-4d80-9efa-c1ef6fc885e2.png)

Briefing Screen:
![A-4E_Hot_Pickle](https://user-images.githubusercontent.com/34009225/151690627-7a7baca3-0698-427e-a787-5302711192d4.png)

Hopefully others can use these as inspiration for getting their own screenshots!

**Comment by ImJustDubzzz** [comment]
![a4 main screen](https://user-images.githubusercontent.com/98683874/151691221-0068d069-3bc9-46ad-bb85-a06a2e7c9e63.png)

my submission for the main menu.
