### ISSUE TITLE
Ground power remains attached in flight if you don't turn it off (And they don't communicate to you that it's still connected)

### ISSUE THREAD

**Issue by HarryNoakes** [heclak/community-a4e-c#518]
Hi Team, I have found a small issue with the module regarding ground power.
**Describe the bug**
If you connect ground power and fly off, it remains attached, even in flight.

Secondly if you close the canopy the ground crew does not communicate it is still attached.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect ground power, Re-arm and refuel.
2. Start taxi, the ground power unit should come with you.

**Expected behaviour**
A warning from Ground control + Unit auto disconnecting?

**Screenshots**
![unknown](https://user-images.githubusercontent.com/57322293/152552703-e2a1dac9-d79b-4252-9647-acace77dc27d.png)

**Software Information (please complete the following information):**
 - DCS 2.7.10.18996 Open beta
 - A-4E Version v2.0.0

**Additional context**

**Comment by callmepartario** [comment]
duplicate, see #359 

as for the radio, this is a known limitation, not a bug. the included manual denotes ground crew operations that require the canopy to be open.
