### ISSUE TITLE
Add Option: Disable NVG Use - for mission designers 

### ISSUE THREAD

**Issue by NatiroHadashi** [heclak/community-a4e-c#519]
Suggest addition of option to **disable NVG use** by mission designers, similar to ability to disable RWR (ECM Panel)

Example Use: Mission set in 1968, night. No NVG so the pilots learn to use the ground radar you spent so much time on.

**Comment by 08jne01** [comment]
Yes this is something we were planning on doing. Thanks for submitting the issue.
