### ISSUE TITLE
Cold start throttle stuck off

### ISSUE THREAD

**Issue by Hoiitsme** [heclak/community-a4e-c#520]
new install A-4E-C 2.0.0
inputs deleted
DCS 2.7.10.19402
map: Marianas

steps:
ground power on
ignition on
rpm ramp to 10%

throttle not movable to IGN or IDLE. (using mouse or button assigned)
throttle makes sound but is not moved and engine is not starting

**Comment by callmepartario** [comment]
ensure your throttle is fully in the 0 position when adjusting the lock step - you can see this on the controls indicator. even if you're a keyboard user, attempting to move the throttle position up will lock you out of adjusting the step.

**Comment by callmepartario** [comment]
assuming user error and closing this issue.
