### ISSUE TITLE
MIL-STD-2525 ICON shows F instead of A

### ISSUE THREAD

**Issue by NatiroHadashi** [heclak/community-a4e-c#522]
DCS Editor and map shows the MIL-STD-2525 icon as "F", should be changed to "A"

**Expected behavior**
Should display "A" (Attacker) rather than the current "F" (Fighter) designation.

 - DCS Version:  DCS 2.7.10.19473
 - A-4E Version 2.0.0
 
 
 
 - Image Capture below. Displays A-4E as Fighter type aircraft. 
 
 
![Capture_12](https://user-images.githubusercontent.com/79599393/153118534-7a5d525a-00d2-46e7-aae6-763a7be220f2.JPG)

**Comment by callmepartario** [comment]
thanks, fixed for 2.0.1

**Comment by NatiroHadashi** [comment]
This issue persists. Icon still shows "F" instead of "A"
