### ISSUE TITLE
Fuel amounts are too much for instant action dogfights

### ISSUE THREAD

**Issue by jinchoung** [heclak/community-a4e-c#527]
the fuel level actually seems inconsistent from game to game but in my first few outings for dog fighting, i noticed that the jet handles waaaaay worse than it does when i just take off from the ground and for a long time, i struggled to figure out why that is. i believe that it is because of the amount of fuel you're loaded up with at the beginning of the match. the meter goes to 6 but i've started matches with 5 (hundred? thousand?) lbs of fuel... and i believe that's what's causing the controls to feel so sluggish.

it's a huge hindrance to a beginning player. 1500 (?) lbs of fuel should be fine for most matches.

**Comment by callmepartario** [comment]
give a look to see if reloading the mission is what's tripping you up; this sounds like it could be #236
