### ISSUE TITLE
Nose Wheel steering

### ISSUE THREAD

**Issue by dingo007** [heclak/community-a4e-c#528]
I am unable to find a key binding for Nose wheel steering.  When I go to steer aircraft unable to steer with rudder. I am Running 
DCS 2.7 and A-4-E/C version 2.0.1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by callmepartario** [comment]
there is no nosewheel steering in the a-4e-c. use the differential braking system. additional information is provided in the kneeboard under the TAXI and CONTROLS INDICATOR pages.
