### ISSUE TITLE
Add single-inputs for TACAN mode switch (OFF - REC - T/R - A/A)

### ISSUE THREAD

**Issue by Sepeto73** [heclak/community-a4e-c#530]
Most selectors on this amazing mod have individual commands (Radio modes, radar modes, weapons, etc), please consider creating four new commands so we can assign to every TACAN mode.

- OFF
- REC
- T/R
- A/A

Thanks in advance.

**Comment by callmepartario** [comment]
added in https://github.com/heclak/community-a4e-c/commit/c8b879c3e18449203a656f67742296bb0c253ed1

you can go ahead and copy these into your input luas if you want to get a jump-start.

**Comment by Sepeto73** [comment]
Worked perfect!!! I already checked, TACAN modes all worked perfectly. Thank you very much.

**Comment by callmepartario** [comment]
these are well in hand now, closing this issue!
