### ISSUE TITLE
Some A-4E skins are missing textures and some work fine.

### ISSUE THREAD

**Issue by Headears** [heclak/community-a4e-c#532]
**Describe the bug**
After i followed the directions to download the A-4 and loaded it in the game, some of the skins are missing textures and some are not. There seems to be no rhyme or reason to why some are and some are not loading into the game. All of the cockpit textures work even on the skins the are missing textures.

**To Reproduce**
(dont know if you can, it seems im the only one with with issue but ill still put what i did)
1. download Community_A-4E-C_v2.0.1.zip
2. download the A-4E by following the instructions
3. launch dcs  

**Expected behavior**
You will load dcs world and see that most of the skins for the A-4E are missing textures but not all of them. For example USN VS-64 Black Lancers is a missing texture but, USN VA-83 Rampagers, 1966 works fine 

**Screenshots**
Rampagers
![Digital Combat Simulator  Black Shark Screenshot 2022 05 15 - 20 38 42 53](https://user-images.githubusercontent.com/105616071/168506177-29ba00a1-6b01-43e5-a0e5-94628394736c.png)

Black Lancers 
![Digital Combat Simulator  Black Shark Screenshot 2022 05 15 - 20 38 35 23](https://user-images.githubusercontent.com/105616071/168506200-d859c27a-2b46-429c-8065-202c47d9744b.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.12.23362 Open Beta]
 - A-4E Version [e.g. v2.0.1]

**Additional context**

**Comment by callmepartario** [comment]
solved: user had overridden liveries int the user liveries folder
