### ISSUE TITLE
Integrity Check fails after playing multiplayer and returning to the DCS main menu

### ISSUE THREAD

**Issue by mani-zaeim** [heclak/community-a4e-c#533]
textures/briefing-map-default @ c:/users/<UsrName>/saved games/dcs.openbeta/mods/aircraft/a-4e-c/skins/1/me
time to time I get IC error which I need to restart the DCS

**Comment by callmepartario** [comment]
this DCS bug appears to be fixed these days, closing until it crops up as an inconvenience again.
