### ISSUE TITLE
Individual trim speed percentage setting sliders for pitch, roll, and rudder

### ISSUE THREAD

**Issue by Drofseh** [heclak/community-a4e-c#534]
**Is your feature request related to a problem? Please describe.**
I'd like to turn down aileron trim to 25%, but keep elevator trim at 50%, currently this is not possible with a single setting that effects all trim controls.

**Describe the solution you'd like**
Add a separate Trim Speed setting for each trim control

**Comment by callmepartario** [comment]
individualized trim speed sliders by axis are added in https://github.com/heclak/community-a4e-c/commit/d29acd0a17decd9b56f2b4534e42b1138403e8c3

**Comment by callmepartario** [comment]
Fixed trim reset in https://github.com/heclak/community-a4e-c/commit/ad0175adc2632098da07edaac04e93f90ce0bd5a - thanks @Drofseh ! (I also added your contributor role on discord, fyi, i forgot to mention that earlier this week!)
