### ISSUE TITLE
Expand mouse button binding options

### ISSUE THREAD

**Issue by Thefifouslain** [heclak/community-a4e-c#536]
**Is your feature request related to a problem? Please describe.**
I personally use a keyboard and mouse to fly and in every other aircraft i use Mouse button 4 and 5 for throttle but on the A-4 you cant bind mouse keys to the throttle.

**Describe the solution you'd like**
I would like for the Throttle Position Continuous to be able to be bound to a mouse key.

**Comment by callmepartario** [comment]
as of https://github.com/heclak/community-a4e-c/commit/573b50359d065c833148aa5a210f4480cf6450a2 the mouse buttons can be bound to anything the joystick buttons can.

**Comment by callmepartario** [comment]
this is all set for next release, thanks for the suggestion. you'll have all kinds of mouse binding options soon for those buttons.
