### ISSUE TITLE
Incompatibility with Anubis Hercules C-130J-30 mod

### ISSUE THREAD

**Issue by heiko-jakob** [heclak/community-a4e-c#541]
**Describe the bug**
When the A-4E module is loaded, and a Hercules with air drop items (vehicles/paratroopers) gets shot down, DCS crashes with:
2022-06-12 08:15:35.020 ALERT   APP: Unhandled exception: No input port in scheme: suppress_ballute

This bug on the Hercules **only** happens when the A-4E mod is loaded. I'm not sure if it's a problem of the A-4 mod or the Hercules mod, but TacView shows the Hercules airdrop items as Mk77mod0 napalm canisters that come with the A-4, so i'd guess there are ID collisions between weapon/airdrop items. 

**To Reproduce**
1.) Install A-4E module and the Hercules module
2.) Shoot down a Hercules that's loaded with air drop items. (paratroopers/air drop vehicles)
DCS crashes completely with last message '2022-06-12 08:15:35.020 ALERT   APP: Unhandled exception: No input port in scheme: suppress_ballute' 

**Expected behavior**
DCS shouldn't crash

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.15.25026 Open Beta
 - A-4E Version 2.0.1
 - Hercules 6.8.2

**Additional context**
I'm not sure if it's a problem of the A-4 mod or the Hercules mod.

**Comment by heiko-jakob** [comment]
Created a [example mission](https://forum.dcs.world/applications/core/interface/file/attachment.php?id=272830&key=5c35ec614c35a140ffa9f453957bda93) that will crash DCS when the A-4E module is loaded.

**Comment by callmepartario** [comment]
word on the street is that this has been fixed; can anyone confirm?

**Comment by heiko-jakob** [comment]
Seems to be fixed. I checked the example mission and it didn't crash anymore.
 DCS 2.8.6.41363
 Hercules 6.8.2
 A-4E-C 2.1.1

**Comment by callmepartario** [comment]
great, closing this.
