### ISSUE TITLE
USN VA-164 Ghostriders livery can't be from 1988

### ISSUE THREAD

**Issue by joshuaborn** [heclak/community-a4e-c#543]
The USN VA-164 Ghostriders livery is listed as circa 1988 and operating from the USS Hancock, but VA-164 was [disbanded in 1975](https://en.wikipedia.org/wiki/VA-164_(U.S._Navy)) and the USS Hancock was [decommissioned in early 1976 and sold for scrap later that year](https://en.wikipedia.org/wiki/USS_Hancock_(CV-19)). This livery appears to be circa 1972 or 1973.

**To Reproduce**
1. Go to Mission Editor.
2. Add an A-4E Skyhawk to the mission.
3. Select "PAYLOAD."
4. Select USN VA-164 Ghostriders LADY JESSIE, 1988 under "PAINT SCHEME."

**Screenshot**
![image](https://user-images.githubusercontent.com/206484/173975266-402459e9-01aa-411c-8fcf-39fd429ed649.png)

**Software Information (please complete the following information):**
 - DCS Version: 2.7.14.24228
 - A-4E Version: 2.0.1

**Comment by callmepartario** [comment]
this livery is an airshow restoration for _one specific plane_, which was still sporting this paint job in 1988, not the entire squadron.
