### ISSUE TITLE
ILS Button and Radio communications

### ISSUE THREAD

**Issue by omega2607** [heclak/community-a4e-c#546]
I use latest version of A4E Community.
In the cockpit, I don't have the ILS on TACAN Selector.
So, I can't use ILS landing mode.

The radio menu is only available for the take-off.
No possibility to call carrier, ATC or other plane to landing.

What is the problem?

I need your help. 

Best regards

**Comment by callmepartario** [comment]
Consult your kneeboard manual - press `RShift+K` in the cockpit or browse the document in PDF there in your install folder. 

Radio details are provided on page 1-2 - chances are you are not using the appropriate `Radio Microphone Push to Talk (PTT)` binding and are relying instead on the communications menu. Like many other high-fidelity modules, you must use the radio button when using the radio to communicate with other units.

As for the ILS, that procedure is detailed on page 1-3 of the manual, with the relevant control panel area shown as item 11 on page 6-4 of the manual. The A-4's ILS system is older and is still called MCL; it's not integrated with the TACAN panel at all.

Consider joining the Discord linked on the project page at https://08jne01.github.io/community-a4e-c/ - that's a great place to get assistance from a user perspective.
