### ISSUE TITLE
CBU 2/A or 2B/A bomblets destroy releasing aircraft

### ISSUE THREAD

**Issue by cissev** [heclak/community-a4e-c#547]
CBU 2/A or 2B/A pod bomblets damage the aircraft once dropped.

To reproduce:

- Equip 2/A or 2B/A dispenser pods
- AWRS settings do not impact behaviour
- start dispensing, in F2 view you can observe bomblets impacting the aircraft and destroying it (track added)

Expected behavior:
CBU 1 pods do not exhibit this behaviour and work as expected (track added)

**Software Information**
 - DCS Version: [DCS 2.7.16.27869 Open Beta]
 - A-4E Version [2.0.1]
 

[Tracks.zip](https://github.com/heclak/community-a4e-c/files/9175794/Tracks.zip)

**Comment by cissev** [comment]
![Screen_220724_144405](https://user-images.githubusercontent.com/109904844/180647587-fd1ac819-5b4f-4efc-9dcc-578089d7ef1b.png)
![Screen_220724_144412](https://user-images.githubusercontent.com/109904844/180647592-dc0d45c9-45a9-4e79-8f80-33be2807557a.png)

**Comment by callmepartario** [comment]
This issue is likely related to #526 - we've got a fix in the works for it, but will keep these as two separate issues for now for resolution testing.

**Comment by callmepartario** [comment]
closing and condensing this, let's move any remaining discussion to #526 as we move toward the next release
