### ISSUE TITLE
DCS authorization

### ISSUE THREAD

**Issue by vfaco** [heclak/community-a4e-c#551]
A4E 2.01 will not load in DCS Open Beta 2.7.16.28157. DCS says it's not authorized. The download is loaded to external drive/DCS Open Beta/Mods/Aircraft.

**Comment by Drofseh** [comment]
<https://github.com/heclak/community-a4e-c#step-2-installing-the-module-files>

"Place the `Mods\aircraft\A-4E-C` folder in into your Windows user folder's Saved Games folder for DCS"
`C:\Users\username\Saved Games\DCS.openbeta`

**Comment by callmepartario** [comment]
as drofseh has noted, you have failed to follow the installation instructions properly - consult https://08jne01.github.io/community-a4e-c/#installation-troubleshooting - and join the discord (link at the top of the page) if you need additional live troubleshooting.

**Comment by vfaco** [comment]
Got it.  Thanks
