### ISSUE TITLE
Add unique Fire Can SON-9 sound to AN/APR-25

### ISSUE THREAD

**Issue by 08jne01** [heclak/community-a4e-c#553]
Should be E band radar.

**Comment by 08jne01** [comment]
Fire can be a tracking and search radar btw. Used for guiding KS-19 flak batterys

**Comment by callmepartario** [comment]
asset added to binaries 

prelim code in https://github.com/heclak/community-a4e-c/commit/33fcb18234d4934383784a594ad7ba867f31ecfa - need to fix up that weird cockpit disappearing shizzle to proceed to collect a proper emitter ID.

**Comment by callmepartario** [comment]
added in https://github.com/heclak/community-a4e-c/commit/9061a269475ea6891b01961c142c5f1b86fe2ddc

**Comment by callmepartario** [comment]
project complete and documented
