### ISSUE TITLE
Seat position

### ISSUE THREAD

**Issue by vfaco** [heclak/community-a4e-c#554]
Is there a control for seat position like the ejection seat height in the DCS F18 and the eyepoint in the FSX/P3D code? I lose the ball over the nose when approaching the ramp and can't see the refueling probe. I can adjust the cockpit camera position but it returns to default when I center the view. Something in the code, maybe?     Thanks

**Comment by callmepartario** [comment]
see issue #430 

in the meantime, the standard cockpit view controls for adjusting head position are your best bet. the eventual implementation of the switch will work much the same.
