### ISSUE TITLE
Add Single Inputs for Throttle Positions (OGG - IGN - IDLE)

### ISSUE THREAD

**Issue by Sepeto73** [heclak/community-a4e-c#556]
Please, consider adding commands for the throttle positions during engine ignition sequence.

- OFF Else IGN
- IDLE Else IGN
- OFF
- IGN
- IDLE

Thanks.

**Comment by callmepartario** [comment]
LOL i *just* filed this at #555 - what a coincidence!

**Comment by Sepeto73** [comment]
As long as it gets done, I´m OK. Thanks.
