### ISSUE TITLE
S_EVENT_SHOT , event id == 1 does not trigger/work in multiplayer server

### ISSUE THREAD

**Issue by ucnanoman** [heclak/community-a4e-c#560]
S_EVENT_SHOT , event id == 1 does not trigger/work in multiplayer server for A-4 only, but works in single player.

**To Reproduce**
Hookup S_EVENT_SHOT or event id == 1 script  (MIST required) for event setup.
- Fire any weapon in multiplayer standalone server and event id == 1 will no trigger/work.

**Expected behavior**
S_EVENT_SHOT or event id == 1 is supposed to trigger and upon event whatever action you set will execute

**Software Information (please complete the following information):**
 - DCS Version: [e.g. 2.7.17.29140 Open Beta Dedicated Server]
 - A-4E (all versions ... tried multiple versions)

**Additional context**
I tried other events event id == 2, 14 and they all work in multiplayer.

**Comment by gcask** [comment]
I was unsuccessful at hitting the issue with the following (really simple) mission (simply rename .zip to .miz, used it to be able to upload on GH).

I have used MIST 4.5.107 and the [sample event shot snippet from HOGGIT](https://wiki.hoggitworld.com/view/DCS_event_shot)

I tried with mk81SE, maybe it's specific to some weapons?

[a4-bugs-event-shot-not-firing.zip](https://github.com/heclak/community-a4e-c/files/9611022/a4-bugs-event-shot-not-firing.zip)

**Comment by ucnanoman** [comment]
Interesting, no I tried it on different weapons it's the same. It's possible some update fixed it. I'll try it again when I get back in town on Monday.

**Comment by ucnanoman** [comment]
I tested your script and if I hit multiplayer from Mission Editor, I was able to not have any problems.
When I try to launch a dedicated multiplayer server with the .miz file, I had the same issue where event id == 1 did not fire/trigger.
This seems to be isolated to dedicated multiplayer standalone server.

**Comment by gcask** [comment]
Interesting, as I had no issue with a dedicated server setup...

I'm also using the Target Impact Tracker Script on my dedicated server, which relies on that event, and it tracks properly.

Sorry I couldn't be of more help :(

**Comment by ucnanoman** [comment]
I'll try creating a new instance of the dedicated multiplayer server and see if that works. Maybe it's old and doesn't have some update needed.

**Comment by callmepartario** [comment]
also, please ensure you have the same version of A-4E-C actually installed on the multiplayer server - failure to have the module installed on the server can cause errors.

**Comment by ucnanoman** [comment]
THAT WAS IT! PROBLEM SOLVED! 
Solution: I needed to make sure I had the airplane downloaded onto the server as well. (I had issues in the past for whatever reason and never needed to put it back on.)
Napalm fireball works for multiplayer now. Thanks so much man.
