### ISSUE TITLE
Add axis bindings Radar Indicator Storage, Brilliance, Detail, Gain, and Reticle knobs

### ISSUE THREAD

**Issue by aetios** [heclak/community-a4e-c#561]
I have a controller with lots of rotary axes and I was planning to use it for radar fine tuning, but it appears that the knobs around the radar screen (gain, detail, brilliance) don't have axis bindings available, where e.g sidewinder volume does. It would be nice to also have the option to map these to an axis.

**Comment by callmepartario** [comment]
posing the same question as #562 - for inputs like these, what kind of axis do you usually assume? a -1 to 1, or a 0 to 1?

**Comment by callmepartario** [comment]
having a little difficulty with these, i think these device_commands may be going straight to the EFM. still working on it, though.

**Comment by aetios** [comment]
> posing the same question as #562 - for inputs like these, what kind of axis do you usually assume? a -1 to 1, or a 0 to 1?
I think I generally have seen axes go from -1 to 1.

**Comment by callmepartario** [comment]
added initial input bindings and command_defs here: https://github.com/heclak/community-a4e-c/commit/a779ce4f682d87055c43c7613d81f2f86d31efa9

additional C++ changes will be needed in the radar code to map the axes to the knobs themselves.

**Comment by callmepartario** [comment]
lua side is all set up for these on develop

**Comment by callmepartario** [comment]
added, thanks nelson!
