### ISSUE TITLE
v2.01 release zip contains a readme for v1.4.2

### ISSUE THREAD

**Issue by Drofseh** [heclak/community-a4e-c#568]
**Describe the bug**
v2.01 release zip contains a readme for v1.4.2

**To Reproduce**
Download https://github.com/heclak/community-a4e-c/releases/download/v2.0.1/Community_A-4E-C_v2.0.1.zip from https://github.com/heclak/community-a4e-c/releases/tag/v2.0.1
Open or Extract `Community_A-4E-C_v2.0.1.zip`
Open `Community A-4E-C Readme.pdf`
See version number is `v1.4.2`
Get confused about nose wheel steering

**Expected behavior**
Obsolete manuals and guides should not be included in the current release

**Suggested Solution**
Remove `Community A-4E-C Readme.pdf` from `Community_A-4E-C_v2.0.1.zip` and reupload it to the `v2.0.1` release.

Alternately, update `Community A-4E-C Readme.pdf` with correct information and reupload

**Comment by callmepartario** [comment]
this won't show up next time, thanks again for the prompt.
