### ISSUE TITLE
How about making this plane able to steer when taxying

### ISSUE THREAD

**Issue by Rinkashikachi** [heclak/community-a4e-c#571]
You can't steer the plane when on the ground. None of your suggested tutorials explain this problem, multiple comments regarding the problem are left unanswered there, the manual doesn't explain it as well. FAQ ignores this Frequently Asked Question as well. Though it answers some questions I bet no one ever asked or was going to ask.

Can you finally add such basic functionality as steering to this plane or, if this feature is somehow present, can you stop ignoring the issue with multiple people not knowing how to do that and explain it **somewhere**? Because neither watching all existing terribly outdated videos on YT, nor reading anything else you suggest to read help with that. And I know for a fact that multiple people are still struggling with that.

**Comment by callmepartario** [comment]
- See the FAQ at https://08jne01.github.io/community-a4e-c/#q-why-doesnt-the-a-4e-c-have-a-nosewheel-steering-button
- See the included kneeboard manual, page 5-4, on TAXI and TAKEOFF
- See the included kneeboard manual, page 6-5, on CONTROLS INDICATOR
- See multiple excellent ground handling tutorials, such as https://www.youtube.com/watch?v=gQOTZB8PqwA and https://www.youtube.com/watch?v=yt9iu7wKWrg
- Stow the attitude, ya dingus.

**Comment by Rinkashikachi** [comment]
You should've seen your FAQ on your front page of the GitHub project. How am I supposed to know that there is another, not abandoned FAQ god knows where?

**Comment by Rinkashikachi** [comment]
> The FAQ is available as a part of the package you downloaded. I cannot help if it you are someone who doesn't read what they already have but goes around making angry posts at someone who provided something you got for free, like a child who wanders into a movie halfway through and wants to know what's going on. That's just not my responsibility, pal.

You must be joking right now. Your FAQ just says "we don't have nosewheel steering button". Cool. That doesn't explain, what to do and if I am steel supposed to use rudder or something wrong with my control scheme. Imagine getting that defensive over uninformative FAQ. That's one of the reasons sims are so niche. Because people who stew in them for decades and spend all their lives playing that one game automatically think that everyone who just gets into is wandering into a movie halfway through

**Comment by callmepartario** [comment]
well golly gee willikers, beav~
- what does the included manual i mentioned say?
- what do the video tutorials i linked have to say?
- there is no magic plug i can put from my brain into yours to make you know the things i know.
