### ISSUE TITLE
Debug message "Selected Station X" is displayed when switching to "Bombs & GM ARM" as well as after firing

### ISSUE THREAD

**Issue by Tuuvas** [heclak/community-a4e-c#576]
It seems there is a debug message reading "Selected Station X" and the player switches to "Bombs & GM ARM".  This message is also displayed when the player launches 1 of 2 AIM-9P5s with both stations selected.  I did not do a thorough test to see what every condition was, but at the very least you should replicate this issue with the following steps:

1. Open the "Caucasus A-4E-C Dogfight vs F-14A Veteran.miz" in Mission Editor
2. Add AIM-9P5s to the outer-most stations.  Stations 1 and 5.
3. Start the mission
4. Master Arm ON
5. Guns Ready
6. Select station switches for 1 and 5 
7. Mode select to "Bombs & GM ARM"
8. Find "Selected Station 1" displayed to player
9. Fire missile
10. Find "Selected Station 5" displayed to player

**Comment by twanmal** [comment]
I could not replicate on A-4E-C and DCS build 2.8.2.35759

**Comment by 08jne01** [comment]
Yea sorry guys I need to release a quick fix for this one.

**Comment by callmepartario** [comment]
fixed in 2.1.1!
