### ISSUE TITLE
DCS version 2.7 and 2.8 compatibilities (DCS crashes on load-in)

### ISSUE THREAD

**Issue by Crecheer** [heclak/community-a4e-c#579]
**Describe the bug**
When i try to load into a mission, dcs gest stuck for a while and then crashes

**To Reproduce**
Sadly i dont know

**Expected behavior**
DCS would load normally

**Screenshots**

**Software Information (please complete the following information):**
 - DCS version is the latest from steam
 - Latest mod version

**Comment by Postboote1** [comment]
I got the sma issue. 
I reinstalled the mod nothing changed.
I also tieed other maps but it crashed again

**Comment by callmepartario** [comment]
Can you provide your DCS version number and the A-4E-C version number?

Remember: 
If you are on DCS 2.7.x, you want to use [A-4E-C version 2.0.1](https://github.com/heclak/community-a4e-c/releases/tag/v2.1).
If you are on DCS 2.8.x, you want to use [A-4E-C version 2.1](https://github.com/heclak/community-a4e-c/releases/tag/v2.0.1).

**Comment by Postboote1** [comment]
DCS Version: 2.7.18.30765
Mod version: 2.1.0

**Comment by callmepartario** [comment]
well there's your problem then. roll back to A-4E-C 2.0.1, and when your DCS version updates to 2.8.x, re-upgrade to A-4E-C 2.1.

**Comment by Postboote1** [comment]
but how can I dowenload an older version?

**Comment by Postboote1** [comment]
But how do I download it

**Comment by callmepartario** [comment]
I already provided links above to the two relevant versions of the A-4E-C. 
Each version has a ~1 GB zip file in the update post's "Assets" section below the release post.
