### ISSUE TITLE
No Nose Wheel Steering button

### ISSUE THREAD

**Issue by TimberWolf5871** [heclak/community-a4e-c#581]
As the title suggests, there is no setting for Nose Wheel Steering. And not like "Oh I forgot to set it to a button", I mean there's no option to set it to a button at all! Have attached a picture as proof. That's all settings minus axis.

![image](https://user-images.githubusercontent.com/3935287/203453340-57cf5f54-77ab-48bb-beaf-e08aa02668ed.png)

**Comment by callmepartario** [comment]
[in-cockpit-troubleshooting](https://08jne01.github.io/community-a4e-c/#in-cockpit-troubleshooting -- there is no nosewheel steering on this aircraft!)
[Sidekick's Ground Handling Tutorial](https://www.youtube.com/watch?v=gQOTZB8PqwA)
[Sidekick's Ground Handling Tutorial](https://www.youtube.com/watch?v=RiHLHUnA7dc)
