### ISSUE TITLE
DCS crashes while loading missions from instant action

### ISSUE THREAD

**Issue by Alex1996able** [heclak/community-a4e-c#582]
**Describe the bug**
DCS crashes in the following “Instant Action” scenarios:
- cold start, crashes when loading
- carrier start, crashes immediately after being ready to fly

“taxi” scenario works properly, I haven’t tried other scenarios.
The TF-51 Mustang works properly, so it seems the issue is related only to the A-4e-c.

**To Reproduce**
1. Go to 'Instant Action'
2. Click on 'Cold start' or ‘Carrier start’
3. Wait for the error during loading or immediately after

**Expected behavior**
The mission should start without crashing, as it does the “taxi” scenario.

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.8.0.33006 Open Beta
 - A-4E Version 2.1.0
 - latest Visual Studio packages installed

**Comment by callmepartario** [comment]
crashing with 2.1 only happens if the radio functions are unable to initialize. is this still occurring?

**Comment by twanmal** [comment]
I have not been able to reproduce. What do you mean with "if the radio functions are unable to initialize in DCS world" ?

**Comment by callmepartario** [comment]
as of A-4E-C version 2.1, the software tests all the radio and radar functions and mission load-in -- if they fail to initialize, the game crashes immediately rather than waiting untli you've started up and get a system failure. this is a signal that a version mis-match is occurring.

**Comment by callmepartario** [comment]
are you still having this issue?
can you provide any crash logs? 
are you using steam to launch the game?
