### ISSUE TITLE
zip.bomb virus reported in the a4e_airframe.zip

### ISSUE THREAD

**Issue by rdcoe** [heclak/community-a4e-c#583]
I just downloaded the latest release, [Community A-4E-C v2.1](https://github.com/heclak/community-a4e-c/releases/tag/v2.1), and NordVPN's threat detector autodeleted it, because it detected zip.bomb in a4e_airframe.zip.

**Comment by callmepartario** [comment]
nothing we can do about false positives. there' nothing in that zip file but texture fles, so the best you can do is set an exception from your overactive and intrusive antivirus software.
