### ISSUE TITLE
Wheel brakes and Left/Right Brakes

### ISSUE THREAD

**Issue by Zerro-G** [heclak/community-a4e-c#584]
**Describe the bug**
While testing the mod I discovered that both wheel brake, as well as right and left brakes are always on.  In the controls setting, the brakes are set by default to **"on else off"**.  Meaning that I must press the brake levers or toe brake to turn the brakes off.  I believe the brake settings should be set by default to **"off else on"**.  Meaning that the brakes should be off unless I actuate the brake levers or toe brake(s). 

This is very much an issue when taxi.  If the brakes are on at all times, I cannot taxi, especially if I have rudders without toe brakes.

**To Reproduce**
1. Go to 'wheel brakes or right/left wheel brakes'
2. Click on 'brake activation button'
4. See error - Brakes are engaged at all times until I press the brake levers or toe brakes.

**Expected behavior**
The brakes should be off unless I actuate the brake levers to actuate them.  **"off else on"**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.8.1.34667 Open Beta]
 - A-4E Version [e.g. v2]

**Additional context**
Add any other context about the problem here.  The mod is excellent.  I have rudders without toe brakes.  As the brakes are always on, I cannot roll to turn while taxi.

**Comment by callmepartario** [comment]
can anyone else reproduce this? brake bindings are working fine for me.

**Comment by Zerro-G** [comment]
It is not that the bindings are not working.  What is happening is the brakes are by default engaged until I press the brake lever (on else off), where they should be (off else on).

Greg
Index Point Holsters
________________________________

**Comment by callmepartario** [comment]
have you set an axis to control the brakes? Stray inputs may be holding your brakes down. It is very common to need to invert those, i have to do it for the majority of DCS modules, myself.

**Comment by Zerro-G** [comment]
Good suggestion.  However, I am unable to access the axis tune options.  The tune options are unaccessable.

Greg
Index Point Holsters
________________________________

**Comment by callmepartario** [comment]
did you upgrade from an older version of the A-4E-C? have you tried generating a clean input configuration for the aircraft?

**Comment by Zerro-G** [comment]
Good question.  I am using version 2 of the A4, downloaded from GitHub.  Before adding the folder of the updated aircraft, I deleted the old folder.  Should I install it another way?

Greg
Index Point Holsters
________________________________

**Comment by Zerro-G** [comment]
OK.  What is the full path to the input folder?

Greg
Index Point Holsters
________________________________

**Comment by Zerro-G** [comment]
Is this path in the saved games folder?

Greg
Index Point Holsters
________________________________

**Comment by callmepartario** [comment]
yes, in the same strucure as the module, but DCS/config/input/a-4e-c, not the module's folder. this is where dcs stores your custom keybinds for each module.

**Comment by Zerro-G** [comment]
I've included two screen shots of the DCS keybinds.  Both show keybinds highlight wheel brakes.  One screenshot is from the Systems keybinds, and the other is from the Axis Commands. You can see that only one allows access to Axis Tune.

I am able to reverse the brake axis from the Axis Command section of the keybinds.

Greg
Index Point Holsters
________________________________

**Comment by callmepartario** [comment]
if you are using email to reply, your attachments are not coming through. what i might advise most at this point is joining the discord for a live troubleshoot over a livestream -- the discord link is on the project page at https://08jne01.github.io/community-a4e-c/

**Comment by Zerro-G** [comment]
Thanks for the option of getting on Discord.  Your earlier suggestion of deleting the inputs folder for this module has resolved the issues I was having.

The attachments were to highlight something I noticed while working through this issue.  However, I may post my screen shots the clearification and discussion.

Greg
Index Point Holsters
________________________________

**Comment by callmepartario** [comment]
good deal, i will close the issue, glad you got it sorted.
