### ISSUE TITLE
Other A-4 variants

### ISSUE THREAD

**Issue by SteelersForever** [heclak/community-a4e-c#588]
**Is your feature request related to a problem? Please describe.**
No, it isn't. However, I really would love to create an A-4B/C Skyhawk mod that is a little different than this mod.

**Describe the solution you'd like**
I have an idea: I can take out a few of the features that aren't on the A-4B/C and that'll be ok.

**Describe alternatives you've considered**
I have used the A-4E-C, and it's great, but I just want other A-4 variants.

**Additional context**
Question: What all would I need to change in the A-4E-C to make the A-4B/C a reality?

**Comment by callmepartario** [comment]
I'm afraid doing any additional variants is outside the capability of the team and scope of the project.
