### ISSUE TITLE
add countermeasure dispenser select X else Both keybinds

### ISSUE THREAD

**Issue by Drofseh** [heclak/community-a4e-c#589]
**Is your feature request related to a problem? Please describe.**
Dispenser select currently has keybinds for, 1, 2, Both, Cycle, and Toggle 1/2
![2f6e39c6822be1a81393e6b09e9e3615](https://user-images.githubusercontent.com/15274778/214769880-8b4874dd-92a5-4fa0-a7ab-0f563bda4581.png)

**Describe the solution you'd like**
Add keybinds for following:

1 else BOTH
2 else BOTH

This will allow a single On -Off-On switch to control all three positions.

**Comment by callmepartario** [comment]
good suggest, that'll be in there for next time, added in https://github.com/heclak/community-a4e-c/commit/bca210b142eddd1eec442c8a524090fd5dbed4f1
