### ISSUE TITLE
Kneeboard page 1-5 (loadout options) listing errors

### ISSUE THREAD

**Issue by monotonea** [heclak/community-a4e-c#590]
The kneeboard weapon list and in-game loadout do not match in some cases.

 - AN-M30A1, AN-M64, AN-M65 and M117 are not available in the game for now while still listed in the kneeboard.
 - Single AN-M81 on Sta.1/5 is available in the game while unlisted in the kneeboard.
 - Single AN-M66A2 on Sta.3 is available in the game while unlisted in the kneeboard.
 - Single MK 20 Rockeye on Sta.1/5 is available in the game while unlisted in the kneeboard.
 - Mk 70 MOD 0(750lb variant) is not available on Sta.1/5 in the game while shown in the kneeboard.
 - Single or double CBU-2B/A which is not identical to CBU-2/A is available on Sta.2/4 while unlisted in the kneeboard.

Software Information:
 - DCS Version: 2.8 OB
 - A-4E Version 2.1

Supporting docs 

 - In game bomb loadout
![image](https://user-images.githubusercontent.com/86151422/215339951-581ef81e-f0b5-44da-be92-adfb03dbf361.png)

- In game pod loadout sta.2
![image](https://user-images.githubusercontent.com/86151422/215340664-98438ae7-bd80-4f36-a840-cb0000cfa26e.png)

- Kneeboard
![image](https://user-images.githubusercontent.com/86151422/215338651-ed40237d-e9f1-4da2-b9d4-3ced20f3ed8c.png)

**Comment by callmepartario** [comment]
thanks for these corrections. the AN- munitions are still in the package - they may be disabled, however, if you play multiplayer primarily, they could be set to unavailable by the server owner for various reasons in favor of official munitions. the rest of these corrections are well-taken, and i will make fixes for the next release.

**Comment by callmepartario** [comment]
Fixed in dev. A replacement file for `/A-4E-C/Cockpit/KneeboardResources/a4e_cockpit_kneeboard_15.png` is available for anyone who wants the fix ahead of time:

https://cdn.discordapp.com/attachments/527134526305075210/1105620783310573638/a4e_cockpit_kneeboard_15.png

**Comment by callmepartario** [comment]
related for changelog: added sidewinder and shrike delivery information to page 3-5
