### ISSUE TITLE
ILS Ability

### ISSUE THREAD

**Issue by amn2be** [heclak/community-a4e-c#593]
**Is your feature request related to a problem? Please describe.** No.

**Describe the solution you'd like**

Using ILS having the ability to ref kneeboard with all related material in it. Currently does the job as is for all landings. Wanted to to free fly on non impact servers and practice approaches. Videos on You tube show old model with ILS switch installed.

**Comment by callmepartario** [comment]
are you playing on ECW? they have export scripts that might be disabling kneeboard ILS data import functions. check your experience using a single-player mission, please.
