### ISSUE TITLE
Add Hydra rockets to outer pylon rocket pod options

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#597]
i see this requested frequently - is there any reason other than an oversight we haven't added the hydras as options for outer rocket pods?

**Comment by Drofseh** [comment]
#591

**Comment by callmepartario** [comment]
if adding, update kneeboard page 1-5

**Comment by callmepartario** [comment]
- everything looks like its in there and working. i'll go in for a uniformity pass on the files, but these are ready to mess about with and test, everything seems to be firing just fine. watching 171 hydras fly out of the scooter is pretty bananas.
- note that i also updated the loadout naming conventions to better match standard modules like the F-18 and A-10. This makes them a little less cleanly sorted, and verbose, but you get used to it.
- i kept, but commented out a few CLSIDs for the hydras in a LAU-3 since those are not loading in. it's very strange; the single CLSIDs seem to just get ignored - suggesting they are not valid. The created double and triples create a loadout entry properly with an empty rack. are there any aircraft known to load Hydras in a LAU-3 out there?
- we might can look at defining a HEAT hydra rocket to use in the LAU-61, or define the LAU-3 to carry it, i am still looking into that, but this will do for now.

**Comment by callmepartario** [comment]
(double check weight values to clear errors in the log on these loadouts)

**Comment by callmepartario** [comment]
just a double check for myself to hit up the kneeboard now that the LAU-3 Hydras are in. thanks for the assist, nelson.

**Comment by callmepartario** [comment]
also, ensure LAU-3 hydras are populating to kneeboard correctly, deprecate LAU-61 entries

**Comment by callmepartario** [comment]
all the new LAU-3s should now be populating properly to the kneeboard manual, but some other changes have moved some things around. i still need to get the binaries updated to reflect these changes, but we have some new room to document the ADF, tacan, radio, or mcl in more detail if we want.

**Comment by callmepartario** [comment]
kneeboard updates should be in decent shape on the binaries, just need to do a little accommodation cleanup on the LUA.

**Comment by callmepartario** [comment]
kneeboards should be good to go on this front.

**Comment by callmepartario** [comment]
closing this for now, file a new issue if any rocket-related mayhem unfolds.
