### ISSUE TITLE
Mk4 gunpod deactivated after bomb release 

### ISSUE THREAD

**Issue by ACGLaCrepe** [heclak/community-a4e-c#601]
**Describe the bug**
Hi,
I m new to the A4 module and absolutely love what you ve done. Wish I could donate to thank you.
Anyway I found that after releasing bombs my gunpods were unresponsive.
Don t know if it is an historical feature but doubt it.

**To Reproduce**
1. Select an A4 with bombs and Mk4 guns (tried with wings or center line Mk4 got the same)
2. Activate Gunpods (RH+LH and/or Center + arm g/p + master arm + trigger)=it works
3. Let it be and now drop your bombs (in my case it was mk82 SE ripple*4/6 nose+tail fuse+80m/s but got the same with other loads)
4. Squeeze the trigger again, nothing comes out even if resetting the gunpods ; internal guns can work though after arming.

**Expected behavior**
Be able to fire gunpods with trigger, after releasing bomb with weapon release button.
**Screenshots**
N/A
**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.8.6.41363 Open Beta]
 - A-4E Version [e.g. v2.1.1]

**Additional context**
N/A
Thanks for looking into it or tell me it s historical !

**Comment by callmepartario** [comment]
without seeing exactly what you did it's hard to replicate. it's possible you CLEARed the gunpods, rendering them inoperable until the ground crew resets them. i'm unable to reproduce your error, everything appears working find for me.

**Comment by ACGLaCrepe** [comment]
Hi, thanks for your reply.
It s not a visual bug I was reporting more a functional one.
I m sure I didn t clear the pods, that s the first thing I checked and I ve learned that mechanic, like the limited number of internal cannons arming.
I cornered the issue to the CMPTR bomb release mode : in CMPTR, gunpods don t work. They work again in all other weapon function selector switch postition : that I can accept. But after releasing bombs in CMPTR they don t come back to life even after rotating the WFS back to any position. The pods have not been dropped nor cleared and the LH+RH are still engaged. Just no bullets coming out. My conf this time was 1=Aim9P5 // 2=Mk4 // 3=2*Mk83 // 4=Mk4 // 5=Aim9P5.

**Comment by ACGLaCrepe** [comment]
I got it to work : and I found the issue or the mechanic behind : it was the AWRS mode selector switch on RIPPLE that was inhibating the gunpods. So to conclude you have to be on amything but CMPTR and AWRS on STEP. Don t know if that's historical but at least now I can take the pods without fear of losing their benefit randomly :)

**Comment by callmepartario** [comment]
having the AWRS on an in paired mode is probably what is tripping you up, you want those off when you are operating a gunpod, especially one on the center pylon.
