### ISSUE TITLE
Radar Altitude Warning Axis Commands Option

### ISSUE THREAD

**Issue by peeecet** [heclak/community-a4e-c#607]
Currently setting the radar altitude warning has only digital options (continuous increase/decrease, rotary increment/decrement).

An axis command would enable the use of a potentiometer for setting the altitude.

This adds the feature of having the desired altitude already set at startup.

**Comment by callmepartario** [comment]
so, in reviewing how the device works and the code surrounding it, the best i can give you is a slew, which appears to be how the device is built, settings its own rate differently at different altitude ranges (notice how it slows down in the 100-200 feet range). it won't let you pre-set, but you will get the tactility with a self-centering potentiometer.

**Comment by callmepartario** [comment]
added a slew input with https://github.com/heclak/community-a4e-c/commit/ec8bf63e71d28f41e13de6d236ba67b82fc9346b
