### ISSUE TITLE
Intermittent TACAN and MCL failures in multiplayer

### ISSUE THREAD

**Issue by vfaco** [heclak/community-a4e-c#609]
**Describe the bug**
The tacan and ILS do not work. The tacan and the MCL are set to the carrier channels but the tacan needles and DME are frozen and the ILS needles do not activate even though they test correctly. The tacan panel does not have the ILS option so I guess the needles should activate automatically. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS open beta 2.8.8.43704
 - A4E v2.1.1

**Additional context**

**Comment by callmepartario** [comment]
things are working fine for me. are you playing in multiplayer?

**Comment by vfaco** [comment]
Single player. Since it's working for you I guess I'll try removing and restoring the mod.

**Comment by vfaco** [comment]
Reloaded mod. Tacan now OK, ICLS still not working.

**Comment by jkaryan** [comment]
Interesting, playing in MP today on a locally hosted dedicated server, we couldn't get the ships in the mission to show up on TACAN (set to 1X, 73X and 74X), but stations on airfields like 21X (Incirlik, since this was Syria map) worked fine. Might try to remove and reinstall.

**Comment by callmepartario** [comment]
Getting additional similar reports from several servers that there are intermittent interoperability issues and occasional crashes when using radio functions in multiplayer.

**Comment by 08jne01** [comment]
If people could send their mission files so I can replicate it.

**Comment by callmepartario** [comment]
Mission file for replication - https://cdn.discordapp.com/attachments/518815335013679104/1164343696205025340/Training_Server_V2.08_FallA..miz

crash should be replicable by clicking the MCL selector once it's in operation

**Comment by jkaryan** [comment]
Mission file for replication: 
[Free_Flight_and_Practice_-_Syria.zip](https://github.com/heclak/community-a4e-c/files/13059097/Free_Flight_and_Practice_-_Syria.zip)
