### ISSUE TITLE
A-4E-C Mod download

### ISSUE THREAD

**Issue by SquattingBear1** [heclak/community-a4e-c#612]
Hello heclak, 
I attempted to download the community mod but got the error message "Failed - Download error".
 Is there another site to download the mod?

Thanks,

Matthew

**Comment by callmepartario** [comment]
That sounds unusual.

To confirm, the release downloads are available from https://github.com/heclak/community-a4e-c/releases

The current release is https://github.com/heclak/community-a4e-c/releases/download/v2.1.1/Community_A-4E-C_v2.1.1.zip

That's what you're unable to download? We have not provided any mirrors in the past, so I'd like to confirm the issue first.

**Comment by callmepartario** [comment]
any movement on this? were you able to complete a download?

**Comment by callmepartario** [comment]
closing this issue.
