### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by Emtageclan8** [heclak/community-a4e-c#613]
**Describe the bug**
when trying to launch DCS a pop up appears saying "The following DLCs are not authorized and will be 
disabled:
A-4E-C"

Software Information
 - DCS Version: v2.8.8.43704
 - A-4E Version v2.1.1

**Additional context**
i installed through steam into the mods aircraft folder and try to launch but it says Authorization failed

**Comment by callmepartario** [comment]
you have installed the module incorrectly. you will need to remove the improperly installed files before making a proper installation as outlined at https://08jne01.github.io/community-a4e-c/#installation-troubleshooting
