### ISSUE TITLE
DCS 2.9 OpenBeta - UHF Radio, ADF, TACAN, and MCL issues

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#614]
DCS OpenBeta 2.9 appears to cause crashes when the radios are powered or manipulated in DCS 2.9 (Filing this separate from #605 and #609 in case they need to be tracked or addressed separately).

To reproduce:

Instant Action, Air-to-Air refueling, power and tune the TACAN to the tanker frequency

**Comment by Montykoro** [comment]
Is fixed? any chance to release the fix now and the other fixed later?

**Comment by callmepartario** [comment]
closing this one out as we head into release candidate town for 2.2. things are looking pretty solid, but we'll know more after some dedicated multiplayer testing in the wild this week.
