### ISSUE TITLE
AI won't launch on Supercarrier

### ISSUE THREAD

**Issue by charlie5001** [heclak/community-a4e-c#617]
**Describe the bug**
When A4e AI spawns in parking hot or cold the AI will line up, one of the officers will tell it to move forward over the hump, the AI will just sit still.

I tested start from take off and it would take off.

Notes:

This was working before the 2.9 update

Sorry for my terminology.

**To Reproduce**
1.Make a new mission with the super carrier module and an a4e AI on parking hot or cold start
2. The plane will go to the catapult and line up. The guys will put in the holdback Bar. One of the officers will tell the A4 to move up. But nothing happens.  (Other aircraft will launch fine)

**Expected behavior**
The A4E to hookup to the catapult and launch

**Screenshots**
![Digital Combat Simulator 23_10_2023 3_04_04 pm](https://github.com/heclak/community-a4e-c/assets/67763783/89b29cba-cf4d-4a81-adbf-1de4d22d11f3)

image above is where the a4e stops doing anything.
Does the holdback bar look a bit odd?

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.9.0.48601 Open Beta
 - A-4E Version v2.1.1

**Comment by nsargent76** [comment]
I can attest to this bug as well.  I have experienced the same behavior from the AI A-4’s on the super carrier module. 

I can also say the AI was tested on the Forestall and it works perfectly. This is an issue with the Super Carrier module only in my testing.

**Comment by callmepartario** [comment]
this is probably related to #620 -- expecting it to be resolved with the next OpenBeta hotfix, but we'll keep an eye on it.

**Comment by callmepartario** [comment]
closing this, any further activity should be put forth on #620
