### ISSUE TITLE
User troubleshooting: Throttle step position won't move

### ISSUE THREAD

**Issue by patton610** [heclak/community-a4e-c#618]
Upon first use of the a4 in while but still the most recent version, the throttle will not ignite or move from the off position 
. In the past, right and left clicks advanced  and regressed the throttle until the regular axis could be used. 

**To Reproduce**
launch from cold start and proceed through start up procedure 

**Expected behavior**
ignition 

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [2.9 open beta 
 - A-4E Version 2.1.1

**Additional context**
I did make some changes to my physical pc set up recently, but since no other aircraft seems effected i believe this might be 2.9 related.

**Comment by callmepartario** [comment]
if you have not used the module in a while or upgraded, you might need to reset your control bindings. clear them out and give it a new go.

**Comment by patton610** [comment]
I.... don't know what is up. I installed the aircraft again using a fresh install and there isn't any change. The hotas bindings don't work. The keyboard default bindings don't work. this is the only aircraft that I am having this issue with. I could understand if the 2.9 update had led the clickpit to malfunction due to resolution changes, but the keyboard binding isn't working. this issue seems isolated to the throttle. I have no other controllers connected that might conflict.  all the other switches  and axes work. I am using a cold start prebuilt scenario might try to build my own mission and see if that helps.

**Comment by patton610** [comment]
no change  going to delete everything again  and restart

**Comment by patton610** [comment]
second install new , no throttle function is it possible that the code in some way is corrupted or maybe not interacting with dcs? maybe dcs  is bad? everything else is fully functional though. all other modules etc

**Comment by patton610** [comment]
i cleared and then tried multiple  input combinations. only thing left is is to delete the  binding file itself. it is something beyond the stick as the keyboard inputs dont work either

**Comment by callmepartario** [comment]
yes, please, do that.

**Comment by patton610** [comment]
I am out of ideas i vaguely remember input config files being in the dcs install location somewhere , but ive yet to find anything specific to the A-4E-C and ive deleted the input files in the saved games folder multiple times. Unless there is a hidden file  or undocumented conflict .... I dont know. I use viacom pro, srs I have some mod aircraft but none that are listed in the known issue list.

**Comment by Drofseh** [comment]
Just to confirm, your throttle axis is all the way back before you're trying to click on the throttle handle right?
Clicking on it won't work if your throttle axis input is greater than 0

**Comment by patton610** [comment]
It should be set to zero by default. currently I am waiting on some parts for a vkb throttle module so I have been using an encoder wheel on my stick. but as i understand it they are read as rapid key presses so,  I should be able to use anything other than an axis binding with the physical control. i'll try to zero it next test

**Comment by Drofseh** [comment]
I recommend opening the Controls Indicator so you can see the exact position of each axis. RCTRL+ENTER

**Comment by callmepartario** [comment]
if you have continued issues with this after resetting your bindings, please join the A-4E-C discord (see https://08jne01.github.io/community-a4e-c/ ) for some live tech support and troubleshooting. i'm confident we can sort things out.
