### ISSUE TITLE
Can't access external views

### ISSUE THREAD

**Issue by Mamakin72** [heclak/community-a4e-c#622]
hello everyone.
I can't seem to activate the external views, they don't work. With all the other modules I have no problem.
The same thing was happening to me with the previous version on 2.8. 
Where am I going wrong? I hit F2 or F3 and nothing happened...

**Comment by Mamakin72** [comment]
Hi again.
Looks like no one of F buttons works...
Any suggestion??

**Comment by callmepartario** [comment]
i'm not having any issue with external views and am unable to replicate this issue. are you certain you didn't de-bind some inputs?

**Comment by Mamakin72** [comment]
Yes, when I move to other plane in the same session F keys works just fine. Is there something in the control menu the I've to deal with?
I use VR Reverb G2
Thanks

**Comment by callmepartario** [comment]
you still might have unbound view keys specific to the A-4E-C. Try resetng your keyboard controls to the defaults and see if that helps.

**Comment by Mamakin72** [comment]
I'll try, than you.

**Comment by callmepartario** [comment]
if you continue to have issues after resetting your control bindings, please join the A-4E-C discord (see https://08jne01.github.io/community-a4e-c/ ) for a live troubleshoot via livestream and we'll see what might be throwing you off.

**Comment by Mamakin72** [comment]
Thanks. I still not give it a try. As sono as possible I’ give you a
feedback.

Il giorno lun 30 ott 2023 alle 15:48 Partario Flynn <
***@***.***> ha scritto:

**Comment by Mamakin72** [comment]
Hello.My fault, the keyboard assignments were totally erased...that's why no keys worked....Thanks anyway for the help.Luca Inviato da Posta per Windows Da: Partario FlynnInviato: lunedì 30 ottobre 2023 15:48A: heclak/community-a4e-cCc: Mamakin72; AuthorOggetto: Re: [heclak/community-a4e-c] Can't access external views (Issue #622) if you continue to have issues after resetting your control bindings, please join the A-4E-C discord (see https://08jne01.github.io/community-a4e-c/ ) for a live troubleshoot via livestream and we'll see what might be throwing you off.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
