### ISSUE TITLE
Community A-4E-C v2.2 Crashed on Mission load

### ISSUE THREAD

**Issue by Alpha19299** [heclak/community-a4e-c#628]
**Describe the bug**
When I click instant action or fast mission, during loading screen it crashes at "Spawning Objects"

**To Reproduce**
1. Click instant action > A4 plane / Create fast mission using A4 -- OK
2. Loading screen 1: initializing terrain -- OK
3. Loading screen 2 (with A4 background): .. spawning objects --crashed

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: DCS Worls Steam Edition - Build ID: 11806347
 - A-4E Version: Community A-4E-C v2.2

**Comment by Drofseh** [comment]
A-4E-C v2.2 requires DCS v2.9.
You're using build ID 11806347, which is DCS v2.8.7
You need upgrade your DCS to the latest v2.9 Open Beta, or you need to downgrade your version of the A-4E to v2.1.1

**Comment by callmepartario** [comment]
This is likely the culprit -- once you determine the version you need, it can be downloaded from https://github.com/heclak/community-a4e-c/releases/
