### ISSUE TITLE
Incorrect model of volume knob on armament panel

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#63]
The shape of the volume knob on the armament panel is incorrect. The knob should a dual concentric knob with the centre portion protruding.

![armament panel volume knob](https://user-images.githubusercontent.com/46121009/52068385-8e690180-25b7-11e9-89df-a8a7db805cc4.jpg)

**Comment by callmepartario** [comment]
fixed in release candidates for 1.4
