### ISSUE TITLE
The gun and AIM-9 both fire with the trigger depressed in BOMBS&GM ARM

### ISSUE THREAD

**Issue by sav07** [heclak/community-a4e-c#635]
**Describe the bug**
The gun and AIM-9 both fire with the trigger depressed. 

This occurs with the Weapon Function Selector Switch in BOMBS & GM ARM, Guns

**To Reproduce**
1. Go to 'Armament Panel.'
2. Click on 'Guns-Ready'
3. Click on 'Guns-Station 1,2,3,4 (as required for AIM-9- Ready'
4. Select 'BOMBS & GM ARM on WFSS"
5. Select 'Master - On'
6. Depress Trigger
7. Depress Bomb Release Button

**Expected behavior**
Expect Gun to fire with Trigger (when armed and in Bomb & GM-ARM; not both Gun and AIM-9. Expect AIM-9 to fire with bomb release switch.

**Screenshots**
N/A

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.9.1.48335 Open Beta]
 - A-4E Version [v2.2]

**Additional context**
Not sure if it is functioning as intended, but it doesn't appear to be right.

**Comment by callmepartario** [comment]
sorry, this behavior is correct for the aircraft.

**Comment by sav07** [comment]
No worries, thanks for the speedy reply.
