### ISSUE TITLE
Lock Slats Checkbox Option

### ISSUE THREAD

**Issue by RuneDogg** [heclak/community-a4e-c#657]
Could we get a Menu Checkbox option to lock the Leading Edge Slats in the closed position?  This is how the Blue Angels flew, but also there were occasions where slats would become Inop for various reasons, maintenance, battle damage, etc.  

Thank you for your consideration.  

-Preston Martin

**Comment by callmepartario** [comment]
this already exists, consult the kneeboard on page 4-6.
