### ISSUE TITLE
Add catapult launch sounds

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#76]
Some sounds should be added for the catapult launch to improve immersion.

**Comment by callmepartario** [comment]
relatedly: place a large-scale "smokewinder" effect at front wheel during cat launch?

**Comment by callmepartario** [comment]
Useful sound assets:
\DCS\Sounds\Effects\AircraftsCarrierCatapultTakeoff.wav
\DCS\Sounds\Effects\AircraftsCarrierCatapultTakeoff_In.wav
\DCS\Sounds\Effects\CarrierLaunchBarDisconnect.wav
\DCS\Sounds\Effects\CarrierLaunchBarDisconnect_In.wav

RELATED: Carrier landing hook/cable sounds:
\DCS\Sounds\Effects\CarrierArrestedLanding.wav
\DCS\Sounds\Effects\CarrierArrestedLanding_In.wav

**Comment by heclak** [comment]
Catapult launch sounds are added. Landing sounds are work in progress

**Comment by callmepartario** [comment]
calling this closed for now, framework for improvement is in place.
