### ISSUE TITLE
Flap in full down position is clipping with HIPEG gunpods

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#8]
I'm not sure how this needs to be fixed. IE. if the HIPEG models are off or its a positions issue. From photos, the front of the HIPEG looks like they are in the correct position (with reference to the nose gear)

![dcs_2018-12-28_11-49-42](https://user-images.githubusercontent.com/46121009/50502017-0b73f900-0a97-11e9-8232-2d5432596b9e.jpg)
![dcs_2018-12-28_11-52-07](https://user-images.githubusercontent.com/46121009/50502019-0dd65300-0a97-11e9-9316-05ca3cbcfb4e.jpg)

**Comment by heclak** [comment]
https://www.youtube.com/watch?v=rntZbKY68gk

From the video reference, it looks like the rear taper of the gun pods need to be much sharper. The gunpods might also need to be pointing slightly higher inside of point down. Or is might be the mounting height.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by callmepartario** [comment]
closing this issue for a duplication merge with similar issues.
