### ISSUE TITLE
BUG - Altimeter in NTTR

### ISSUE THREAD

**Issue by DISCOVMA131** [heclak/community-a4e-c#82]
Have seen this several times in a row now at Nellis in particular, altimeter is incorrect and you cannot set field elevation - Creech seems to be OK, have not tried other fields in NTTR yet - this was in stable V1.02 and the 1.03Beta

**Comment by heclak** [comment]
This is probably related to the primary issue of the getBarometricAltitude() Lua function not returning the correct value from the sim. #146
