### ISSUE TITLE
Suggest clickable point in cockpit to hide control stick

### ISSUE THREAD

**Issue by heclak** [heclak/community-a4e-c#9]
Not an urgent issue. But might I suggest having a click point at the base of the control stick for hiding the control stick instead of a mandatory keybind? The other modules all have this so it would be good to add this for consistency.

**Comment by callmepartario** [comment]
there is now a bind present for this, but no default key is assigned. the F-18 also has an entry and the default key is backspace, which is currently unused for the A-4, so i suggest this as a default for this entry.

**Comment by heclak** [comment]
Implemented for next version.
