### ISSUE TITLE
COCKPIT - unwrap inside of instrument casings

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#90]
inside circumference of instrument cases would look better and not get the illuminated streaks if they were unwrapped to some generic dark space.

see:
![](https://cdn.discordapp.com/attachments/543940775583416368/543952564505280516/unknown.png)

**Comment by heclak** [comment]
Just checked on this. Seems like there needs to be more padding between the dial face and bezel. Maybe switching to a trim sheet for the bezel would be a better idea?

**Comment by callmepartario** [comment]
modeling improvement and texture changes have resolved this issue!
