### ISSUE TITLE
LIGHTING - console and instrument backlighting color and animation

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#91]
Certain items are animated to be on instrument lighting and should be moved to console lighting.
see:
![](https://cdn.discordapp.com/attachments/543940775583416368/544201318655328288/unknown.png)
![](https://cdn.discordapp.com/attachments/543940775583416368/544201400952029185/unknown.png)

Other items are bound to console lighting and should be swapped to instrument lighting:
![](https://cdn.discordapp.com/attachments/543940775583416368/544201746415616012/unknown.png)
![](https://cdn.discordapp.com/attachments/543940775583416368/544201910824075324/unknown.png)
![](https://cdn.discordapp.com/attachments/543940775583416368/544201990025248778/unknown.png)

also recommend resolving color discrepancies between console and instrument backlightingi feel it is also worth moving the color a bit more toward orange.

color intensity-mismatched areas between sheets, see:
![](https://cdn.discordapp.com/attachments/543940775583416368/544203784365015069/unknown.png)

proposed unified backlighting color mockup:
![](https://cdn.discordapp.com/attachments/543940775583416368/544220380521562132/unknown.png)

**Comment by callmepartario** [comment]
just wanted to weight in and say this is relatively low priority - i textured the instruments anew to alleviate some of these problems, and with the other improved lighting it's far less distracting than it used to be.

**Comment by heclak** [comment]
Fixed.
