### ISSUE TITLE
EXTERNAL - MER rack need an unwrap

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#96]
Let's discuss paint / unwrap location for this - perhaps the best place is on the top or bottom of the livery so the paint can patch the pylons ( ? ) - could be a good candidate for replacing the internal of the engine. probably doesn't need to be massively high in detail.

**Comment by heclak** [comment]
Yea. We can do this. But I'll need your help to point out where you want me to unwrap to.

**Comment by callmepartario** [comment]
upwrapped and textured, thanks heclak!
